import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {parse} from 'smol-toml';
import {CodexAppearance,codexTheme,patchAppearance} from '../electron/codex-theme';
import {probeThemeClients,hasClaudeLoader} from '../electron/theme-clients';

const share='codex-theme-v1:'+JSON.stringify({variant:'dark',codeThemeId:'codex',theme:{accent:'#88cfff',surface:'#071523',ink:'#e7f4ff',fonts:{code:'Cascadia Code',ui:'Microsoft YaHei UI'},contrast:55,opaqueWindows:true,semanticColors:{diffAdded:'#80cc99',diffRemoved:'#ee8899',skill:'#aaccff'}}});
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'starsleep-client-theme-')),file=path.join(root,'config.toml');return {root,file,client:new CodexAppearance(file,root),read:()=>fs.readFileSync(file,'utf8'),close:()=>{assert.equal(path.dirname(path.resolve(root)),path.resolve(os.tmpdir()));assert.ok(path.basename(root).startsWith('starsleep-client-theme-'));fs.rmSync(root,{recursive:true,force:true});}};}
test('Codex theme accepts encoded shares and validates the native field types',()=>{assert.deepEqual(codexTheme('codex-theme-v1:'+encodeURIComponent(share.slice(15))),codexTheme(share));for(const value of [share.replace('#88cfff','rgba(1,2,3,1)'),share.replace('"contrast":55','"contrast":105'),share.replace('"codeThemeId":"codex"','"codeThemeId":"not-a-theme"')])assert.throws(()=>codexTheme(value));});
test('Codex configuration changes actual desktop theme fields and preserves unrelated bytes',()=>{const f=fixture();try{const initial='# preserve comment\r\nmodel = "existing-model"\r\n[desktop]\r\nappearanceTheme = "system" # original\r\nlocaleOverride = "zh-CN"\r\n[projects."E:/work"]\r\ntrust_level = "trusted"\r\n';fs.writeFileSync(f.file,initial);f.client.apply(share);const value=parse(f.read()) as any;assert.equal(value.desktop.appearanceTheme,'dark');assert.equal(value.desktop.appearanceDarkChromeTheme.accent,'#88cfff');assert.equal(value.desktop.appearanceDarkChromeTheme.fonts.ui,'Microsoft YaHei UI');assert.ok(f.read().startsWith('# preserve comment\r\nmodel = "existing-model"'));assert.ok(f.read().endsWith('[projects."E:/work"]\r\ntrust_level = "trusted"\r\n'));fs.appendFileSync(f.file,'# changed later\r\n');f.client.restore();assert.equal(f.read(),initial+'# changed later\r\n');}finally{f.close();}});
test('switching native themes keeps the first backup for both variants',()=>{const f=fixture();try{fs.writeFileSync(f.file,'[desktop]\nappearanceTheme = "system"\n');f.client.apply(share);f.client.apply(share.replace('"dark"','"light"'));f.client.apply(share);f.client.restore();assert.equal(f.read(),'[desktop]\nappearanceTheme = "system"\n');assert.equal(f.client.canRestore,false);}finally{f.close();}});
test('external appearance edits block restore without overwriting the client',()=>{const f=fixture();try{fs.writeFileSync(f.file,'[desktop]\nappearanceTheme = "system"\n');f.client.apply(share);fs.writeFileSync(f.file,f.read().replace('appearanceTheme = "dark"','appearanceTheme = "light"'));const before=f.read();assert.throws(()=>f.client.restore(),/外部/);assert.equal(f.read(),before);assert.throws(()=>f.client.apply(share),/外部/);}finally{f.close();}});
test('damaged TOML and nonstandard desktop representations are refused without writes',()=>{for(const original of ['[desktop]\nbroken=','desktop = { appearanceTheme = "system" }\n','[desktop.appearanceDarkChromeTheme]\naccent = "#ffffff"\n','description="""a\nb"""\n']){const f=fixture();try{fs.writeFileSync(f.file,original);assert.throws(()=>f.client.apply(share));assert.equal(f.read(),original);assert.equal(f.client.canRestore,false);}finally{f.close();}}});
test('appearance patch refuses non-appearance keys and injected backup lines',()=>{assert.throws(()=>patchAppearance('[desktop]\n',{model:'model="new"\n'}));assert.throws(()=>patchAppearance('[desktop]\n',{appearanceTheme:'appearanceTheme="dark"\nmodel="new"\n'}));});
test('missing desktop section can be created without touching model settings',()=>{const f=fixture();try{fs.writeFileSync(f.file,'model = "original"\n');f.client.apply(share);assert.equal((parse(f.read()) as any).model,'original');f.client.restore();assert.equal((parse(f.read()) as any).model,'original');assert.deepEqual((parse(f.read()) as any).desktop,{});}finally{f.close();}});
test('isolated client detection never treats fixtures as real native validation',async()=>{const status=await probeThemeClients('isolated/config.toml','isolated/theme.json',true);assert.equal(status.codex.ready,true);assert.match(status.claude.detail,/不代表真实/);assert.equal(hasClaudeLoader('missing-client'),false);});
