import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {Scheduler,defaults} from '../electron/scheduler';
import {Storage,parseStore} from '../electron/storage';
import {parseTransfer,exportTransfer,classifyImport} from '../electron/transfer';
import type {PlanInput} from '../src/shared';
const start=+new Date('2026-09-06T23:59:37');
const normal=(p:Partial<PlanInput>={}):PlanInput=>({name:'未来计划',kind:'shutdown',repeat:'daily',date:'',time:'01:00',weekdays:[],enabled:true,...p});
function harness(at=start){let now=at,calls=0;const s=new Scheduler(defaults(),()=>now,()=>{},()=>{calls++;},()=>{});return {s,get calls(){return calls;},set:(at:number)=>{now=at;},advance:(seconds:number)=>{for(let i=0;i<seconds;i++){now+=1000;s.tick();}}};}
function temp(fn:(dir:string)=>void){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'starsleep-v11-'));try{fn(dir);}finally{assert.equal(path.dirname(path.resolve(dir)),path.resolve(os.tmpdir()));assert.ok(path.basename(dir).startsWith('starsleep-v11-'));fs.rmSync(dir,{recursive:true,force:true});}}
test('quick countdown crosses midnight and fires at exact second, not minute boundary',()=>{const h=harness();h.s.quick({kind:'shutdown',minutes:1});const p=h.s.data.plans[0];assert.equal(p.exactAt,start+60_000);assert.equal(p.date,'2026-09-07');assert.equal(h.s.warnings.length,1);h.advance(23);assert.equal(h.calls,0);h.advance(36);assert.equal(h.calls,0);h.advance(1);assert.equal(h.calls,1);});
test('quick deadline persists through restart and rename; editing date/time converts to ordinary plan',()=>{const h=harness();h.s.quick({kind:'alarm',minutes:1});const s=new Scheduler(parseStore(JSON.stringify(h.s.data)),()=>start+40_000,()=>{},()=>assert.fail(),()=>{});s.reconcile();const p=s.data.plans[0];assert.equal(s.snapshot().plans[0].nextAt,start+60_000);s.save({...p,name:'新名字'},p.id);assert.equal(s.data.plans[0].exactAt,p.exactAt);s.save({...s.data.plans[0],time:'01:00'},p.id);assert.equal(s.data.plans[0].exactAt,undefined);});
test('quick values are bounded and validated',()=>{const h=harness();for(const minutes of [0,1441,1.5,NaN,Infinity])assert.throws(()=>h.s.quick({kind:'alarm',minutes}));h.s.quick({kind:'alarm',minutes:1440});assert.equal(h.s.data.plans[0].exactAt,start+86400_000);});
test('pause persists enabled states, stops current alarms and skips exact resume boundary',()=>{const h=harness();h.s.quick({kind:'shutdown',minutes:1});h.s.demo('alarm');h.s.setPaused(true);assert.equal(h.s.alarms.length,0);assert.equal(h.s.warnings.length,0);assert.equal(h.s.data.plans[0].enabled,true);h.advance(60);h.s.setPaused(false);h.advance(1);assert.equal(h.calls,0);assert.equal(h.s.snapshot().plans[0].status,'已错过');});
test('paused restart stays paused, edits do not run, safe demo expires',()=>{const h=harness();h.s.setPaused(true);h.s.quick({kind:'shutdown',minutes:1});const s=new Scheduler(parseStore(JSON.stringify(h.s.data)),()=>start,()=>{},()=>assert.fail(),()=>{});s.reconcile();assert.equal(s.snapshot().paused,true);assert.equal(s.warnings.length,0);h.s.demo('shutdown');h.advance(30);assert.equal(h.s.warnings.length,0);assert.equal(h.calls,0);h.s.setPaused(false);assert.equal(h.s.warnings.length,1);});
test('pause during a real alarm silences it; resume does not ring the completed occurrence',()=>{const h=harness();h.s.quick({kind:'alarm',minutes:1});h.advance(60);assert.equal(h.s.alarms.length,1);h.s.setPaused(true);h.s.setPaused(false);assert.equal(h.s.alarms.length,0);});
test('fault stop cannot be bypassed by resume',()=>{const h=harness();h.s.setPaused(true);h.s.stop();assert.throws(()=>h.s.setPaused(false),/故障/);assert.equal(h.s.active,false);});
test('export omits history and overrides, imports disabled and deduplicates exact plans',()=>{const h=harness();h.s.save(normal());h.s.quick({kind:'alarm',minutes:30});h.s.data.overrides.private=123;h.s.log('private-log');const raw=exportTransfer(h.s.data.plans);assert.equal(raw.includes('private'),false);assert.equal(raw.includes('createdAt'),false);const parsed=parseTransfer(raw);assert.ok(parsed.every(p=>p.enabled===false));const empty=harness();const result=empty.s.importPlans(parsed);assert.equal(result.imported,2);assert.ok(empty.s.data.plans.every(p=>!p.enabled));assert.equal(empty.s.warnings.length,0);assert.equal(empty.s.importPlans(parsed).duplicate,2);assert.equal(classifyImport([...parsed,...parsed],[],start).accepted.length,2);});
test('import skips expired one-offs and rechecks expiry at confirmation',()=>{const h=harness();h.s.quick({kind:'shutdown',minutes:1});const parsed=parseTransfer(exportTransfer(h.s.data.plans));assert.equal(classifyImport(parsed,[],start).accepted.length,1);const later=harness(start+60_000);assert.deepEqual(later.s.importPlans(parsed),{imported:0,duplicate:0,expired:1});});
test('corrupt/oversize imports are rejected without partial state changes',()=>{const h=harness();h.s.save(normal());const before=JSON.stringify(h.s.data);for(const raw of ['broken',JSON.stringify({format:'starsleep-plans',version:9,plans:[]}),JSON.stringify({format:'starsleep-plans',version:1,plans:[normal(),{...normal(),time:'30:00'}]}),' '.repeat(1024*1024+1),JSON.stringify({format:'starsleep-plans',version:1,plans:Array(501).fill(normal())})])assert.throws(()=>parseTransfer(raw));assert.equal(JSON.stringify(h.s.data),before);});
test('migration writes a persistent original v1 backup and preserves future plans',()=>temp(dir=>{const h=harness();h.s.save(normal());const original=JSON.stringify({...h.s.data,version:1,paused:undefined});fs.writeFileSync(path.join(dir,'schedules.json'),original);const store=new Storage(dir),data=store.load();assert.equal(data.version,2);assert.equal(data.paused,false);assert.equal(data.plans.length,1);assert.equal(fs.readFileSync(path.join(dir,'schedules.v1.backup.json'),'utf8'),original);data.paused=true;store.save(data);assert.equal(store.load().paused,true);assert.equal(fs.readFileSync(path.join(dir,'schedules.v1.backup.json'),'utf8'),original);}));
test('migration backup failure never overwrites the old source',t=>temp(dir=>{const original=JSON.stringify({...defaults(),version:1,paused:undefined});const file=path.join(dir,'schedules.json');fs.writeFileSync(file,original);const open=fs.openSync;t.mock.method(fs,'openSync',(...args:Parameters<typeof fs.openSync>)=>{if(String(args[0]).endsWith('schedules.v1.backup.json'))throw new Error('backup denied');return Reflect.apply(open,fs,args);});assert.throws(()=>new Storage(dir).load(),/backup denied/);assert.equal(fs.readFileSync(file,'utf8'),original);}));
test('unknown storage version never falls back to older backup',()=>temp(dir=>{const store=new Storage(dir);fs.writeFileSync(store.file,JSON.stringify({...defaults(),version:3}));fs.writeFileSync(store.file+'.bak',JSON.stringify(defaults()));assert.throws(()=>store.load(),/更高版本/);}));
test('quick absolute deadline survives timezone changes, load, import and rename',()=>{
  const previous=process.env.TZ;
  try{process.env.TZ='UTC';const at=Date.UTC(2026,8,6,23,30,37),h=harness(at);h.s.quick({kind:'alarm',minutes:60});const raw=JSON.stringify(h.s.data),exported=exportTransfer(h.s.data.plans),exact=h.s.data.plans[0].exactAt;
    process.env.TZ='Asia/Shanghai';const shown=h.s.snapshot().plans[0];assert.equal(shown.time,'08:30');h.s.save({...shown,name:'时区切换后改名'},shown.id);assert.equal(h.s.data.plans[0].exactAt,exact);assert.equal(parseStore(raw).plans[0].time,'08:30');assert.equal(parseTransfer(exported)[0].exactAt,exact);
  }finally{if(previous===undefined)delete process.env.TZ;else process.env.TZ=previous;}
});
