import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {Scheduler,defaults,localDate} from '../electron/scheduler';
import {Storage,parseStore} from '../electron/storage';
import {parseTransfer,exportTransfer,classifyImport} from '../electron/transfer';
import {normalizePreset,presetDraft} from '../src/presets';
import {copyPlan,selectPlans} from '../src/plan-utils';
const start=+new Date('2026-09-22T23:50:00');
function fixture(data=defaults()){
 let now=start,writes=0,shutdowns=0,notifies=0;const s=new Scheduler(data,()=>now,()=>{writes++;},()=>{shutdowns++;},()=>{notifies++;});
 return {s,at:(t:number)=>{now=t;s.tick();},now:(t:number)=>{now=t;},stats:()=>({writes,shutdowns,notifies}),plan:(offset:number,kind:'alarm'|'shutdown'='shutdown')=>{const d=new Date(now+offset*60000);s.save({name:'待办 '+offset,kind,repeat:'once',date:localDate(d),time:`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`,weekdays:[],enabled:true,notes:'保存未提交文件\n检查构建结果'});}};
}
test('temporary pause skips exact resume boundary and clears current reminders',()=>{const f=fixture();f.plan(3);f.plan(10);f.plan(11);f.s.demo('alarm');assert.ok(f.s.warnings.length&&f.s.alarms.length);f.s.pauseFor({minutes:10});assert.equal(f.s.warnings.length+f.s.alarms.length,0);const writes=f.stats().writes;f.at(start+5000);assert.equal(f.stats().writes,writes);f.at(start+600000);assert.equal(f.s.data.paused,false);assert.equal(f.s.data.pauseUntil,undefined);assert.equal(f.stats().shutdowns,0);assert.equal(f.s.data.plans[0].outcome,'已错过');assert.equal(f.s.data.plans[1].outcome,'已错过');assert.equal(f.s.warnings[0].name,'待办 11');});
test('pause restart preserves absolute deadline; elapsed restart and forward jumps never catch up shutdowns',()=>{for(const elapsed of [300000,900000]){const f=fixture();f.plan(6);f.s.pauseFor({minutes:10});const data=parseStore(JSON.stringify(f.s.data));let count=0;const reopened=new Scheduler(data,()=>start+elapsed,()=>{},()=>{count++;},()=>{});reopened.reconcile();assert.equal(reopened.data.paused,elapsed<600000);assert.equal(reopened.data.pauseUntil,elapsed<600000?start+600000:undefined);assert.equal(count,0);if(elapsed>600000)assert.equal(data.plans[0].outcome,'已错过');}});
test('manual pause cancels automatic resume, and early manual resume clears the deadline',()=>{const f=fixture();f.s.pauseFor({minutes:15});f.s.setPaused(true);assert.equal(f.s.data.pauseUntil,undefined);f.at(start+3600000);assert.equal(f.s.data.paused,true);f.s.pauseFor({minutes:30});f.s.setPaused(false);assert.equal(f.s.data.pauseUntil,undefined);assert.equal(f.s.data.paused,false);});
test('resume does not change per-plan enabled flags; backward time retains absolute deadline',()=>{const f=fixture();f.plan(30);f.s.toggle(f.s.data.plans[0].id);f.s.pauseFor({until:start+600000});f.at(start-600000);assert.equal(f.s.data.pauseUntil,start+600000);f.at(start+600000);assert.equal(f.s.data.plans[0].enabled,false);assert.equal(f.stats().shutdowns,0);});
test('invalid pause requests and storage-fault stopped scheduler cannot resume',()=>{const f=fixture();for(const input of [{minutes:0},{minutes:1441},{minutes:1.5},{until:start},{until:start+86400001},{minutes:5,until:start+1000},{},null])assert.throws(()=>f.s.pauseFor(input as any));f.s.pauseFor({minutes:1});f.s.stop();f.at(start+120000);assert.equal(f.s.data.paused,true);assert.throws(()=>f.s.setPaused(false),/故障/);assert.throws(()=>f.s.pauseFor({minutes:2}),/故障/);});
test('corrupt primary backup recovery removes auto-resume and keeps plans disabled',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'starsleep-pause-test-'));try{const store=new Storage(root),f=fixture();f.plan(30);f.s.pauseFor({minutes:10});store.save(f.s.data);fs.writeFileSync(store.file,'broken');const restored=store.load();assert.equal(restored.paused,true);assert.equal(restored.pauseUntil,undefined);assert.equal(restored.plans[0].enabled,false);assert.throws(()=>parseStore(JSON.stringify({...defaults(),pauseUntil:'invalid'})),/恢复时间/);assert.equal(parseStore(JSON.stringify({...defaults(),pauseUntil:start})).pauseUntil,undefined);}finally{assert.equal(path.dirname(path.resolve(root)),path.resolve(os.tmpdir()));assert.ok(path.basename(root).startsWith('starsleep-pause-test-'));fs.rmSync(root,{recursive:true,force:true});}});
test('plan notes survive storage, copies, transfer and quick/personal template application',()=>{const f=fixture();f.plan(30);const p=f.s.data.plans[0];assert.equal(parseStore(JSON.stringify(f.s.data)).plans[0].notes,p.notes);assert.equal(copyPlan(p).notes,p.notes);const transfer=parseTransfer(exportTransfer([p]));assert.equal(transfer[0].notes,p.notes);assert.equal(transfer[0].enabled,false);assert.equal(classifyImport(transfer,[p],start).duplicate,1);assert.equal(classifyImport([{...transfer[0],notes:'different'}],[p],start).accepted.length,1);assert.equal(selectPlans(f.s.snapshot().plans,'构建','all','all','next').length,1);
 const preset=normalizePreset({type:'quick',name:'检查结果',kind:'alarm',minutes:5,notes:p.notes});const draft=presetDraft(preset,start);assert.ok('minutes' in draft);if('minutes'in draft)f.s.quick(draft);assert.equal(f.s.data.plans[1].notes,p.notes);
 assert.throws(()=>f.s.save({...p,notes:'x'.repeat(501)}));assert.throws(()=>normalizePreset({...preset,notes:23}));assert.throws(()=>parseTransfer(JSON.stringify({format:'starsleep-plans',version:1,plans:[{...p,notes:[]}]})));
});
test('notes follow warnings and snoozed alarms, and clearing a note removes it',()=>{const f=fixture();f.plan(3,'alarm');f.now(start+179000);f.s.last=start+179000;f.at(start+180000);assert.equal(f.s.alarms[0].notes,'保存未提交文件\n检查构建结果');f.s.action([f.s.alarms[0].key],'snooze',10);const agenda=f.s.agenda();assert.equal(agenda.days.flatMap(d=>d.occurrences)[0].notes,'保存未提交文件\n检查构建结果');const p=f.s.data.plans[0];f.s.save({...p,date:localDate(new Date(start+86400000)),notes:''},p.id);assert.equal(f.s.data.plans[0].notes,undefined);});
