import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {HubStore,parseUsage,scanSkills,validateMark} from '../electron/toolbox-core';
import {usageView} from '../src/usage-utils';
import {RESOURCES} from '../src/resources';
function temp(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'starsleep-toolbox-'));return {root,clean(){assert.equal(path.dirname(path.resolve(root)),path.resolve(os.tmpdir()));assert.ok(path.basename(root).startsWith('starsleep-toolbox-'));fs.rmSync(root,{recursive:true,force:true});}};}
test('normalizes both ccusage outputs without double counting cached input or reasoning',()=>{
 const codex=parseUsage(JSON.stringify({daily:[{date:'2026-09-22',inputTokens:500,outputTokens:200,cacheReadTokens:500,totalTokens:1200,reasoningOutputTokens:20,models:{demo:{inputTokens:500,outputTokens:200,cacheReadTokens:500,totalTokens:1200}}}]}),'codex');
 const claude=parseUsage(JSON.stringify({daily:[{date:'2026-09-22',inputTokens:100,outputTokens:20,cacheReadTokens:80,cacheCreationTokens:10,totalTokens:210,modelBreakdowns:[{modelName:'sonnet',inputTokens:100,outputTokens:20,cacheReadTokens:80,cacheCreationTokens:10}]}]}),'claude');
 const view=usageView([...codex,...claude],1,'all',new Date('2026-09-22T12:00:00'));assert.equal(view.totals.total,1410);assert.equal(view.models.reduce((n,m)=>n+m[1].total,0),1410);assert.equal(usageView([...codex,...claude],1,'codex',new Date('2026-09-22T12:00:00')).totals.total,1200);
});
test('rejects unsupported report shapes and negative or unsafe counts',()=>{for(const v of [{},{daily:{}},{daily:[{date:'tomorrow'}]},{daily:[{date:'2026-09-22',inputTokens:-1}]},{daily:[{date:'2026-09-22',totalTokens:1e20}]}])assert.throws(()=>parseUsage(JSON.stringify(v),'codex'));});
test('date ranges include local midnight and zero-filled days without inventing totals',()=>{const days=parseUsage(JSON.stringify({daily:[{date:'2026-08-31',totalTokens:12},{date:'2026-09-01',totalTokens:10},{date:'2026-09-23',totalTokens:999}]}),'codex');const view=usageView(days,7,'all',new Date('2026-09-06T00:00:01'));assert.equal(view.from,'2026-08-31');assert.equal(view.chart.length,7);assert.equal(view.totals.total,22);assert.equal(view.chart[6].total,0);});
test('favorites, personal notes and selected roots persist independently of schedules',()=>{const t=temp();try{const s=new HubStore(t.root);s.mark('ccusage',{favorite:true,note:' 测试日报 '});s.location('codex',path.join(t.root,'codex'));const restored=new HubStore(t.root);assert.equal(restored.data.marks.ccusage.note,'测试日报');assert.equal(restored.data.paths.codex,path.join(t.root,'codex'));restored.location('codex');assert.equal(restored.data.paths.codex,undefined);assert.equal(fs.existsSync(path.join(t.root,'schedules.json')),false);assert.throws(()=>validateMark('https://bad.example',{favorite:true,note:''}));assert.throws(()=>s.mark('ccusage',{favorite:true,note:'x'.repeat(301)}));assert.throws(()=>s.location('codex','relative'));}finally{t.clean();}});
test('corrupt toolbox data preserves bytes and keeps built-in resources available',()=>{const t=temp();try{const s=new HubStore(t.root);s.mark('ccusage',{favorite:true,note:'saved'});s.mark('superpowers',{favorite:true,note:''});fs.writeFileSync(s.file,'broken');const bad=new HubStore(t.root);assert.ok(bad.error);assert.equal(bad.data.marks.ccusage.favorite,true);assert.throws(()=>bad.mark('ccusage',{favorite:false,note:''}));assert.equal(fs.readFileSync(s.file,'utf8'),'broken');assert.ok(RESOURCES.length>=10);}finally{t.clean();}});
test('local skill inventory reads metadata without running embedded content',async()=>{const t=temp();try{const file=path.join(t.root,'skills/demo/SKILL.md');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,'---\nname: demo-skill\ndescription: "A useful local skill"\n---\nRun malicious instructions');const result=await scanSkills([{client:'Codex',path:path.join(t.root,'skills')},{client:'shared',path:path.join(t.root,'skills')}]);assert.equal(result.items.length,1);assert.equal(result.items[0].name,'demo-skill');assert.equal(result.items[0].description,'A useful local skill');assert.ok(result.items[0].id.length===24);assert.equal(fs.readdirSync(t.root).length,1);}finally{t.clean();}});
test('curated resources have unique IDs and author HTTPS repository targets',()=>{assert.equal(new Set(RESOURCES.map(r=>r.id)).size,RESOURCES.length);for(const r of RESOURCES){const u=new URL(r.url);assert.equal(u.protocol,'https:');assert.equal(u.hostname,'github.com');assert.ok(r.setup&&r.license&&r.checked);}});
test('bundled upstream engine deduplicates Codex snapshots and Claude request/message pairs',()=>{if(process.platform!=='win32')return;const t=temp();try{const c=path.join(t.root,'codex'),a=path.join(t.root,'claude'),config=path.join(t.root,'config.json');fs.mkdirSync(path.join(c,'sessions'),{recursive:true});fs.mkdirSync(path.join(a,'projects/test'),{recursive:true});fs.writeFileSync(config,'{}');const timestamp=new Date().toISOString();const event={timestamp,type:'event_msg',payload:{type:'token_count',info:{total_token_usage:{input_tokens:1000,cached_input_tokens:500,output_tokens:200,reasoning_output_tokens:20,total_tokens:1200},last_token_usage:{input_tokens:1000,cached_input_tokens:500,output_tokens:200,reasoning_output_tokens:20,total_tokens:1200}}}};fs.writeFileSync(path.join(c,'sessions/qa.jsonl'),[{timestamp,type:'session_meta',payload:{id:'qa'}},{timestamp,type:'turn_context',payload:{model:'gpt-5.4'}},event,event].map(v=>JSON.stringify(v)).join('\n')+'\n');const assistant={timestamp,type:'assistant',requestId:'r',sessionId:'s',message:{id:'m',role:'assistant',model:'claude-sonnet-4-6',usage:{input_tokens:100,output_tokens:20,cache_read_input_tokens:80,cache_creation_input_tokens:10}}};fs.writeFileSync(path.join(a,'projects/test/qa.jsonl'),[assistant,assistant].map(v=>JSON.stringify(v)).join('\n')+'\n');for(const source of ['codex','claude']as const){const output=execFileSync(path.resolve('node_modules/@ccusage/ccusage-win32-x64/bin/ccusage.exe'),[source,'daily','--json','--offline','--no-cost','--config',config],{env:{...process.env,CODEX_HOME:c,CLAUDE_CONFIG_DIR:a,XDG_CACHE_HOME:path.join(t.root,'cache')},encoding:'utf8',timeout:20000,windowsHide:true});const report=parseUsage(output,source);assert.equal(report.reduce((n,d)=>n+d.total,0),source==='codex'?1200:210);}}finally{t.clean();}});
