import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createHash,randomUUID} from 'node:crypto';
import {Workshop,type ThemeFetch} from '../electron/workshop-core';
import {themeDownloader} from '../electron/workshop-network';
import {ThemeLibrary,parseThemeText} from '../electron/themes';
import {SkillMarket} from '../electron/market-core';
import {ScenePolicy} from '../src/scene-policy';
import {ExperienceStore} from '../electron/experience';
import {COMMUNITY_THEMES} from '../src/community-catalog';
import type {CommunityTheme} from '../src/workshop-types';
const raw=Buffer.from(JSON.stringify({name:'Test',bgMain:'#101010',textPrimary:'#ffffff'}));
const digest=(b:Buffer)=>createHash('sha256').update(b).digest('hex');
test('current Claude community schema accepts mode and material booleans but rejects code',()=>{const theme={name:'Arizona',bgMain:'#D4F1EC',textPrimary:'#1A3A35',mode:'light',glassEffect:false,glowEffect:false};assert.equal(parseThemeText(JSON.stringify(theme)).format,'claude-json');assert.throws(()=>parseThemeText(JSON.stringify({...theme,glassEffect:'execute()'})));assert.throws(()=>parseThemeText(JSON.stringify({...theme,script:'alert(1)'})));});
const resource:CommunityTheme={id:'test',name:'Test',author:'Author',client:'claude',style:'dark',format:'claude-json',version:'a'.repeat(40),source:'https://github.com/sample/theme',license:'MIT',loader:'Theme Mod',checked:'2026-09-22',colors:['#101010','#ffffff'],description:'Fixture',download:{url:'https://raw.githubusercontent.com/sample/theme/'+'a'.repeat(40)+'/theme.json',filename:'theme.json',sha256:digest(raw)}};
function fixture(fetcher:ThemeFetch=async()=>raw){const root=fs.mkdtempSync(path.join(os.tmpdir(),'starsleep-v18-')),library=new ThemeLibrary(root);let pushes=0;const workshop=new Workshop(root,[resource],library,fetcher,()=>pushes++);return {root,library,workshop,pushes:()=>pushes};}
test('workshop downloads validated bytes without changing any client and persists provenance',async()=>{const f=fixture();await f.workshop.download('test');assert.equal(f.library.list().length,1);assert.equal(f.workshop.state.tasks[0].status,'done');const id=f.library.list()[0].id;assert.equal(f.workshop.state.themes[id].source,resource.source);assert.equal(fs.existsSync(path.join(f.root,'test-clients')),false);assert.throws(()=>f.workshop.confirm(id),/先写入/);f.workshop.written(id,'claude');assert.ok(f.workshop.confirm(id).themes[id].confirmedAt);f.workshop.restored('claude');assert.equal(f.workshop.state.themes[id].writtenAt,undefined);});
test('workshop cancels an in-flight download without creating a theme and permits retry',async()=>{let first=true;const f=fixture(async(_,signal,progress)=>{if(!first)return raw;first=false;progress(20,300);return new Promise((_,reject)=>signal.addEventListener('abort',()=>reject(Error('aborted')),{once:true}));});const pending=f.workshop.download('test');assert.equal(f.workshop.state.tasks[0].received,20);f.workshop.cancel(f.workshop.state.tasks[0].id);await pending;assert.equal(f.library.list().length,0);assert.equal(f.workshop.state.tasks[0].status,'cancelled');await f.workshop.download('test');assert.equal(f.library.list().length,1);});
test('failed checksum, oversized bytes and invalid format never enter theme library',async()=>{for(const bytes of [Buffer.from('bad'),Buffer.alloc(32*1024*1024+1)]){const f=fixture(async()=>bytes);await f.workshop.download('test');assert.equal(f.library.list().length,0);assert.equal(f.workshop.state.tasks[0].status,'failed');}const f=fixture(async()=>Buffer.from('not JSON'));f.workshop.catalog[0]={...resource,download:{...resource.download!,sha256:digest(Buffer.from('not JSON'))}};await f.workshop.download('test');assert.equal(f.library.list().length,0);});
test('duplicate resources and duplicate contents cannot add a second theme',async()=>{const f=fixture();await f.workshop.download('test');await assert.rejects(()=>f.workshop.download('test'),/已下载/);f.workshop.catalog.push({...resource,id:'same'});await f.workshop.download('same');assert.equal(f.library.list().length,1);assert.equal(f.workshop.state.tasks[0].status,'failed');});
test('workshop preserves corrupted records and blocks writes independently of schedules',()=>{const f=fixture();fs.writeFileSync(path.join(f.root,'workshop.json'),'broken');const w=new Workshop(f.root,[resource],f.library,async()=>raw,()=>{});assert.ok(w.state.error);assert.throws(()=>w.favorite('test',true));assert.equal(fs.readFileSync(path.join(f.root,'workshop.json'),'utf8'),'broken');});
test('workshop interrupted downloads recover as retryable and favorites survive restart',()=>{const f=fixture();f.workshop.favorite('test',true);f.workshop.state.tasks.push({id:'pending',resourceId:'test',status:'downloading',received:4,at:1});f.workshop.favorite('test',true);const w=new Workshop(f.root,[resource],f.library,async()=>raw,()=>{});assert.equal(w.state.tasks[0].status,'failed');assert.deepEqual(w.state.favorites,['test']);});
test('theme downloader bounds stream sizes, refuses arbitrary URLs and reports progress',async()=>{const fetcher=themeDownloader(async()=>new Response(raw,{headers:{'Content-Length':String(raw.length)}}));let size=0;assert.deepEqual(await fetcher(resource.download!.url,new AbortController().signal,n=>size=n),raw);assert.equal(size,raw.length);await assert.rejects(()=>fetcher('https://evil.example/theme',new AbortController().signal,()=>{}));const tooLarge=themeDownloader(async()=>new Response('x',{headers:{'Content-Length':'999999999'}}));await assert.rejects(()=>tooLarge(resource.download!.url,new AbortController().signal,()=>{}),/32 MB/);const chunks=themeDownloader(async()=>new Response(new ReadableStream({start(c){c.enqueue(new Uint8Array(32*1024*1024));c.enqueue(new Uint8Array(1));c.close();}})));await assert.rejects(()=>chunks(resource.download!.url,new AbortController().signal,()=>{}),/32 MB/);});
test('curated downloadable themes use pinned HTTPS author commits and ship original licenses',()=>{assert.equal(new Set(COMMUNITY_THEMES.map(t=>t.id)).size,COMMUNITY_THEMES.length);for(const r of COMMUNITY_THEMES.filter(t=>t.download)){assert.match(r.download!.url,/^https:\/\/raw\.githubusercontent\.com\/[^/]+\/[^/]+\/[a-f0-9]{40}\//);assert.match(r.download!.sha256,/^[a-f0-9]{64}$/);assert.ok(r.licenseText?.includes('Permission'));}});
test('theme style uses native mode rather than accent brightness and upgrades old library metadata',()=>{const f=fixture(),theme=JSON.parse(raw.toString());theme.mode='light';const item=f.library.import(Buffer.from(JSON.stringify(theme)),'theme.json');assert.equal(item.style,'light');const file=path.join(f.root,'themes/library.json'),index=JSON.parse(fs.readFileSync(file,'utf8'));delete index.items[0].style;fs.writeFileSync(file,JSON.stringify(index));assert.equal(new ThemeLibrary(f.root).list()[0].style,'light');});
function interrupted(kind:'install'|'remove'|'restore',afterMove=false,changed=false){
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'starsleep-journal-')),targets={codex:path.join(root,'user/skills'),claude:path.join(root,'claude/skills'),deepseek:path.join(root,'deepseek/skills')},id=randomUUID(),destination=path.join(targets.codex,'sample'),record={id,name:'sample',repo:'sample/repo',commit:'a'.repeat(40),skillPath:'',target:'codex',destination,installedAt:1,status:kind==='restore'?'removed':'installed',hashes:{'SKILL.md':digest(raw)}};
 const stage=path.join(root,'user/.starsleep-staging',id),disabled=path.join(root,'user/.starsleep-disabled',id),from=kind==='install'?stage:kind==='remove'?destination:disabled,to=kind==='remove'?disabled:destination;
 fs.mkdirSync(afterMove?to:from,{recursive:true});fs.writeFileSync(path.join(afterMove?to:from,'SKILL.md'),changed?'user edits':raw);fs.writeFileSync(path.join(root,'skill-installs.json'),JSON.stringify({version:1,installs:kind==='install'?[]:[record]}));fs.writeFileSync(path.join(root,'skill-operation.json'),JSON.stringify({version:1,kind,phase:'prepared',record}));
 return {root,targets,from,to,record,open:()=>new SkillMarket(root,targets,async()=>Buffer.alloc(0))};
}
test('install/remove/restore recover both sides of a process interruption',()=>{for(const kind of ['install','remove','restore']as const)for(const afterMove of [false,true]){const f=interrupted(kind,afterMove),m=f.open();assert.equal(m.error,'');assert.equal(m.list()[0].status,kind==='remove'?'removed':'installed');assert.ok(fs.existsSync(f.to));assert.equal(fs.existsSync(f.from),false);assert.equal(JSON.parse(fs.readFileSync(path.join(f.root,'skill-operation.json'),'utf8')).phase,'complete');assert.equal(f.open().list().length,1);}});
test('recovery never overwrites modified files or conflicting destinations',()=>{for(const afterMove of [false,true]){const f=interrupted('install',afterMove,true),m=f.open();assert.ok(m.error);assert.equal(fs.readFileSync(path.join(afterMove?f.to:f.from,'SKILL.md'),'utf8'),'user edits');}const f=interrupted('restore');fs.mkdirSync(f.to,{recursive:true});fs.writeFileSync(path.join(f.to,'mine'),'keep');assert.ok(f.open().error);assert.equal(fs.readFileSync(path.join(f.to,'mine'),'utf8'),'keep');});
test('client file inspection reports user edits without reading unrelated directories',()=>{const f=interrupted('install'),m=f.open();assert.equal(m.inspect()[0].status,'ok');fs.writeFileSync(path.join(f.to,'SKILL.md'),'modified');assert.equal(m.inspect()[0].status,'attention');});
test('scene policy idles at 15 seconds, progressively degrades, and static/low preferences are explicit',()=>{const p=new ScenePolicy();for(let n=100;n<40000;n+=100)p.sample(n,n);assert.equal(p.tier,4);const idle=new ScenePolicy();idle.sample(15001,0);assert.equal(idle.idle,true);idle.sample(15002,15002);assert.equal(idle.idle,false);assert.equal(new ScenePolicy('low').tier,2);assert.equal(new ScenePolicy('static').tier,4);});
test('experience accepts legacy preferences and validates panel/zoom limits without changing plan data',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'starsleep-experience-')),store=new ExperienceStore(root);store.prefs({interaction:true,miniPinned:true});assert.equal(store.data.prefs.sceneMode,'immersive');store.prefs({...store.data.prefs,panels:{workshop:{width:900,height:500}},cameraZoom:1.2});assert.equal(new ExperienceStore(root).data.prefs.panels?.workshop?.width,900);assert.throws(()=>store.prefs({...store.data.prefs,cameraZoom:99}));assert.throws(()=>store.prefs({...store.data.prefs,panels:{agent:{width:1,height:1}}}));});
