import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {WallpaperLibrary,validateWallpaper,MAX_WALLPAPER_BYTES} from '../electron/wallpapers';
const image=Buffer.from([137,80,78,71,13,10,26,10,1]);
const decode=(bytes:Buffer)=>({width:1672,height:941,thumbnail:'data:image/png;base64,fixture',normalized:bytes});
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'starsleep-wallpapers-')),assets=path.join(root,'assets');fs.mkdirSync(assets);for(const name of ['tidal-glass','cloud-fjord'])fs.writeFileSync(path.join(assets,name+'.png'),image);return {root,assets,lib:new WallpaperLibrary(root,assets,decode),close:()=>{assert.equal(path.dirname(root),os.tmpdir());assert.match(path.basename(root),/^starsleep-wallpapers-/);fs.rmSync(root,{recursive:true,force:true});}};}
test('image import rejects executable formats, oversize and undecodable images',()=>{assert.throws(()=>validateWallpaper(Buffer.from('<svg/>'),decode),/PNG/);assert.throws(()=>validateWallpaper(Buffer.alloc(MAX_WALLPAPER_BYTES+1),decode),/10 MB/);assert.throws(()=>validateWallpaper(image,()=>{throw new Error('decode failed');}),/decode failed/);for(const [width,height]of [[1,1],[9000,800],[8000,8000]])assert.throws(()=>validateWallpaper(image,b=>({...decode(b),width,height})),/尺寸/);});
test('personal backgrounds survive restart, duplicates do not create extra entries',()=>{const f=fixture();try{const id=f.lib.import(image,'假期.png');assert.equal(f.lib.item(id).name,'假期');assert.throws(()=>f.lib.import(image,'重复.png'),/已在/);const reopened=new WallpaperLibrary(f.root,f.assets,decode);assert.equal(reopened.list().length,3);assert.deepEqual(reopened.raw(id),image);assert.equal(reopened.item(id).builtin,false);reopened.remove(id);assert.equal(new WallpaperLibrary(f.root,f.assets,decode).list().length,2);assert.throws(()=>reopened.raw(id),/不存在/);}finally{f.close();}});
test('renderer identifiers cannot select arbitrary files or remove builtins',()=>{const f=fixture();try{for(const value of ['../secrets','C:/private.json',null,{}])assert.throws(()=>f.lib.raw(value),/不存在/);assert.throws(()=>f.lib.remove('tidal-glass'),/内置/);assert.equal(f.lib.list().length,2);}finally{f.close();}});
test('damaged library preserves original bytes and keeps builtins available',()=>{const f=fixture();try{const file=path.join(f.root,'wallpapers/library.json');fs.mkdirSync(path.dirname(file));fs.writeFileSync(file,'broken');const reopened=new WallpaperLibrary(f.root,f.assets,decode);assert.match(reopened.error,/保留/);assert.equal(reopened.list().length,2);assert.throws(()=>reopened.import(image,'x.png'),/保留/);assert.equal(fs.readFileSync(file,'utf8'),'broken');}finally{f.close();}});
test('tampered persisted paths are refused before reading outside the library',()=>{const f=fixture();try{const file=path.join(f.root,'wallpapers/library.json');fs.mkdirSync(path.dirname(file));fs.writeFileSync(file,JSON.stringify({version:1,items:[{id:'00000000-0000-0000-0000-000000000000',file:'../../secret.jpg',builtin:false,name:'bad'}]}));const reopened=new WallpaperLibrary(f.root,f.assets,decode);assert.match(reopened.error,/读取失败/);assert.equal(reopened.list().length,2);}finally{f.close();}});
test('failed index save rolls back the new image',()=>{const f=fixture();try{fs.mkdirSync(path.join(f.root,'wallpapers/library.json'),{recursive:true});assert.throws(()=>f.lib.import(image,'x.png'));assert.deepEqual(fs.readdirSync(path.join(f.root,'wallpapers')),['library.json']);assert.equal(f.lib.list().length,2);}finally{f.close();}});
