import { contextBridge, ipcRenderer,webUtils } from 'electron';
import type { Api } from '../src/shared';
const api:Api={
  themeCreate:input=>ipcRenderer.invoke('theme-create',input),
  workshopCatalog:()=>ipcRenderer.invoke('workshop-catalog'),
  workshopState:()=>ipcRenderer.invoke('workshop-state'),
  workshopChanged:callback=>{const fn=(_:unknown,state:any)=>callback(state);ipcRenderer.on('workshop',fn);return()=>ipcRenderer.removeListener('workshop',fn);},
  workshopDownload:id=>ipcRenderer.invoke('workshop-download',id),
  workshopCancel:id=>ipcRenderer.invoke('workshop-cancel',id),
  workshopFavorite:(id,value)=>ipcRenderer.invoke('workshop-favorite',id,value),
  workshopOpen:id=>ipcRenderer.invoke('workshop-open',id),
  workshopConfirm:id=>ipcRenderer.invoke('workshop-confirm',id),
  themeDrop:file=>ipcRenderer.invoke('theme-drop',webUtils.getPathForFile(file)),
  clientHealth:()=>ipcRenderer.invoke('client-health'),
  exportHealth:()=>ipcRenderer.invoke('health-export'),
  githubSearch:(q,s,p)=>ipcRenderer.invoke('github-search',q,s,p),
  githubSkills:repo=>ipcRenderer.invoke('github-skills',repo),
  skillAudit:(repo,commit,p)=>ipcRenderer.invoke('skill-audit',repo,commit,p),
  skillAuditFile:(token,p)=>ipcRenderer.invoke('skill-audit-file',token,p),
  skillInstall:(token,target)=>ipcRenderer.invoke('skill-install',token,target),
  skillUninstall:id=>ipcRenderer.invoke('skill-uninstall',id),
  skillRestore:id=>ipcRenderer.invoke('skill-restore',id),
  skillZip:token=>ipcRenderer.invoke('skill-zip',token),
  marketState:()=>ipcRenderer.invoke('market-state'),
  marketTarget:target=>ipcRenderer.invoke('market-target',target),
  marketOpen:repo=>ipcRenderer.invoke('market-open',repo),
  marketReveal:id=>ipcRenderer.invoke('market-reveal',id),
  toolboxState:()=>ipcRenderer.invoke('toolbox-state'),
  usageRead:(force?:boolean)=>ipcRenderer.invoke('usage-read',force),
  usageSelect:source=>ipcRenderer.invoke('usage-select',source),
  usageReset:source=>ipcRenderer.invoke('usage-reset',source),
  usageExport:(range,source)=>ipcRenderer.invoke('usage-export',range,source),
  resourceMark:(id,mark)=>ipcRenderer.invoke('resource-mark',id,mark),
  resourceOpen:id=>ipcRenderer.invoke('resource-open',id),
  resourceCopy:id=>ipcRenderer.invoke('resource-copy',id),
  localSkills:()=>ipcRenderer.invoke('local-skills'),
  skillReveal:id=>ipcRenderer.invoke('skill-reveal',id),
  wallpaperList:()=>ipcRenderer.invoke('wallpaper-list'),
  wallpaperImport:()=>ipcRenderer.invoke('wallpaper-import'),
  wallpaperPreview:id=>ipcRenderer.invoke('wallpaper-preview',id),
  wallpaperExport:id=>ipcRenderer.invoke('wallpaper-export',id),
  wallpaperRemove:id=>ipcRenderer.invoke('wallpaper-remove',id),
  wallpaperDshApply:id=>ipcRenderer.invoke('wallpaper-dsh-apply',id),
  themeDshSelect:()=>ipcRenderer.invoke('theme-dsh-select'),
  themeDshApply:id=>ipcRenderer.invoke('theme-dsh-apply',id),
  themeDshRestore:()=>ipcRenderer.invoke('theme-dsh-restore'),
  integrations:()=>ipcRenderer.invoke('integrations'),
  integrationChanged:callback=>{const fn=(_:unknown,value:any)=>callback(value);ipcRenderer.on('integrations',fn);return()=>ipcRenderer.removeListener('integrations',fn);},
  agentArm:ids=>ipcRenderer.invoke('agent-arm',ids),
  agentDisarm:()=>ipcRenderer.invoke('agent-disarm'),
  agentConnect:(provider,install,real)=>ipcRenderer.invoke('agent-connect',provider,install,real),
  agentExportDsh:()=>ipcRenderer.invoke('agent-export-dsh'),
  agentDemo:()=>ipcRenderer.invoke('agent-demo'),
  themeImport:()=>ipcRenderer.invoke('theme-import'),
  themeImportText:(text,name)=>ipcRenderer.invoke('theme-import-text',text,name),
  themeCopy:id=>ipcRenderer.invoke('theme-copy',id),
  themeExport:id=>ipcRenderer.invoke('theme-export',id),
  themeRemove:id=>ipcRenderer.invoke('theme-remove',id),
  themeClaudeApply:id=>ipcRenderer.invoke('theme-claude-apply',id),
  themeClaudeRestore:()=>ipcRenderer.invoke('theme-claude-restore'),
  themeClients:()=>ipcRenderer.invoke('theme-clients'),
  themeCodexApply:id=>ipcRenderer.invoke('theme-codex-apply',id),
  themeCodexRestore:()=>ipcRenderer.invoke('theme-codex-restore'),
  integrationLink:target=>ipcRenderer.invoke('integration-link',target),
  experience:()=>ipcRenderer.invoke('experience'),
  savePreset:(value,id)=>ipcRenderer.invoke('preset-save',value,id),
  removePreset:id=>ipcRenderer.invoke('preset-remove',id),
  experiencePrefs:value=>ipcRenderer.invoke('experience-prefs',value),
  setMode:mode=>ipcRenderer.invoke('window-mode',mode),
  panelOpen:open=>ipcRenderer.send('panel-open',open),
  experienceChanged:callback=>{const fn=(_:unknown,value:any)=>callback(value);ipcRenderer.on('experience',fn);return()=>ipcRenderer.removeListener('experience',fn);},
  miniRequest:callback=>{const fn=()=>callback();ipcRenderer.on('open-mini',fn);return()=>ipcRenderer.removeListener('open-mini',fn);},
  agenda:()=>ipcRenderer.invoke('agenda'),
  agendaWatch:watch=>ipcRenderer.send('agenda-watch',watch),
  agendaChanged:callback=>{const fn=(_:unknown,value:any)=>callback(value);ipcRenderer.on('agenda',fn);return()=>ipcRenderer.removeListener('agenda',fn);},
  snapshot:()=>ipcRenderer.invoke('snapshot'),
  save:(input,id)=>ipcRenderer.invoke('save',input,id),
  remove:id=>ipcRenderer.invoke('remove',id),
  toggle:id=>ipcRenderer.invoke('toggle',id),
  batch:(ids,action)=>ipcRenderer.invoke('batch',ids,action),
  skip:(id,at)=>ipcRenderer.invoke('skip',id,at),
  act:(keys,action,minutes)=>ipcRenderer.invoke('act',keys,action,minutes),
  settings:value=>ipcRenderer.invoke('settings',value),
  demo:kind=>ipcRenderer.invoke('demo',kind),
  quick:input=>ipcRenderer.invoke('quick',input),
  pause:paused=>ipcRenderer.invoke('pause',paused),
  pauseFor:input=>ipcRenderer.invoke('pause-for',input),
  exportPlans:()=>ipcRenderer.invoke('export-plans'),
  exportLogs:filter=>ipcRenderer.invoke('export-logs',filter),
  previewImport:()=>ipcRenderer.invoke('preview-import'),
  commitImport:token=>ipcRenderer.invoke('commit-import',token),
  cancelImport:()=>ipcRenderer.invoke('cancel-import'),
  openLink:target=>ipcRenderer.invoke('open-link',target),
  window:action=>ipcRenderer.send('window',action),
  subscribe:callback=>{const fn=(_:unknown,state:any)=>callback(state);ipcRenderer.on('state',fn);return()=>ipcRenderer.removeListener('state',fn);},
  clock:callback=>{const fn=(_:unknown,now:number)=>callback(now);ipcRenderer.on('clock',fn);return()=>ipcRenderer.removeListener('clock',fn);},
  runtime:callback=>{const fn=(_:unknown,state:any)=>callback(state);ipcRenderer.on('runtime',fn);return()=>ipcRenderer.removeListener('runtime',fn);},
  quickRequest:callback=>{const fn=()=>callback();ipcRenderer.on('open-quick',fn);return()=>ipcRenderer.removeListener('open-quick',fn);},
  visibility:callback=>{const fn=(_:unknown,visible:boolean)=>callback(visible);ipcRenderer.on('visibility',fn);return()=>ipcRenderer.removeListener('visibility',fn);}
};
contextBridge.exposeInMainWorld('starSleep',api);
