import { contextBridge, ipcRenderer } from 'electron';
import type { Api } from '../src/shared';
const api:Api={
  experience:()=>ipcRenderer.invoke('experience'),
  savePreset:(value,id)=>ipcRenderer.invoke('preset-save',value,id),
  removePreset:id=>ipcRenderer.invoke('preset-remove',id),
  experiencePrefs:value=>ipcRenderer.invoke('experience-prefs',value),
  setMode:mode=>ipcRenderer.invoke('window-mode',mode),
  panelOpen:open=>ipcRenderer.send('panel-open',open),
  experienceChanged:callback=>{const fn=(_:unknown,value:any)=>callback(value);ipcRenderer.on('experience',fn);return()=>ipcRenderer.removeListener('experience',fn);},
  miniRequest:callback=>{const fn=()=>callback();ipcRenderer.on('open-mini',fn);return()=>ipcRenderer.removeListener('open-mini',fn);},
  agenda:()=>ipcRenderer.invoke('agenda'),
  agendaWatch:watch=>ipcRenderer.send('agenda-watch',watch),
  agendaChanged:callback=>{const fn=(_:unknown,value:any)=>callback(value);ipcRenderer.on('agenda',fn);return()=>ipcRenderer.removeListener('agenda',fn);},
  snapshot:()=>ipcRenderer.invoke('snapshot'),
  save:(input,id)=>ipcRenderer.invoke('save',input,id),
  remove:id=>ipcRenderer.invoke('remove',id),
  toggle:id=>ipcRenderer.invoke('toggle',id),
  batch:(ids,action)=>ipcRenderer.invoke('batch',ids,action),
  skip:(id,at)=>ipcRenderer.invoke('skip',id,at),
  act:(keys,action,minutes)=>ipcRenderer.invoke('act',keys,action,minutes),
  settings:value=>ipcRenderer.invoke('settings',value),
  demo:kind=>ipcRenderer.invoke('demo',kind),
  quick:input=>ipcRenderer.invoke('quick',input),
  pause:paused=>ipcRenderer.invoke('pause',paused),
  exportPlans:()=>ipcRenderer.invoke('export-plans'),
  exportLogs:filter=>ipcRenderer.invoke('export-logs',filter),
  previewImport:()=>ipcRenderer.invoke('preview-import'),
  commitImport:token=>ipcRenderer.invoke('commit-import',token),
  cancelImport:()=>ipcRenderer.invoke('cancel-import'),
  openLink:target=>ipcRenderer.invoke('open-link',target),
  window:action=>ipcRenderer.send('window',action),
  subscribe:callback=>{const fn=(_:unknown,state:any)=>callback(state);ipcRenderer.on('state',fn);return()=>ipcRenderer.removeListener('state',fn);},
  clock:callback=>{const fn=(_:unknown,now:number)=>callback(now);ipcRenderer.on('clock',fn);return()=>ipcRenderer.removeListener('clock',fn);},
  runtime:callback=>{const fn=(_:unknown,state:any)=>callback(state);ipcRenderer.on('runtime',fn);return()=>ipcRenderer.removeListener('runtime',fn);},
  quickRequest:callback=>{const fn=()=>callback();ipcRenderer.on('open-quick',fn);return()=>ipcRenderer.removeListener('open-quick',fn);},
  visibility:callback=>{const fn=(_:unknown,visible:boolean)=>callback(visible);ipcRenderer.on('visibility',fn);return()=>ipcRenderer.removeListener('visibility',fn);}
};
contextBridge.exposeInMainWorld('starSleep',api);
