import {Power,Timer,ArrowUpRight,Moon,CalendarDays} from 'lucide-react';
import type {Snapshot,QuickInput} from '../shared';
import {useClock} from '../clock';
import {fullTime} from '../plan-utils';
export function Countdown({at,paused=false}:{at:number|null;paused?:boolean}){const now=useClock(),s=at?Math.max(0,Math.ceil((at-now)/1000)):0;const days=Math.floor(s/86400);return <div className="countdown-wrap">{days>0&&!paused&&<span className="countdown-days">{days} 天</span>}<div className="countdown">{paused||!at?'-- : -- : --':[Math.floor(s/3600)%24,Math.floor(s%3600/60),s%60].map(x=>String(x).padStart(2,'0')).join(':')}</div></div>;}
export function WallClock(){const now=useClock();return <time className="wall-clock">{new Date(now).toLocaleDateString('zh-CN',{month:'short',day:'numeric',weekday:'short'})}<b>{new Date(now).toLocaleTimeString('zh-CN',{hour12:false,hour:'2-digit',minute:'2-digit'})}</b></time>;}
export function Console({state,onQuick,onEdit,onTemplate}:{state:Snapshot;onQuick:(q:QuickInput)=>void;onEdit:(p:Snapshot['plans'][number])=>void;onTemplate:(id:'workday'|'daily')=>void}){
 const next=state.plans.filter(p=>p.kind==='shutdown'&&p.nextAt!==null).sort((a,b)=>a.nextAt!-b.nextAt!)[0];
 return <section className="console-panel" aria-label="关机控制台"><div className="console-heading"><h1>今晚，按时休息。</h1><p>让工作有个终点，也给自己留点时间。</p></div><div className={`orbital ${next?'armed':''}`}>
  <svg className="orbit-art" viewBox="0 0 360 360" aria-hidden="true"><circle cx="180" cy="180" r="172" className="orbit-outline"/><circle cx="180" cy="180" r="145" className="orbit-outline"/>{Array.from({length:60},(_,i)=><line key={i} x1="180" y1={i%5===0?13:19} x2="180" y2="25" transform={`rotate(${i*6} 180 180)`} className={i%5===0?'tick-major':'tick'}/>)}<circle cx="180" cy="180" r="145" className="arc-light" strokeDasharray="380 532"/><g className="orbit-satellite"><circle cx="180" cy="8" r="3"/></g></svg>
  <div className="dial"><Power size={25} strokeWidth={1.3}/><span>{state.storageError?'自动执行已停止':state.paused?'全部计划已暂停':'距离下次关机'}</span><Countdown at={next?.nextAt??null} paused={state.paused||!!state.storageError}/><small>{next?'小时 : 分钟 : 秒':'尚未安排关机'}</small></div>
 </div><button className="next-event" disabled={!next} onClick={()=>next&&onEdit(next)}><CalendarDays size={20}/><div><span>{next?(state.paused?'暂停中 · 原定执行':'下次关机时间'):'下一次休息，由你决定'}</span><strong>{next?fullTime(next.nextAt!):'新建计划或开始快捷计时'}</strong>{next&&<p>{next.name}</p>}</div>{next&&<ArrowUpRight size={18}/>}</button>
 <div className="quick-section"><div className="section-title"><h2><Timer size={17}/> 再工作一会儿</h2><span>确认后开始</span></div><div className="quick-launch">{[[30,'30 分钟'],[60,'1 小时'],[120,'2 小时'],[240,'4 小时']].map(([n,label])=><button className="secondary" key={n} disabled={!!state.storageError} onClick={()=>onQuick({kind:'shutdown',minutes:Number(n)})}>{label}</button>)}</div></div>
 <details className="templates"><summary><Moon size={16}/> 常用模板</summary><div><button onClick={()=>onTemplate('workday')}>工作日 23:30 关机</button><button onClick={()=>onTemplate('daily')}>每天 21:00 提醒</button><button onClick={()=>onQuick({kind:'alarm',minutes:30})}>30 分钟后提醒</button><button onClick={()=>onQuick({kind:'shutdown',minutes:120})}>2 小时后关机</button></div></details></section>;
}
