import {useEffect,useState} from 'react';
import {Cable,Check,Download,FileUp,Palette,Play,Power,Trash2,Clipboard,ExternalLink,Square,ArrowLeft} from 'lucide-react';
import type {IntegrationSnapshot,ThemeItem} from '../integration-types';
import {Modal} from './UI';
import {Countdown} from './Console';
import {Wallpapers} from './Wallpapers';
import type {WorkshopState} from '../workshop-types';

const empty:IntegrationSnapshot={themes:[],installed:{codex:false,claude:false},night:{sessions:[],armed:false,selected:[],message:'正在读取接入状态…',settleAt:null,deadline:null,bridgeReady:false}};
const providerName={codex:'Codex',claude:'Claude Code 桌面',deepseek:'DeepSeek Harness'};
const statuses={running:'运行中',waiting:'等待处理',completed:'已报告完成',failed:'失败',disconnected:'已断开'};
const formats={'codex-native':'Codex 原生主题','dsh-appearance':'DSH UI Appearance 配色','dsh-dreamskin':'DeepSeek Dream Skin 主题','claude-json':'Claude Theme Mod','dreamskin-zip':'Codex Dream Skin ZIP','custom-css':'自定义 CSS · 需匹配加载器'};
const targets={'codex-native':'codex','dreamskin-zip':'codex','claude-json':'claude','dsh-appearance':'deepseek','dsh-dreamskin':'deepseek','custom-css':'css'};
export function IntegrationsPanel({safe,paused,onBack,section,active=true}:{safe:boolean;paused:boolean;onBack:()=>void;section?:'agent'|'theme';active?:boolean}){
  const api=window.starSleep!;
  const [state,setState]=useState(empty),[tab,setTab]=useState<'agent'|'theme'|'wallpaper'>(section??'agent'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[selected,setSelected]=useState<string[]>([]),[themeId,setThemeId]=useState(''),[paste,setPaste]=useState(false),[raw,setRaw]=useState(''),[name,setName]=useState('我的主题'),[remove,setRemove]=useState<ThemeItem|null>(null),[confirm,setConfirm]=useState(false);
  const [guide,setGuide]=useState(false);
  const [filter,setFilter]=useState('all'),[styleFilter,setStyleFilter]=useState('all'),[formatFilter,setFormatFilter]=useState('all'),[readyFilter,setReadyFilter]=useState('all');
  const [workshop,setWorkshop]=useState<WorkshopState>({favorites:[],tasks:[],themes:{}});
  useEffect(()=>{void api.workshopState().then(setWorkshop).catch(()=>{});return api.workshopChanged(setWorkshop);},[]);
  useEffect(()=>{if(active&&section==='theme')void api.themeClients().then(setState).catch(e=>setMessage(String(e)));},[active,section]);
  const canApply=(t:ThemeItem)=>{const target=targets[t.format];return target!=='css'&&['codex-native','claude-json','dsh-dreamskin'].includes(t.format)&&!!state.clients?.[target as 'codex'|'claude'|'deepseek']?.ready;};
  const light=(t:ThemeItem)=>{if(t.style)return t.style==='light';const c=t.colors[0]??'#000000';const h=c.replace('#','');return h.length===6&&(parseInt(h.slice(0,2),16)*.2126+parseInt(h.slice(2,4),16)*.7152+parseInt(h.slice(4,6),16)*.0722)>145;};
  const filtered=state.themes.filter(t=>(filter==='all'||targets[t.format]===filter)&&(styleFilter==='all'||(light(t)?'light':'dark')===styleFilter)&&(formatFilter==='all'||t.format===formatFilter)&&(readyFilter==='all'||(readyFilter==='ready'?canApply(t):!canApply(t))));
  useEffect(()=>{let live=true;const off=api.integrationChanged(s=>{if(live)setState(s);});void api.integrations().then(s=>{if(live)setState(s);}).catch(e=>setMessage(String(e)));return()=>{live=false;off();};},[]);
  useEffect(()=>{api.panelOpen(active&&(paste||!!remove||confirm||busy||guide));return()=>api.panelOpen(false);},[paste,remove,confirm,busy,guide,active]);
  async function run(fn:()=>Promise<unknown>,done?:string){if(busy)return;setBusy(true);setMessage('');try{const result=await fn();if(result&&typeof result==='object'&&'night' in result)setState(result as IntegrationSnapshot);if(typeof result==='string')setMessage(result);else if(done&&result!==false)setMessage(done);return true;}catch(e){setMessage(String(e).replace(/^Error:.*Error: /,''));return false;}finally{setBusy(false);}}
  const theme=filtered.find(t=>t.id===themeId)||filtered[0];
  const activeSelected=selected.filter(id=>state.night.sessions.some(s=>s.id===id&&s.status==='running'));
  return <main className="integration-workspace">
    <div className="integration-heading"><div><h1>{section==='agent'?'夜间联动':section==='theme'?'我的主题':'Agent 与美化'}</h1><p>完成夜间工作，让电脑和你一起休息。</p></div><button className="text-button" onClick={onBack}><ArrowLeft size={17}/> 返回计划</button></div>
    <nav className="integration-tabs" aria-label="集成功能" hidden={section==='agent'}><button hidden={section==='theme'} className={tab==='agent'?'active':''} aria-pressed={tab==='agent'} onClick={()=>setTab('agent')}><Cable size={18}/> 夜间联动</button><button className={tab==='theme'?'active':''} aria-pressed={tab==='theme'} onClick={()=>{setTab('theme');if(!state.clients)void run(()=>api.themeClients());}}><Palette size={18}/> 原界面美化</button><button className={tab==='wallpaper'?'active':''} aria-pressed={tab==='wallpaper'} onClick={()=>setTab('wallpaper')}>DeepSeek 背景</button></nav>
    {(message||state.error)&&<p className="integration-feedback" role="status">{message||state.error}</p>}
    {tab==='wallpaper'?<Wallpapers/>:tab==='agent'?<div className="integration-body agent-layout">
      <section className="integration-guide"><h2>连接你的 Agent</h2><p>先配置真实客户端，再完成信任并发送新任务。收到事件后，任务才会出现在右侧。{safe?'当前为安全测试：可以真实接入，但不会关机。':'监控只在星枢运行期间有效。'}</p>
        {(['codex','claude'] as const).map(provider=>{
          const configured=state.realHooks?.[provider].installed??(!safe&&state.installed[provider]);
          return <div className="connector-row" key={provider}><h3>{providerName[provider]}</h3><p>{provider==='codex'?'配置后打开 Codex 的 Hooks 设置，审核并信任星枢 hooks，再发送一条新任务。':'适用于 Code 标签的本地会话；Chat 和 Cowork 暂未接入。'}</p>
            <p className="integration-small">{configured?'配置已写入 · 客户端是否已信任尚未核实':'尚未配置真实客户端'}</p>
            {state.realHooks&&<p className="integration-small" style={{overflowWrap:'anywhere'}}>配置位置：{state.realHooks[provider].path}</p>}
            <button className="secondary" disabled={busy} aria-label={`${configured?'移除':'接入真实'} ${providerName[provider]}`} onClick={()=>void run(()=>api.agentConnect(provider,!configured,true),configured?'已移除当前星枢的真实接入配置':'已写入真实客户端配置。请在客户端审核并信任 hooks，再发送新任务；收到事件前尚未连接。')}>{configured?<Check size={16}/>:<Cable size={16}/>} {configured?'移除真实接入':`接入真实 ${providerName[provider]}${safe?'（不关机）':''}`}</button>
            {safe&&<details><summary>模拟配置测试</summary><p className="integration-small">仅写入隔离目录，不会出现在 Codex 或 Claude 中。</p><button className="text-button" disabled={busy} onClick={()=>void run(()=>api.agentConnect(provider,!state.installed[provider]),state.installed[provider]?'已移除模拟配置':'已写入隔离测试目录，真实客户端未改变。')}>{state.installed[provider]?'移除模拟配置':'仅模拟配置'}</button></details>}
          </div>;
        })}
        <div className="connector-row"><h3>DeepSeek Harness</h3><p>导出本机连接器，在对应 Web 或 Desktop profile 中安装，再开始新任务。</p><button className="secondary" disabled={busy} onClick={()=>void run(()=>api.agentExportDsh(),'连接器已导出，请按其中的接入说明安装')}><Download size={16}/> 导出连接器</button></div>
        <p className="integration-small">完成检测使用 Agent 的明确完成报告及生命周期事件，不读取或上传完整对话。完成报告仍由 Agent 判断，不代替结果验收。</p>
      </section>
      <section className="agent-monitor"><div className="monitor-heading"><h2>今晚等待哪些任务</h2><span className={state.night.armed?'connected-label':''}>{state.night.armed?'联动已开启':'联动未开启'}</span></div>
        <div className="watch-state" role="status"><Power size={22}/><div><strong>{state.night.message}</strong><p>{state.night.deadline?'提醒期间仍检查续跑和进程状态。':state.night.settleAt?'全部报告完成后观察 60 秒，再进入关机提醒。':'等待全部选定任务完成；退出、暂停或任务失联会解除联动。'}</p>{state.night.settleAt&&!state.night.deadline&&<Countdown at={state.night.settleAt}/>}</div></div>
        <div className="agent-session-list">{state.night.sessions.length===0?<div className="integration-empty"><Cable size={30}/><h3>等待第一条任务</h3><p>左侧配置接入后，给 Agent 发送一条新任务。正在进行的旧任务不会被自动认领。</p></div>:state.night.sessions.map(s=><label className="agent-session" key={s.id}><input type="checkbox" aria-label={`监控 ${s.name}`} checked={state.night.armed?state.night.selected.includes(s.id):selected.includes(s.id)} disabled={state.night.armed||s.status!=='running'||busy} onChange={e=>setSelected(ids=>e.target.checked?[...ids,s.id]:ids.filter(id=>id!==s.id))}/><div><strong>{s.name}</strong><small>{providerName[s.provider]} · {s.sessionId.slice(0,12)}</small><p>{s.detail}</p></div><span className={`agent-status ${s.status}`}>{statuses[s.status]}</span></label>)}</div>
        <div className="watch-actions">{state.night.armed?<button className="secondary" disabled={busy} onClick={()=>void run(()=>api.agentDisarm())}><Square size={16}/> 取消夜间联动</button>:<button className="primary" disabled={busy||paused||!state.night.bridgeReady||!activeSelected.length} onClick={()=>setConfirm(true)}><Play size={16}/> 等待 {activeSelected.length} 个任务后关机</button>}{safe&&<button className="text-button" disabled={busy||paused||state.night.armed} onClick={()=>void run(()=>api.agentDemo())}>安全演示完成流程</button>}</div>
        <p className="integration-small">{safe?'安全测试模式：即使倒计时结束，也不会关闭电脑。':'到点会强制关机，未保存内容可能丢失。开启前请保存其他应用中的工作。'}</p>
      </section>
    </div>:<div className="integration-body theme-layout">
      <section className="theme-library"><div className="theme-library-actions"><button className="primary" disabled={busy} onClick={()=>void run(()=>api.themeImport(),'美化包已加入主题库，尚未应用')}><FileUp size={17}/> 导入美化文件</button><button className="secondary" disabled={busy} onClick={()=>setPaste(true)}>粘贴主题</button></div><p>JSON、TXT、CSS、Dream Skin ZIP 与背景图片。先收藏，再配置原客户端。</p><label className="field">适用客户端<select value={filter} onChange={e=>{setFilter(e.target.value);setThemeId('');}}><option value="all">全部主题 · {state.themes.length}</option><option value="codex">Codex</option><option value="claude">Claude Desktop</option><option value="deepseek">DeepSeek Harness</option><option value="css">自定义 CSS</option></select></label><div className="library-extra-filters"><label>明暗<select value={styleFilter} onChange={e=>setStyleFilter(e.target.value)}><option value="all">全部</option><option value="light">浅色</option><option value="dark">深色</option></select></label><label>格式<select value={formatFilter} onChange={e=>setFormatFilter(e.target.value)}><option value="all">全部</option>{Object.entries(formats).map(([k,n])=><option key={k} value={k}>{n}</option>)}</select></label><label>应用状态<select value={readyFilter} onChange={e=>setReadyFilter(e.target.value)}><option value="all">全部</option><option value="ready">可配置</option><option value="missing">缺少加载器</option></select></label></div><div className="theme-list">{filtered.length?filtered.map(t=><button className={`theme-row ${theme?.id===t.id?'selected':''}`} key={t.id} onClick={()=>setThemeId(t.id)} aria-pressed={theme?.id===t.id}><span className="theme-swatches">{(t.colors.length?t.colors:['#20374b','#a6d7f5','#0d192a']).slice(0,4).map((c,i)=><i key={i} style={{backgroundColor:c}}/>)}</span><span><strong>{t.name}</strong><small>{formats[t.format]}</small></span></button>):<div className="integration-empty"><Palette size={30}/><h3>这里还没有主题</h3><p>导入对应客户端的社区文件，或切换筛选查看已收藏的主题。</p></div>}</div>
        <details className="theme-sources"><summary>社区主题与加载器</summary><button className="text-button" onClick={()=>void run(()=>api.integrationLink('codex-theme'))}>Codex Dream Skin <ExternalLink size={14}/></button><button className="text-button" onClick={()=>void run(()=>api.integrationLink('dsh-theme'))}>DeepSeek 外观插件 <ExternalLink size={14}/></button><button className="text-button" onClick={()=>void run(()=>api.integrationLink('claude-theme'))}>Claude Theme Mod <ExternalLink size={14}/></button></details>
      </section>
      <section className="theme-detail">
        <div className="client-check-heading"><h2>配置三种 Agent 的原界面</h2><button className="text-button" disabled={busy} onClick={()=>void run(()=>api.themeClients())}>{busy?'正在处理…':'重新检测客户端'}</button></div>
        <p>星枢负责配置，颜色和字体显示在原客户端中。</p>
        <details className="client-summary"><summary>客户端检测与目标位置</summary><div className="theme-client-status">{(['codex','claude','deepseek'] as const).map(client=><div key={client}><strong>{state.clients?.[client]?.label??({codex:'Codex',claude:'Claude Desktop',deepseek:'DeepSeek Harness'}[client])}</strong><span>{state.clients?.[client]?(state.clients[client]?.ready?'可以配置':'需要配置加载方式'):'等待检测'}</span><p>{state.clients?.[client]?.detail??'检测安装版本与可用的主题加载方式。'}</p>{client==='deepseek'&&<><button className="text-button" disabled={busy} onClick={()=>void run(()=>api.themeDshSelect(),safe?'已选择隔离测试目录':'DeepSeek 数据目录已连接')}>{safe?'使用隔离数据目录':'选择 DeepSeek 数据目录'}</button>{state.clients?.deepseek?.configPath&&<p className="theme-target-path">{state.clients.deepseek.configPath}</p>}</>}</div>)}</div></details>
        {theme?<>
          <div className="theme-detail-heading"><div><h2>{theme.name}</h2><p>{formats[theme.format]} · 主题文件已导入</p></div><button className="icon-button" aria-label="移除主题" disabled={busy} onClick={()=>setRemove(theme)}><Trash2 size={18}/></button></div>
          <ThemePreview theme={theme}/><p className="integration-small">{workshop.themes[theme.id]?.confirmedAt?'已由用户确认客户端效果':workshop.themes[theme.id]?.writtenAt?'配置已写入，待客户端确认':canApply(theme)?'已下载 · 可配置':'已下载 · 需准备对应加载器'}</p>{workshop.themes[theme.id]?.source&&<p className="integration-small">来源：{workshop.themes[theme.id].source} · 版本 {workshop.themes[theme.id].version?.slice(0,8)}</p>}{workshop.themes[theme.id]?.writtenAt&&!workshop.themes[theme.id]?.confirmedAt&&<button className="secondary" onClick={()=>void run(()=>api.workshopConfirm(theme.id),'已记录你对客户端效果的确认')}>我已在客户端确认效果</button>}
          <p className="theme-instruction">{theme.note}</p>
          {theme.format==='dreamskin-zip'&&<p className="integration-small">背景图片与 CSS 需要 Dream Skin 引擎；此处尚不能自动安装引擎。请通过下方社区入口核对版本兼容性后导入原包。</p>}
          <div className="theme-actions">
            {theme.format==='codex-native'&&<button className="primary" disabled={busy||!state.clients?.codex.ready} onClick={()=>void run(()=>api.themeCodexApply(theme.id))}>应用到 Codex</button>}
            {theme.format==='claude-json'&&<button className="primary" disabled={busy||!state.clients?.claude.ready} onClick={()=>void run(()=>api.themeClaudeApply(theme.id))}>应用到 Claude</button>}
            {theme.format==='dsh-dreamskin'&&<button className="primary" disabled={busy||!state.clients?.deepseek?.ready} onClick={()=>void run(()=>api.themeDshApply(theme.id))}>应用到 DeepSeek</button>}
            {(theme.format==='custom-css'||theme.format==='dreamskin-zip'||theme.format==='dsh-appearance')&&<button className="primary" onClick={()=>setGuide(true)}>查看对应配置方式</button>}
            {theme.format!=='dreamskin-zip'&&<button className="secondary" disabled={busy} onClick={()=>void run(async()=>{await api.themeCopy(theme.id);return '主题代码已复制，尚未应用；可在对应客户端或插件中手动导入。';})}><Clipboard size={17}/> 复制主题代码</button>}
            <button className="secondary" disabled={busy} onClick={()=>void run(()=>api.themeExport(theme.id),'主题文件已导出，尚未应用')}><Download size={17}/> 导出{theme.format==='dreamskin-zip'?'原美化包':'主题文件'}</button>
          </div>
        </>:<div className="integration-empty"><h3>选择要应用的美化包</h3><p>先导入主题，再选择应用到对应客户端。导入到星枢不会改变星枢自身的界面。</p></div>}
        <div className="theme-actions theme-recovery">
          <button className="text-button" disabled={busy||!state.codexRestore} onClick={()=>void run(()=>api.themeCodexRestore())}>恢复 Codex 原外观</button>
          <button className="text-button" disabled={busy} onClick={()=>void run(()=>api.themeClaudeRestore())}>恢复 Claude 原外观</button>
          <button className="text-button" disabled={busy||!state.dshRestore} onClick={()=>void run(()=>api.themeDshRestore())}>恢复 DeepSeek 原外观</button>
          <button className="text-button" onClick={()=>setGuide(true)}>三端配置指南</button>
        </div>
        <p className="integration-small">{safe?'当前是安全体验，只修改隔离测试配置。退出后正常启动星枢，才可配置真实客户端。':'应用前备份外观设置；保存配置后仍需在原客户端核对实际效果。'}不会更改 API 密钥、模型或连接设置。</p>
      </section>
    </div>}
    {paste&&<Modal title="粘贴主题代码" onClose={()=>{if(!busy)setPaste(false);}}><label className="field">主题名称<input value={name} maxLength={80} onChange={e=>setName(e.target.value)}/></label><label className="field">主题代码<textarea autoFocus rows={8} value={raw} onChange={e=>setRaw(e.target.value)} placeholder="codex-theme-v1:… 或主题 JSON"/></label><p className="integration-small">仅支持数据格式，不执行粘贴内容中的命令。</p><button className="primary full" disabled={busy||!raw.trim()} onClick={async()=>{if(await run(()=>api.themeImportText(raw,name),'主题已导入')){setPaste(false);setRaw('');}}}>{busy?'正在导入…':'导入主题库'}</button>{message&&<p role="alert">{message}</p>}</Modal>}
    {remove&&<Modal title="从主题库移除？" onClose={()=>{if(!busy)setRemove(null);}}><p>{remove.name}</p><p className="muted">不会修改客户端当前已经应用的外观。</p><button className="danger-button" disabled={busy} onClick={async()=>{if(await run(()=>api.themeRemove(remove.id),'已从主题库移除'))setRemove(null);}}>移除主题</button></Modal>}
    {guide&&<Modal title="三端原界面美化配置" onClose={()=>setGuide(false)}><div className="theme-setup-steps"><h3>Codex</h3><p>原生主题代码与 JSON：导入后选择“应用到 Codex”，重新打开客户端核对。含 CSS 和背景的 Dream Skin ZIP：导出原包，交给兼容的 Dream Skin 引擎安装；原生配色接口不支持背景图片。</p><button className="text-button" onClick={()=>void run(()=>api.integrationLink('codex-theme'))}>Codex Dream Skin 说明 <ExternalLink size={14}/></button><h3>Claude Desktop</h3><p>{state.clients?.claude.detail}</p><p>在 Theme Mod 项目核对独立安装版兼容性。加载器会修改程序文件，星枢不自动安装。加载器就绪后重新检测，导入配色 JSON 并应用；codeBg 支持半透明颜色。商店版不能直接套用独立安装版补丁。</p><button className="text-button" onClick={()=>void run(()=>api.integrationLink('claude-theme'))}>Claude Theme Mod 说明 <ExternalLink size={14}/></button><h3>DeepSeek Harness</h3><p>安装并启用 Dream Skin 9.x；选择包含 profiles 的数据目录（DSH_HOME），不是程序安装目录。导入 Dream Skin 原生主题包，或去背景页选图片。完全退出 DeepSeek 后配置，再重新打开；恢复按钮还原星枢修改的外观字段。</p><p>旧版 DSH UI Appearance 配色 JSON 需复制或导出到同名插件；它与 Dream Skin 的主题包格式不同。</p><button className="text-button" onClick={()=>void run(()=>api.integrationLink('dsh-theme'))}>DeepSeek Dream Skin 说明 <ExternalLink size={14}/></button><h3>单独 CSS 文件</h3><p>支持收藏、复制与原样导出。请使用作者指定的加载器和客户端版本；CSS 的页面选择器不能跨客户端通用。星枢不执行脚本、安装程序或未知压缩包。</p></div></Modal>}
    {confirm&&<Modal title="开启今晚的自动关机？" onClose={()=>setConfirm(false)}><p>等待以下 {activeSelected.length} 个任务报告完成：</p><ul className="confirmation-list">{state.night.sessions.filter(s=>activeSelected.includes(s.id)).map(s=><li key={s.id}>{s.name}</li>)}</ul><p className="form-hint">完成后观察 60 秒，再显示关机提醒。续跑会撤销倒计时。{safe?'当前为安全测试，不会实际关机。':'到点强制关机，未保存内容可能丢失。'}</p><button className="primary full" disabled={busy||!activeSelected.length} onClick={async()=>{if(await run(()=>api.agentArm(activeSelected)))setConfirm(false);}}>确认开启夜间联动</button>{message&&<p role="alert">{message}</p>}</Modal>}
  </main>;
}
function ThemePreview({theme}:{theme:ThemeItem}){const c=theme.colors;return <div className="theme-preview" aria-label="主题配色预览"><div className="preview-palette">{c.length?c.map((color,i)=><div key={i}><span style={{backgroundColor:color}}/><code>{color}</code></div>):<p>此包使用背景图或 CSS；请在对应美化工具中预览实际效果。</p>}</div><span>配色预览 · 实际布局由原客户端决定</span></div>;}
