import {memo,useMemo,useState,useEffect,RefObject} from 'react';
import {Plus,Search,Power,Bell,Pencil,Copy,SkipForward,Trash2,ListChecks,Moon} from 'lucide-react';
import type {Snapshot} from '../shared';
import {selectPlans,recurrence,fullTime,isFinished} from '../plan-utils';
import {Switch} from './UI';
type Row=Snapshot['plans'][number];
export const Plans=memo(function Plans({state,searchRef,busy,onCreate,onEdit,onCopy,onSkip,onDelete,onBatch,onToggle}:{state:Snapshot;searchRef:RefObject<HTMLInputElement|null>;busy:boolean;onCreate:()=>void;onEdit:(p:Row)=>void;onCopy:(p:Row)=>void;onSkip:(p:Row)=>void;onDelete:(p:Row[])=>void;onBatch:(ids:string[],action:'enable'|'disable')=>Promise<boolean>;onToggle:(p:Row)=>void}){
 const [query,setQuery]=useState(''),[kind,setKind]=useState('all'),[status,setStatus]=useState('all'),[sort,setSort]=useState('next'),[selected,setSelected]=useState<string[]>([]),[page,setPage]=useState(0);
 const plans=useMemo(()=>selectPlans(state.plans,query,kind,status,sort),[state.plans,query,kind,status,sort]);
 useEffect(()=>{setSelected([]);setPage(0);},[query,kind,status]);
 useEffect(()=>{setSelected(ids=>ids.filter(id=>state.plans.some(p=>p.id===id)));setPage(p=>Math.min(p,Math.max(0,Math.ceil(plans.length/50)-1)));},[state.plans]);
 const pageRows=plans.slice(page*50,(page+1)*50),all=plans.length>0&&plans.every(p=>selected.includes(p.id));
 const toggle=(id:string)=>setSelected(ids=>ids.includes(id)?ids.filter(x=>x!==id):[...ids,id]);
 const ended=state.plans.filter(isFinished),disabled=busy||!!state.storageError;
 return <section className="plans-panel"><div className="plans-heading"><div><h2>时间计划 <span>{state.plans.length}</span></h2><p>安排、调整，然后安心去忙。</p></div><button className="primary" disabled={disabled} onClick={onCreate}><Plus size={18}/> 新建计划</button></div>
 <div className="plan-search"><Search size={17}/><input ref={searchRef} aria-label="搜索计划" placeholder="搜索计划名称…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button className="text-button" onClick={()=>setQuery('')}>清除</button>}</div>
 <div className="plan-filters"><div className="filters" role="group" aria-label="筛选计划">{[['all','全部计划'],['shutdown','定时关机'],['alarm','闹钟提醒']].map(([key,label])=><button key={key} aria-pressed={kind===key} onClick={()=>setKind(key)}>{label}</button>)}</div><div className="filter-selects"><select aria-label="计划状态" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">全部状态</option><option value="enabled">已启用</option><option value="disabled">已停用</option><option value="finished">已结束</option></select><select aria-label="排序方式" value={sort} onChange={e=>setSort(e.target.value)}><option value="next">执行时间</option><option value="created">创建时间</option><option value="name">名称</option></select></div></div>
 <div className="selection-bar"><label><input type="checkbox" aria-label="全选当前筛选结果" disabled={!plans.length||disabled} checked={all} onChange={()=>setSelected(all?[]:plans.map(p=>p.id))}/>{selected.length?`已选 ${selected.length} 条`:`${plans.length} 条计划`}</label>{selected.length>0?<div><button className="text-button" disabled={disabled} onClick={async()=>{if(await onBatch(selected,'enable'))setSelected([]);}}>批量启用</button><button className="text-button" disabled={disabled} onClick={async()=>{if(await onBatch(selected,'disable'))setSelected([]);}}>批量停用</button><button className="text-button danger-text" disabled={disabled} onClick={()=>onDelete(state.plans.filter(p=>selected.includes(p.id)))}>批量删除</button></div>:<button className="text-button" disabled={!ended.length||disabled} onClick={()=>onDelete(ended)}><ListChecks size={16}/> 清理已结束</button>}</div>
 <div className="plan-list">{!plans.length?<div className="empty"><Moon size={35}/><h3>{state.plans.length?'没有符合条件的计划':'给忙碌的一天，设一个终点。'}</h3><p>{state.plans.length?'试试其他名称或筛选条件。':'创建定时关机，或留一个温柔的提醒。'}</p><button className="secondary" onClick={state.plans.length?()=>{setQuery('');setKind('all');setStatus('all');}:onCreate}>{state.plans.length?'重置筛选':'创建一个计划'}</button></div>:pageRows.map(p=><article className={`plan-row ${!p.enabled?'disabled':''}`} key={p.id}><input type="checkbox" aria-label={`选择${p.name}`} checked={selected.includes(p.id)} onChange={()=>toggle(p.id)} disabled={disabled}/><div className={`plan-type ${p.kind}`}>{p.kind==='shutdown'?<Power size={19}/>:<Bell size={19}/>}</div><div className="plan-main"><div className="plan-name"><h3>{p.name}</h3><span className={`status-tag ${!p.enabled?'off':''}`}>{!p.enabled?'已停用':isFinished(p)?p.outcome??p.status:state.paused?'暂停中':'已启用'}</span></div><div className="plan-clock">{p.time}<span>{recurrence(p)}</span></div><div className="plan-meta">{p.nextAt?`${state.paused?'原定':'下次执行'} · ${fullTime(p.nextAt)}`:p.outcome??p.status}</div><div className="row-actions"><button title="编辑计划" aria-label={`编辑${p.name}`} onClick={()=>onEdit(p)} disabled={disabled}><Pencil size={14}/> 编辑</button><button aria-label={`复制${p.name}`} onClick={()=>onCopy(p)} disabled={disabled}><Copy size={14}/> 复制</button><button aria-label={`跳过${p.name}`} disabled={disabled||!p.nextAt} onClick={()=>onSkip(p)}><SkipForward size={14}/> 跳过一次</button><button aria-label={`删除${p.name}`} className="danger-text" onClick={()=>onDelete([p])} disabled={disabled}><Trash2 size={14}/></button></div></div><Switch value={p.enabled} disabled={disabled} label={`${p.enabled?'停用':'启用'}${p.name}`} onChange={()=>onToggle(p)}/></article>)}</div>
 {plans.length>50&&<nav className="pagination" aria-label="计划分页"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>上一页</button><span>{page+1} / {Math.ceil(plans.length/50)} · 每页 50 条</span><button disabled={(page+1)*50>=plans.length} onClick={()=>setPage(p=>p+1)}>下一页</button></nav>}
 <p className="plan-note">关闭窗口后继续在托盘运行；从托盘退出后，所有计时停止。</p></section>;
});
