import {useState} from 'react';
import {Timer,CalendarDays,Pencil,Trash2} from 'lucide-react';
import type {ExperienceSnapshot,Preset,PresetInput} from '../shared';
import {normalizePreset} from '../presets';
import {Modal} from './UI';
import {NotesField} from './NotesField';
export function PresetLibrary({experience,onClose,onApply,onBuiltin,onEdit,onDelete}:{experience:ExperienceSnapshot;onClose:()=>void;onApply:(p:Preset)=>void;onBuiltin:(id:string)=>void;onEdit:(p:Preset)=>void;onDelete:(id:string)=>Promise<boolean>}){
 const [deleting,setDeleting]=useState<Preset|null>(null),[busy,setBusy]=useState(false);
 return <><Modal title="常用模板" wide onClose={onClose}><p className="muted">模板只预填内容，确认保存后才会创建计划。</p><h3>内置模板</h3><div className="builtin-presets">{[['workday','工作日 23:30 关机'],['daily','每天 21:00 提醒'],['alarm30','30 分钟后提醒'],['shutdown120','2 小时后关机']].map(([id,label])=><button className="secondary" key={id} onClick={()=>onBuiltin(id)}>{label}</button>)}</div><h3 className="personal-heading">我的模板 <small>{experience.presets.length}</small></h3>{experience.error&&<p className="form-hint" role="alert">{experience.error}</p>}<div className="preset-list">{experience.presets.length?experience.presets.map(p=><article key={p.id}><button className="preset-apply" onClick={()=>onApply(p)} disabled={!!experience.error}>{p.type==='quick'?<Timer size={19}/>:<CalendarDays size={19}/>}<span><strong>{p.name}</strong><small>{p.type==='quick'?`${p.minutes} 分钟后`:p.repeat==='once'?`下次 ${p.time}`:p.repeat==='daily'?`每天 ${p.time}`:`每周 ${p.weekdays.map(d=>'日一二三四五六'[d]).join('、')} ${p.time}`} · {p.kind==='shutdown'?'关机':'提醒'}</small></span></button><button className="icon-button" aria-label={`编辑模板${p.name}`} disabled={!!experience.error} onClick={()=>onEdit(p)}><Pencil size={17}/></button><button className="icon-button danger-text" aria-label={`删除模板${p.name}`} disabled={!!experience.error} onClick={()=>setDeleting(p)}><Trash2 size={17}/></button></article>):<p className="muted">在计划编辑器或快捷计时面板中，点击“存为常用模板”。</p>}</div></Modal>{deleting&&<Modal title="删除这个模板？" onClose={()=>{if(!busy)setDeleting(null);}}><h3>{deleting.name}</h3><p className="muted">已创建的计划不会改变。</p><div className="modal-actions"><button className="secondary" disabled={busy} onClick={()=>setDeleting(null)}>保留模板</button><button className="danger-button" disabled={busy} onClick={async()=>{setBusy(true);try{if(await onDelete(deleting.id))setDeleting(null);}finally{setBusy(false);}}}>删除模板</button></div></Modal>}</>;
}
export function PresetEditor({initial,onClose,onSave}:{initial:PresetInput&{id?:string};onClose:()=>void;onSave:(p:PresetInput,id?:string)=>Promise<boolean>}){
 const [value,setValue]=useState<PresetInput>(initial),[error,setError]=useState(''),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(false);
 const dirty=JSON.stringify(value)!==JSON.stringify(initial),close=()=>{if(!busy){if(dirty)setConfirm(true);else onClose();}};
 return <><Modal title={initial.id?'编辑常用模板':'存为常用模板'} onClose={close}><form noValidate onSubmit={async e=>{e.preventDefault();if(busy)return;let p:PresetInput;try{p=normalizePreset(value);}catch(e){setError(String(e).replace(/^Error: /,''));return;}setBusy(true);try{if(await onSave(p,initial.id))onClose();}finally{setBusy(false);}}}>
 <label className="field">模板名称<input aria-label="模板名称" autoFocus maxLength={48} value={value.name} onChange={e=>setValue({...value,name:e.target.value})}/></label><div className="form-grid"><label className="field">模板动作<select aria-label="模板动作" value={value.kind} onChange={e=>setValue({...value,kind:e.target.value as 'shutdown'|'alarm'})}><option value="shutdown">定时关机</option><option value="alarm">闹钟提醒</option></select></label>{value.type==='quick'?<label className="field">模板分钟<input aria-label="模板分钟" type="number" min="1" max="1440" value={Number.isNaN(value.minutes)?'':value.minutes} onChange={e=>setValue({...value,minutes:e.target.valueAsNumber})}/></label>:<label className="field">模板时间<input aria-label="模板时间" type="time" value={value.time} onChange={e=>setValue({...value,time:e.target.value})}/></label>}</div>
 {value.type==='schedule'&&<><label className="field">模板重复<select aria-label="模板重复" value={value.repeat} onChange={e=>setValue({...value,repeat:e.target.value as 'once'|'daily'|'weekly'})}><option value="once">单次 · 下次这个时刻</option><option value="daily">每天</option><option value="weekly">每周</option></select></label>{value.repeat==='weekly'&&<fieldset className="weekdays"><legend>模板星期</legend>{[1,2,3,4,5,6,0].map(d=><button type="button" key={d} aria-pressed={value.weekdays.includes(d)} onClick={()=>setValue({...value,weekdays:value.weekdays.includes(d)?value.weekdays.filter(x=>x!==d):[...value.weekdays,d]})}>{'日一二三四五六'[d]}</button>)}</fieldset>}</>}
 <NotesField value={value.notes} onChange={notes=>setValue({...value,notes})}/>
 {error&&<p className="field-error" role="alert">{error}</p>}<p className="muted">保存模板不会创建计划，也不会改变已有计划。单次模板不记住固定日期。</p><div className="modal-actions"><button type="button" className="secondary" disabled={busy} onClick={close}>取消</button><button className="primary" disabled={busy}>{busy?'正在保存…':'保存模板'}</button></div></form></Modal>{confirm&&<Modal title="放弃模板修改？" onClose={()=>setConfirm(false)}><p>模板修改尚未保存。</p><div className="modal-actions"><button className="secondary" onClick={()=>setConfirm(false)}>继续编辑</button><button className="danger-button" onClick={onClose}>放弃修改</button></div></Modal>}</>;
}
