import {Power,Bell,Pause,RotateCcw,VolumeX} from 'lucide-react';
import type {RuntimeState} from '../shared';
import {fullTime} from '../plan-utils';
import {Modal} from './UI';
import {Countdown} from './Console';
export function Reminder({runtime,busy,onAction,onPause}:{runtime:RuntimeState;busy:boolean;onAction:(keys:string[],action:'cancel'|'snooze',minutes?:number)=>void;onPause:()=>void}){
 const first=Math.min(...runtime.warnings.map(o=>o.at)),warnings=runtime.warnings.filter(o=>o.at===first),alarms=runtime.alarms;
 return <Modal title="到时提醒"><div className="reminder">{warnings.length>0&&<section><Power size={34}/><h2>{warnings.every(w=>w.demo)?'体验一次，安心休息':'电脑即将休息'}</h2><div className="reminder-plans">{warnings.map(w=><div key={w.key}><p>{w.name}</p>{w.notes&&<p className="reminder-notes">{w.notes}</p>}</div>)}</div><p className="muted">执行时间 · {fullTime(first)}</p><Countdown at={first}/><p className="form-hint">{warnings.every(w=>w.demo)?'这是演示，不会执行实际关机。':'到点将强制关机，未保存的内容可能丢失。'}</p><button className="primary full" disabled={busy} onClick={()=>onAction(warnings.map(w=>w.key),'cancel')}>{warnings.every(w=>w.demo)?'结束演示':'取消本次关机'}</button><div className="snooze"><span>本次延后</span>{[10,30,60].map(m=><button className="secondary" key={m} disabled={busy} onClick={()=>onAction(warnings.map(w=>w.key),'snooze',m)}>{m} 分钟</button>)}</div></section>}
 {alarms.length>0&&<section className={warnings.length?'alarm-below':''}><Bell size={32}/><h2>该留意一下时间了</h2><div className="reminder-plans">{alarms.map(a=><div key={a.key}><p>{a.name}</p>{a.notes&&<p className="reminder-notes">{a.notes}</p>}</div>)}</div><div className="alarm-actions"><button className="primary" disabled={busy} onClick={()=>onAction(alarms.map(a=>a.key),'cancel')}><VolumeX size={16}/> 停止提醒</button><button className="secondary" disabled={busy} onClick={()=>onAction(alarms.map(a=>a.key),'snooze',10)}><RotateCcw size={16}/> 10 分钟后提醒</button></div><p className="muted">自动停止于 {fullTime(Math.max(...alarms.map(a=>a.endsAt??a.at+60000)))}</p></section>}
 {[...warnings,...alarms].some(o=>!o.demo)&&<button className="text-button reminder-pause" disabled={busy} onClick={onPause}><Pause size={16}/> 暂停全部计划</button>}</div></Modal>;
}
