import {useEffect,useState} from 'react';
import {Github,ArrowUpRight,Volume2,Upload,Download,Moon} from 'lucide-react';
import type {Settings,LogEntry,LogFilter,ImportPreview} from '../shared';
import {PRODUCT} from '../product';
import {localDate,fullTime} from '../plan-utils';
import {Modal,Switch} from './UI';
export function SettingsPanel({settings,onClose,onUpdate,onDemo,onLink,onImport,onExport,fileBusy}:{settings:Settings;onClose:()=>void;onUpdate:(s:Settings)=>Promise<boolean>;onDemo:()=>void;onLink:(t:'author'|'repository')=>void;onImport:()=>void;onExport:()=>void;fileBusy:boolean}){
 const [tab,setTab]=useState('sound'),[volume,setVolume]=useState(settings.volume);
 useEffect(()=>setVolume(settings.volume),[settings.volume]);
 const commit=()=>{if(volume!==settings.volume)void onUpdate({...settings,volume});};
 return <Modal title="设置与关于" onClose={()=>{commit();onClose();}} wide><div className="settings-tabs" role="group" aria-label="设置分类">{[['sound','声音与提醒'],['appearance','外观'],['data','数据管理'],['about','关于']].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>{commit();setTab(id);}}>{label}</button>)}</div><div className="settings-content">
 {tab==='sound'&&<><div className="setting"><div><strong>按钮与操作音效</strong><p>短促的电子反馈，不影响闹钟响铃。</p></div><Switch value={settings.sound} label="按钮音效" onChange={()=>void onUpdate({...settings,sound:!settings.sound})}/></div><div className="setting vertical"><label htmlFor="volume">提醒音量 <b>{Math.round(volume*100)}%</b></label><input id="volume" type="range" min="0" max="1" step="0.05" value={volume} onChange={e=>setVolume(Number(e.target.value))} onPointerUp={commit} onKeyUp={commit} onBlur={commit}/><button className="text-button" onClick={async()=>{if(volume===settings.volume||await onUpdate({...settings,volume}))onDemo();}}><Volume2 size={17}/> 试听闹钟</button></div><div className="form-grid"><label className="field">关机提前提醒<select aria-label="关机提前提醒" value={settings.warningMinutes??5} onChange={e=>void onUpdate({...settings,warningMinutes:Number(e.target.value)})}>{[1,5,10,15,30].map(n=><option key={n} value={n}>{n} 分钟</option>)}</select></label><label className="field">闹钟响铃时长<select aria-label="闹钟响铃时长" value={settings.alarmSeconds??60} onChange={e=>void onUpdate({...settings,alarmSeconds:Number(e.target.value)})}>{[15,30,60].map(n=><option key={n} value={n}>{n} 秒</option>)}</select></label></div><p className="muted">新设置用于后续提醒，已经开始的提醒不会重新计时。</p></>}
 {tab==='appearance'&&<><div className="setting"><div><strong>减少动态效果</strong><p>关闭轨道动画与鼠标波纹，保留必要的状态反馈。</p></div><Switch value={settings.reducedMotion} label="减少动态效果" onChange={()=>void onUpdate({...settings,reducedMotion:!settings.reducedMotion})}/></div><div className="settings-note"><Moon size={24}/><p>窗口隐藏或最小化后停止装饰绘制。<br/>星眠遵循系统的减少动态效果设置。</p></div><p className="muted">Ctrl+N 新建计划 · Ctrl+F 搜索 · Esc 关闭普通面板</p></>}
 {tab==='data'&&<><h3>计划备份与迁移</h3><p className="muted">导出只包含计划定义。导入会跳过重复和过期计划，其余计划默认停用，核对后再启用。</p><div className="data-actions"><button className="secondary" disabled={fileBusy} onClick={onImport}><Upload size={17}/> 导入计划</button><button className="secondary" disabled={fileBusy} onClick={onExport}><Download size={17}/> 导出计划</button></div><p className="muted">支持版本 1 的星眠计划 JSON，每个文件最多 1 MB、500 条计划。执行记录可以在记录面板单独导出。</p></>}
 {tab==='about'&&<section className="about-product"><div className="about-title"><Moon size={35}/><div><h3>星眠 <span>Star Sleep</span></h3><p>版本 {PRODUCT.version} · Windows 桌面版</p></div></div><p>第一作者 <button className="text-button" onClick={()=>onLink('author')}>{PRODUCT.author} <ArrowUpRight size={15}/></button></p><p className="author-bio">借助 AI，把日常问题做成实用、耐看的产品。<br/>让夜间的工作有个终点，也给电脑一段休息。</p><button className="secondary" onClick={()=>onLink('repository')}><Github size={18}/> GitHub 项目主页 <ArrowUpRight size={16}/></button><p className="muted">允许个人和商业工作使用 · 禁止售卖软件及改版</p><p className="muted">仅软件运行时有效，不注册 Windows 定时任务，不自动启动，不唤醒电脑。</p></section>}
 </div></Modal>;
}
export function Logs({logs,onClose,onExport}:{logs:LogEntry[];onClose:()=>void;onExport:(f:LogFilter)=>Promise<void>}){
 const [filter,setFilter]=useState<LogFilter>({query:'',date:'',errorsOnly:false}),[busy,setBusy]=useState(false);
 const shown=logs.filter(l=>(!filter.query.trim()||l.text.toLocaleLowerCase().includes(filter.query.trim().toLocaleLowerCase()))&&(!filter.date||localDate(new Date(l.at))===filter.date)&&(!filter.errorsOnly||l.level==='error'));
 return <Modal title="执行记录" onClose={onClose} wide><p className="muted">保留最近 200 条记录，仅存储在本机。</p><div className="form-grid"><label className="field">搜索记录<input aria-label="搜索记录" value={filter.query} maxLength={200} placeholder="计划名称或操作…" onChange={e=>setFilter({...filter,query:e.target.value})}/></label><label className="field">记录日期<input aria-label="记录日期" type="date" value={filter.date} onChange={e=>setFilter({...filter,date:e.target.value})}/></label></div><div className="selection-bar"><label><input type="checkbox" checked={filter.errorsOnly} onChange={e=>setFilter({...filter,errorsOnly:e.target.checked})}/>仅看错误</label><span>{shown.length} 条</span><button className="secondary" disabled={busy||!shown.length} onClick={async()=>{setBusy(true);try{await onExport(filter);}finally{setBusy(false);}}}><Download size={16}/> 导出当前记录</button></div><div className="logs">{shown.length?shown.map((l,i)=><div key={i} className={`log ${l.level}`}><time>{fullTime(l.at)}</time><p>{l.text}</p></div>):<div className="empty small">没有符合条件的记录</div>}</div></Modal>;
}
export function ImportPanel({preview,busy,onClose,onConfirm}:{preview:ImportPreview;busy:boolean;onClose:()=>void;onConfirm:()=>void}){return <Modal title="导入前，核对一下" onClose={()=>{if(!busy)onClose();}}><p className="muted">追加到现有计划，不覆盖已有内容。导入后全部停用。</p><div className="import-counts"><span><strong>{preview.imported}</strong> 可导入</span><span><strong>{preview.duplicate}</strong> 重复</span><span><strong>{preview.expired}</strong> 已过期</span></div><ul className="import-names">{preview.names.map((name,i)=><li key={i}><span>{name}</span><small>导入后停用</small></li>)}{preview.skipped.map((item,i)=><li key={`skip-${i}`} className="muted"><span>{item.name}</span><small>{item.reason}</small></li>)}</ul><div className="modal-actions"><button className="secondary" disabled={busy} onClick={onClose}>取消导入</button><button className="primary" disabled={busy||!preview.imported} onClick={onConfirm}>{busy?'正在导入…':`确认导入 ${preview.imported} 条`}</button></div></Modal>;}
