import {useEffect,useState} from 'react';
import {Search,ArrowLeft,Download,ExternalLink,ShieldCheck,History,FolderOpen,RotateCcw} from 'lucide-react';
import type {GithubRepo,RepositorySkills,SkillAudit,SkillTarget,MarketState} from '../market-types';

const api=()=>window.starSleep!;
const message=(e:unknown)=>String(e).replace(/^Error: (Error invoking remote method '[^']+': Error: )?/,'');
export function SkillMarketPanel({safe}:{safe:boolean}){
 const [query,setQuery]=useState('agent skills'),[sort,setSort]=useState<'relevance'|'stars'|'updated'>('relevance'),[page,setPage]=useState(1),[total,setTotal]=useState(0),[searched,setSearched]=useState(false),[repos,setRepos]=useState<GithubRepo[]>([]);
 const [repository,setRepository]=useState<RepositorySkills|null>(null),[filter,setFilter]=useState(''),[audit,setAudit]=useState<SkillAudit|null>(null),[state,setState]=useState<MarketState|null>(null),[history,setHistory]=useState(false);
 const [busy,setBusy]=useState(''),[feedback,setFeedback]=useState(''),[target,setTarget]=useState<SkillTarget>('codex'),[accepted,setAccepted]=useState(false),[file,setFile]=useState('SKILL.md'),[content,setContent]=useState(''),[remove,setRemove]=useState('');
 async function run(label:string,fn:()=>Promise<void>){if(busy)return;setBusy(label);setFeedback('');try{await fn();}catch(e){setFeedback(message(e));}finally{setBusy('');}}
 async function refresh(){setState(await api().marketState());}
 useEffect(()=>{void refresh().catch(e=>setFeedback(message(e)));},[]);
 useEffect(()=>{if(!audit)return;let live=true;setContent('正在读取…');void api().skillAuditFile(audit.token,file).then(text=>{if(live)setContent(text);}).catch(e=>{if(live)setContent(message(e));});return()=>{live=false;};},[audit,file]);
 async function discover(repo:string){setRepository(await api().githubSkills(repo));setAudit(null);setHistory(false);setFilter('');}
 async function search(next=1,q=query){await run('正在搜索 GitHub…',async()=>{const direct=q.trim().replace(/^https:\/\/github.com\//,'').replace(/\/$/,'');if(/^[\w.-]+\/[\w.-]+$/.test(direct)){await discover(direct);return;}const found=await api().githubSearch(q,sort,next);setRepos(found.items);setTotal(found.total);setPage(next);setSearched(true);setRepository(null);setAudit(null);if(found.partial)setFeedback('GitHub 返回了部分结果，请缩小关键词后重试。');});}
 const back=()=>{setFeedback('');if(audit){setAudit(null);setAccepted(false);}else if(repository)setRepository(null);else setHistory(false);};
 const selectedTarget=state?.targets.find(t=>t.id===target),blocked=audit?.findings.some(f=>f.level==='block');
 return <div className="market-panel"><div className="market-title"><div><h2>发现值得装的 Skills</h2><p>按工作场景寻找，查看原文，再把能力装进你的 Agent。</p></div><button className="secondary" disabled={!!busy} onClick={()=>{setHistory(!history);setAudit(null);setRepository(null);setRemove('');void refresh().catch(e=>setFeedback(message(e)));}}><History size={16}/>{history?'返回发现':'安装记录'}</button></div>
 {safe&&<p className="usage-scope">安全体验：安装写入隔离的 skill-samples，不更改真实客户端。</p>}
 {state?.error&&<p role="alert" className="toolbox-feedback">{state.error}</p>}{feedback&&<p role="status" className="toolbox-feedback">{feedback}</p>}{busy&&<p role="status" className="market-progress">{busy}</p>}
 {(repository||audit)&&<button className="text-button" disabled={!!busy} onClick={back}><ArrowLeft size={15}/>{audit?'返回技能目录':'返回搜索结果'}</button>}
 {history?<section aria-label="安装记录"><h3>我的安装记录</h3><p className="usage-scope">只管理由星枢安装的技能。移除会保留备份，可随时恢复；有本地修改时停止操作。</p>{!state?.installs.length&&<div className="toolbox-empty">还没有安装记录。先选择一个适合自己的技能。</div>}{state?.installs.slice().reverse().map(item=><article className="market-installed" key={item.id}><div><h3>{item.name}</h3><span>{item.target} · {item.status==='installed'?'已安装':'已移除，可恢复'}</span></div><p>{item.repo} · 提交 {item.commit.slice(0,10)} · {new Date(item.installedAt).toLocaleString()}</p><p className="path-text">{item.destination}</p><div className="source-actions"><button className="text-button" onClick={()=>void run('正在打开…',async()=>{await api().marketReveal(item.id);})}><FolderOpen size={15}/>查看文件</button>{item.status==='removed'?<button className="secondary" disabled={!!busy||!!state.error} onClick={()=>void run('正在恢复…',async()=>{await api().skillRestore(item.id);await refresh();setFeedback('已恢复原版本技能。');})}><RotateCcw size={15}/>恢复技能</button>:<button className="secondary" disabled={!!busy||!!state.error} onClick={()=>setRemove(item.id)}>移除技能</button>}</div>{remove===item.id&&<div className="market-confirm"><p>将从 {item.target} 移除「{item.name}」，保留文件备份。</p><button className="danger" disabled={!!busy} onClick={()=>void run('正在移除…',async()=>{await api().skillUninstall(item.id);setRemove('');await refresh();setFeedback('已移除，可在记录中恢复。');})}>确认移除</button><button className="text-button" disabled={!!busy} onClick={()=>setRemove('')}>取消</button></div>}</article>)}</section>
 :audit?<section className="market-audit" aria-label="安装前审查"><div className="market-audit-heading"><ShieldCheck size={23}/><div><h3>{audit.name||'技能格式待修复'}</h3><p>{audit.description}</p></div></div><p className="usage-scope">{audit.repo} / {audit.path||'根目录'} · 版本 {audit.commit.slice(0,12)} · {audit.license} · {audit.files.length} 个文件</p><div className="market-audit-grid"><div><h3>静态检查线索</h3><p className="usage-scope">逐文件规则扫描，不执行代码。可能误报或漏报；没有发现不等于安全认证。请核对用途、来源和依赖。</p><ul className="audit-findings">{audit.findings.map((f,i)=><li key={i} className={'finding-'+f.level}><strong>{f.level==='block'?'停止安装':f.level==='review'?'需要核对':'检查说明'}</strong><span>{f.message}</span>{f.file&&<button className="text-button" onClick={()=>setFile(f.file)}>{f.file}{f.line?`:${f.line}`:''}</button>}</li>)}</ul></div><div className="market-source"><label>文件原文<select aria-label="审查文件" value={file} onChange={e=>setFile(e.target.value)}>{audit.files.map(f=><option key={f.path} value={f.path}>{f.path} · {Math.ceil(f.bytes/1024)} KB</option>)}</select></label><pre tabIndex={0}>{content}</pre></div></div>
 <div className="market-install"><h3>安装到哪里</h3><label className="field">目标客户端<select aria-label="安装目标" value={target} onChange={e=>{setTarget(e.target.value as SkillTarget);setAccepted(false);}}>{state?.targets.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><p>{selectedTarget?.detail}</p>{!safe&&<button className="text-button" disabled={!!busy} onClick={()=>void run("选择客户端 Skills 目录…",async()=>{if(await api().marketTarget(target)){await refresh();setAccepted(false);}})}>更改目标目录</button>}<p className="path-text">{selectedTarget?.path}\{audit.name}</p><p className="usage-scope">只复制审查过的文件；不运行安装脚本，不代填 API Key，不自动安装外部依赖。同名目录不会覆盖。安装后在客户端的新对话中确认可用；必要时重启客户端。</p><label className="market-consent"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/>我已核对技能原文、使用条件与目标目录，同意安装或导出这一版本。</label><div className="source-actions"><button className="primary" disabled={!!busy||!accepted||blocked||!!state?.error} onClick={()=>void run('正在安装已审查版本…',async()=>{const done=await api().skillInstall(audit.token,target);await refresh();setAccepted(false);setFeedback(`已安装 ${done.name}。可在“安装记录”查看位置或撤销；请在客户端新对话中确认加载。`);})}><Download size={16}/>确认并安装</button><button className="secondary" disabled={!!busy||!accepted||blocked} onClick={()=>void run('正在导出…',async()=>{if(await api().skillZip(audit.token))setFeedback('已导出。请在 Claude 的自定义 / Skills 页面上传 ZIP；导出不代表已安装到 Claude 账号。');})}>导出 Claude 聊天技能包</button><button className="text-button" disabled={!!busy} onClick={()=>void run('正在打开…',async()=>{await api().marketOpen(audit.repo);})}><ExternalLink size={15}/>作者仓库</button></div></div></section>
 :repository?<section><div className="market-repository-heading"><h3>{repository.repo.name}</h3><p>{repository.repo.description}</p><span>{repository.repo.stars.toLocaleString()} Stars · {repository.skills.length} 个 Skills · {repository.repo.license}</span></div><label className="toolbox-search"><Search size={16}/><input aria-label="筛选仓库技能" placeholder="在这个仓库中筛选技能名称" value={filter} onChange={e=>setFilter(e.target.value)}/></label>{!repository.skills.length&&<div className="toolbox-empty">没有找到 SKILL.md。此仓库可能是插件、MCP 服务或工具，需要按作者说明配置。</div>}<div className="market-skill-list">{repository.skills.filter(s=>`${s.name} ${s.path}`.toLowerCase().includes(filter.toLowerCase())).slice(0,200).map(s=><article key={s.path}><div><h3>{s.name}</h3><p>{s.path||'仓库根目录'}</p></div><button className="secondary" disabled={!!busy} onClick={()=>void run('下载固定版本并逐文件检查…',async()=>{const review=await api().skillAudit(repository.repo.name,repository.commit,s.path);setAudit(review);setAccepted(false);setFile('SKILL.md');})}><ShieldCheck size={16}/>查看并审查</button></article>)}</div><p className="form-hint">最多显示 200 项，可使用筛选缩小范围。Skills 的用途、脚本和依赖需在下一步原文中核对。</p></section>
 :<><form className="toolbox-controls" onSubmit={e=>{e.preventDefault();void search();}}><label className="toolbox-search"><Search size={16}/><input aria-label="GitHub 搜索" value={query} maxLength={160} onChange={e=>setQuery(e.target.value)} placeholder="搜索用途关键词，或粘贴 owner/repo"/></label><select aria-label="GitHub 排序" value={sort} onChange={e=>setSort(e.target.value as typeof sort)}><option value="relevance">相关度优先</option><option value="updated">最近更新</option><option value="stars">最多 Stars</option></select><button className="primary" type="submit" disabled={!!busy}><Search size={16}/>搜索 GitHub</button></form><div className="market-topics">{[['前端设计','frontend design skills'],['代码审查','code review agent skills'],['测试与调试','testing agent skills'],['文档办公','document skills'],['OpenAI Skills','openai/skills'],['Anthropic Skills','anthropics/skills']].map(([name,q])=><button key={name} disabled={!!busy} onClick={()=>{setQuery(q);void search(1,q);}}>{name}</button>)}</div><p className="usage-scope">搜索公开 GitHub 仓库，支持 GitHub 查询语法；相关度不等于质量，Stars 不等于安全。相同搜索缓存 5 分钟；不读取 GitHub 凭据，限流时会提示。</p>{!searched?<div className="market-welcome"><Search size={30}/><h3>从你要完成的工作开始</h3><p>搜索设计、测试、写作或数据分析，也可以直接打开已知的作者仓库。</p><ol><li>发现仓库与技能</li><li>核对版本和原文</li><li>选择客户端并安装</li></ol></div>:<><p className="result-count">第 {page} 页 · 最多展示前 {total} 个结果</p>{!repos.length&&<div className="toolbox-empty">没有找到匹配仓库。试试英文关键词，或直接输入 owner/repo。</div>}<div className="market-results">{repos.map(repo=><article key={repo.name}><div className="market-repo-title"><h3>{repo.name}</h3><span>★ {repo.stars.toLocaleString()}</span></div><p>{repo.description}</p><div className="market-repo-meta"><span>更新 {repo.updated.slice(0,10)} · {repo.license}</span><button className="secondary" disabled={!!busy} onClick={()=>void run('正在发现 Skills…',()=>discover(repo.name))}>发现 Skills</button></div></article>)}</div><div className="source-actions market-pagination"><button disabled={!!busy||page<=1} onClick={()=>void search(page-1)}>上一页</button><span>{page} / {Math.max(1,Math.ceil(total/12))}</span><button disabled={!!busy||page*12>=total} onClick={()=>void search(page+1)}>下一页</button></div></> }</>}
 </div>;
}
