import {useEffect,useRef,useState,type ReactNode} from 'react';
import {Orbit,Command,Palette,SlidersHorizontal,ZoomIn,ZoomOut,RotateCcw,Maximize2} from 'lucide-react';
import type {ExperiencePrefs,SpaceNode} from '../shared';
export const SPACE_NODES=[{id:'control',name:'主控台',note:'为今晚安排一个终点',Icon:Orbit},{id:'agent',name:'Agent 工作台',note:'用量、工具与夜间协作',Icon:Command},{id:'workshop',name:'美化工坊',note:'把喜欢的风格带进工作',Icon:Palette},{id:'system',name:'系统维护',note:'检查配置，掌握运行状态',Icon:SlidersHorizontal}] as const;
export function SpaceNavigation({node,onNode}:{node:SpaceNode;onNode:(node:SpaceNode)=>void}){return <nav className="space-navigation" aria-label="空间导航">{SPACE_NODES.map(({id,name,Icon})=><button key={id} aria-current={node===id?'page':undefined} onClick={()=>onNode(id)}><Icon size={19}/><span>{name}</span></button>)}</nav>;}
export function SpaceFrame({node,prefs,immersive,zoom,onZoom,onSave,status,onRetry,concealed,onShowScene,children}:{concealed?:boolean;onShowScene:()=>void;node:SpaceNode;prefs:ExperiencePrefs;immersive:boolean;zoom:number;onZoom:(n:number)=>void;onSave:(size:{width:number;height:number})=>void;status:string;onRetry:()=>void;children:ReactNode}){
 const host=useRef<HTMLDivElement>(null),panel=useRef<HTMLDivElement>(null),drag=useRef<{x:number;y:number;w:number;h:number}|null>(null),latest=useRef(onSave);latest.current=onSave;
 const [size,setSize]=useState(prefs.panels?.[node]);
 useEffect(()=>setSize(prefs.panels?.[node]),[node,prefs.panels]);
 const clamp=(w:number,h:number)=>{const r=host.current!.getBoundingClientRect();return {width:Math.min(Math.max(420,w),Math.max(420,r.width)),height:Math.min(Math.max(240,h),Math.max(240,r.height))};};
 function preset(scale:number){const r=host.current!.getBoundingClientRect(),next=clamp(r.width*scale,r.height*scale);setSize(next);onSave(next);}
 const adjust=(n:number)=>onZoom(Math.max(.65,Math.min(1.5,n)));
 return <><div className="space-aisle" onWheel={e=>{if(immersive&&!document.querySelector('dialog[open]'))adjust(zoom-e.deltaY*.0005);}}><div className="space-destination"><span>{SPACE_NODES.find(n=>n.id===node)!.note}</span><small>{immersive?status:'经典界面 · 场景关闭'}</small></div>{immersive&&<div className="camera-controls" role="group" aria-label="镜头控制"><button className="icon-button" aria-label="镜头拉远" onClick={()=>adjust(zoom-.1)}><ZoomOut size={16}/></button><span>{Math.round(zoom*100)}%</span><button className="icon-button" aria-label="镜头拉近" onClick={()=>adjust(zoom+.1)}><ZoomIn size={16}/></button><button className="icon-button" aria-label="镜头复位" onClick={()=>onZoom(1)}><RotateCcw size={16}/></button><button className="secondary scene-view-button" onClick={onShowScene}>星际观景</button><button className="text-button" onClick={onRetry}>重新启用动效</button></div>}</div>
 <div ref={host} className="flight-area" inert={concealed} aria-hidden={concealed||undefined}><div ref={panel} className="flight-panel" style={size?{width:size.width,height:size.height}:undefined}>
  <div className="panel-sizing"><span>{SPACE_NODES.find(n=>n.id===node)!.name}</span><div role="group" aria-label="功能面板尺寸"><button onClick={()=>preset(.78)}>紧凑</button><button onClick={()=>preset(.92)}>标准</button><button onClick={()=>preset(1)}>展开 <Maximize2 size={12}/></button></div></div>
  <div className="flight-content">{children}</div><button className="panel-resize" aria-label="拖动调整面板尺寸；方向键调整" onPointerDown={e=>{const r=panel.current!.getBoundingClientRect();drag.current={x:e.clientX,y:e.clientY,w:r.width,h:r.height};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(drag.current)setSize(clamp(drag.current.w+e.clientX-drag.current.x,drag.current.h+e.clientY-drag.current.y));}} onPointerUp={e=>{if(!drag.current)return;const next=clamp(drag.current.w+e.clientX-drag.current.x,drag.current.h+e.clientY-drag.current.y);drag.current=null;setSize(next);onSave(next);}} onPointerCancel={()=>{drag.current=null;setSize(prefs.panels?.[node]);}} onKeyDown={e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const r=panel.current!.getBoundingClientRect(),next=clamp(r.width+(e.key==='ArrowLeft'?-24:e.key==='ArrowRight'?24:0),r.height+(e.key==='ArrowUp'?-24:e.key==='ArrowDown'?24:0));setSize(next);}} onKeyUp={e=>{if(e.key.startsWith('Arrow')&&size)onSave(size);}}><Maximize2 size={13}/></button>
 </div></div></>;
}
