import {useEffect,useState} from 'react';
import {ArrowRight,Upload,Download,Check,Palette,Sparkles} from 'lucide-react';
import type {ThemeItem,WallpaperItem} from '../integration-types';
import {studioDraft,STUDIO_PALETTES,contrastRatio,type StudioDraft} from '../theme-studio';
const targets={codex:'Codex · 原生配色','codex-image':'Codex · 图片主题 ZIP',claude:'Claude · Theme Mod',deepseek:'DeepSeek · Dream Skin'};
export function ThemeStudio({onLibrary}:{onLibrary:()=>void}){
 const api=window.starSleep!,[draft,setDraft]=useState(studioDraft),[images,setImages]=useState<WallpaperItem[]>([]),[image,setImage]=useState(''),[saved,setSaved]=useState<ThemeItem|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const update=(next:Partial<StudioDraft>)=>{setDraft(d=>({...d,...next}));setSaved(null);setMessage('');};
 async function load(){const s=await api.wallpaperList();setImages(s.items);if(s.error)setMessage(s.error);}
 useEffect(()=>{void load().catch(e=>setMessage(String(e)));},[]);
 useEffect(()=>{let live=true;setImage('');if(draft.target==='codex-image'&&draft.wallpaperId)void api.wallpaperPreview(draft.wallpaperId).then(s=>{if(live)setImage(s);}).catch(e=>{if(live)setMessage(String(e));});return()=>{live=false;};},[draft.wallpaperId,draft.target]);
 const contrast=contrastRatio(draft.surface,draft.ink),valid=draft.name.trim()&&Number.isFinite(contrast)&&contrast>=4.5&&(draft.target!=='codex-image'||draft.wallpaperId);
 async function save(){if(busy||!valid)return;setBusy(true);try{const item=await api.themeCreate(draft);setSaved(item);setMessage('已保存到我的主题。客户端外观尚未改变。');}catch(e){setMessage(String(e).replace(/^Error: /,''));}finally{setBusy(false);}}
 return <section className="theme-studio" aria-label="主题创作"><div className="studio-layout"><form className="studio-form" onSubmit={e=>{e.preventDefault();void save();}}><h2>你的配色，你的工作空间。</h2><p className="muted">从一组配色开始，调整细节，再把它带进 Agent。</p><label className="field">主题名称<input aria-label="主题名称" maxLength={80} value={draft.name} onChange={e=>update({name:e.target.value})}/></label><label className="field">适用客户端<select aria-label="创作目标" value={draft.target} onChange={e=>update({target:e.target.value as StudioDraft['target']})}>{Object.entries(targets).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><div className="studio-presets" role="group" aria-label="起始配色">{STUDIO_PALETTES.map(p=><button type="button" key={p.name} onClick={()=>update({...p,name:'我的'+p.name})}><i style={{background:p.accent}}/>{p.name}</button>)}</div><div className="studio-colors">{([['surface','背景'],['panel','侧栏'],['ink','正文'],['accent','强调'],['muted','辅助文字'],['border','分隔线']] as const).map(([key,name])=><label key={key}><input type="color" aria-label={`${name}颜色`} value={draft[key]} onChange={e=>update({[key]:e.target.value})}/><span>{name}<small>{draft[key].toUpperCase()}</small></span></label>)}</div><label className="field">明暗模式<select value={draft.mode} aria-label="创作明暗模式" onChange={e=>update({mode:e.target.value as 'light'|'dark'})}><option value="light">浅色</option><option value="dark">深色</option></select></label><p className={contrast<4.5?'download-error':'muted'} role="status">正文对比度 {contrast.toFixed(1)} : 1 {contrast<4.5?'· 请调到至少 4.5 : 1 后保存':'· 可读性检查通过'}</p>
 {draft.target==='codex-image'&&<div className="studio-backgrounds"><div className="selection-bar"><strong>背景图片</strong><button type="button" className="text-button" disabled={busy} onClick={async()=>{setBusy(true);try{const id=await api.wallpaperImport();if(id){await load();update({wallpaperId:id});}}catch(e){setMessage(String(e));}finally{setBusy(false);}}}><Upload size={15}/>导入图片</button></div><div className="studio-images">{images.map(i=><button type="button" key={i.id} aria-pressed={draft.wallpaperId===i.id} aria-label={`选择背景 ${i.name}`} onClick={()=>update({wallpaperId:i.id})}><img src={i.thumbnail} alt=""/><span>{i.name}</span></button>)}</div><label className="field">图片横向焦点<input type="range" min="0" max="1" step="0.05" aria-label="图片横向焦点" value={draft.focusX} onChange={e=>update({focusX:Number(e.target.value)})}/></label></div>}
 <div className="studio-save"><button className="primary" disabled={busy||!valid||!!saved}>{saved?<Check size={17}/>:<Palette size={17}/>} {saved?'已保存':busy?'正在保存…':'保存到我的主题'}</button>{saved&&<button type="button" className="secondary" disabled={busy} onClick={async()=>{setBusy(true);try{if(await api.themeExport(saved.id))setMessage('主题已导出。图片 ZIP 请使用 Dream Skin 托盘的「导入主题 ZIP」。');}catch(e){setMessage(String(e));}finally{setBusy(false);}}}><Download size={16}/>导出美化包</button>}</div>{message&&<p className="toolbox-feedback" role="status">{message}</p>}{saved&&<button type="button" className="text-button" onClick={onLibrary}>到我的主题配置 <ArrowRight size={16}/></button>}</form>
 <div className="studio-preview-column"><div className="studio-preview" style={{background:draft.surface,color:draft.ink,...(image?{backgroundImage:`url("${image}")`,backgroundSize:'cover',backgroundPosition:`${draft.focusX*100}% ${draft.focusY*100}%`}:{})}}><aside style={{background:draft.panel+(image?'D9':''),borderColor:draft.border}}><Palette size={20}/><span>工作空间</span><b style={{color:draft.accent}}>新的灵感</b><span>项目计划</span><span>探索与创作</span><small>Agent workspace</small></aside><main><div className="studio-preview-welcome"><span style={{color:draft.accent}}><Sparkles size={30}/></span><h3>从一个想法开始。</h3><p>让常用的工具，也有你的风格。</p></div><div className="studio-preview-input" style={{background:draft.panel+(image?'ED':''),borderColor:draft.border}}>今天想完成什么？<ArrowRight size={23} style={{color:draft.accent}}/></div></main></div><p className="preview-caption">设计预览 · 示意布局，实际效果以客户端为准</p><div className="studio-guide"><h3>{draft.target==='codex-image'?'图片如何进入 Codex？':'保存之后，如何使用？'}</h3>{draft.target==='codex-image'?<ol><li>选择自己的图片与配色，保存并导出 ZIP。</li><li>准备与当前 Codex 兼容的 Dream Skin 加载器。</li><li>从 Dream Skin 托盘选择「导入主题 ZIP」，再切换主题。</li></ol>:<p>保存到「我的主题」，查看客户端检测结果，确认更改后应用。{draft.target==='codex'?'原生配色不需要图片加载器。':draft.target==='claude'?'需要已安装的 Claude Theme Mod。':'需要已启用的 DeepSeek Dream Skin 9.x；背景可在背景库单独配置。'}</p>}<p className="muted">{draft.target==='codex-image'?'ZIP 包只包含背景、主题配置和受限样式，不包含安装脚本。':'配色主题不包含背景图片。要为 Codex 制作图片主题，请切换创作目标。'}</p></div></div></div></section>;
}
