import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,BarChart3,BookOpen,FolderOpen,RefreshCw,Download,Star,ExternalLink,Copy,Search,Library} from 'lucide-react';
import {RESOURCES} from '../resources';
import {usageView} from '../usage-utils';
import {SkillMarketPanel} from './SkillMarket';
import type {LocalSkill,ResourceItem,ResourceMark,ToolboxState,UsageRange,UsageReport,UsageSource} from '../toolbox-types';

const api=()=>window.starSleep!;
const number=(n:number)=>new Intl.NumberFormat('zh-CN').format(n);
const sourceName={codex:'Codex',claude:'Claude Code'};
const categories={skills:'Skills',plugins:'插件',mcp:'MCP',tools:'工具'};
const messageOf=(e:unknown)=>String(e).replace(/^Error: (Error invoking remote method '[^']+': Error: )?/,'');
export function ToolboxPanel({visible,safe,onBack}:{visible:boolean;safe:boolean;onBack:()=>void}){
 const [tab,setTab]=useState<'usage'|'resources'|'local'|'market'>('usage'),[visited,setVisited]=useState<string[]>(['usage']);
 return <section className="toolbox-workspace" aria-label="Agent 工具箱"><div className="toolbox-heading"><div><h1>Agent 工具箱</h1><p>看清用量，找到工具，把常用能力留在手边。</p></div><button className="text-button" onClick={onBack}><ArrowLeft size={16}/>返回计划</button></div>
 <nav className="toolbox-tabs" aria-label="工具箱分类">{([['usage','用量看板',BarChart3],['market','发现与安装',Search],['resources','开源资源',BookOpen],['local','本机 Skills',Library]]as const).map(([id,name,Icon])=><button key={id} aria-pressed={tab===id} onClick={()=>{setTab(id);setVisited(v=>v.includes(id)?v:[...v,id]);}}><Icon size={17}/>{name}</button>)}</nav>
 <div className="toolbox-body"><div hidden={tab!=='usage'}><UsagePanel visible={visible&&tab==='usage'} safe={safe}/></div>{visited.includes('market')&&<div hidden={tab!=='market'}><SkillMarketPanel safe={safe}/></div>}{visited.includes('resources')&&<div hidden={tab!=='resources'}><ResourcePanel/></div>}{visited.includes('local')&&<div hidden={tab!=='local'}><SkillsPanel safe={safe}/></div>}</div></section>;
}
function UsagePanel({visible,safe}:{visible:boolean;safe:boolean}){
 const readId=useRef(0),mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;readId.current++;};},[]);
 const [report,setReport]=useState<UsageReport|null>(null),[config,setConfig]=useState<ToolboxState|null>(null),[range,setRange]=useState<UsageRange>(7),[source,setSource]=useState<UsageSource|'all'>('all'),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState('');
 useEffect(()=>{let live=true;void api().toolboxState().then(s=>{if(live)setConfig(s);}).catch(e=>{if(live)setFeedback(messageOf(e));});return()=>{live=false;};},[]);
 useEffect(()=>{if(!visible)return;void refresh(false);const timer=setInterval(()=>void refresh(false),300000);return()=>clearInterval(timer);},[visible]);
 async function refresh(force=true){if(busy)return;const id=++readId.current;setBusy(true);setFeedback('');try{const next=await api().usageRead(force);if(mounted.current&&id===readId.current)setReport(next);}catch(e){if(mounted.current&&id===readId.current)setFeedback(messageOf(e));}finally{if(mounted.current&&id===readId.current)setBusy(false);}}
 async function location(s:UsageSource,reset=false){if(busy)return;setBusy(true);setFeedback('');try{const next=await(reset?api().usageReset(s):api().usageSelect(s));if(next){setConfig(next);setReport(await api().usageRead());}}catch(e){setFeedback(messageOf(e));}finally{setBusy(false);}}
 const available=report?.sources.some(s=>(source==='all'||s.source===source)&&['ready','empty'].includes(s.status));
 const view=usageView(report?.days??[],range,source),max=Math.max(1,...view.chart.map(d=>d.total));
 return <div className="usage-panel"><div className="toolbox-controls"><div className="range-buttons" role="group" aria-label="统计范围">{([1,7,30]as const).map(n=><button aria-pressed={range===n} key={n} onClick={()=>setRange(n)}>{n===1?'今天':`近 ${n} 天`}</button>)}</div><label>来源 <select aria-label="用量来源" value={source} onChange={e=>setSource(e.target.value as UsageSource|'all')}><option value="all">全部已接入来源</option><option value="codex">Codex</option><option value="claude">Claude Code</option></select></label><button className="secondary" onClick={()=>void refresh()} disabled={busy}><RefreshCw size={15}/>{busy?'正在读取…':'刷新'}</button><button className="text-button" disabled={busy||!report} onClick={()=>{setBusy(true);void api().usageExport(range,source).then(done=>{if(done)setFeedback('用量摘要已导出，不包含对话或本机路径。');}).catch(e=>setFeedback(messageOf(e))).finally(()=>setBusy(false));}}><Download size={15}/>导出摘要</button></div>
 {feedback&&<p role="status" className="toolbox-feedback">{feedback}</p>}{config?.error&&<p role="alert" className="toolbox-feedback">{config.error}</p>}
 <p className="usage-scope">{safe?'安全体验：默认读取隔离目录，可手动选择真实日志目录进行只读统计。':'只读本机日志，不上传对话。'}统计近 30 天；此页可见时每 5 分钟刷新，隐藏后停止新扫描。</p>
 <div className="usage-summary"><div><span>已读取来源合计</span><strong data-testid="usage-total">{available?number(view.totals.total):'—'}</strong></div><div><span>未缓存输入</span><strong>{available?number(view.totals.input):'—'}</strong></div><div><span>输出</span><strong>{available?number(view.totals.output):'—'}</strong></div><div><span>缓存读取</span><strong>{available?number(view.totals.cacheRead):'—'}</strong></div><div><span>缓存写入</span><strong>{available?number(view.totals.cacheWrite):'—'}</strong></div></div>
 <p className="form-hint">合计包含输入、输出和缓存；推理已包含在输出中。这里只汇总可读取记录，不是剩余额度或订阅账单。</p>
 <div className="usage-insights"><span>日均已记录用量 <strong>{available?number(Math.round(view.totals.total/range)):'—'}</strong></span><span>缓存读取占输入 <strong>{available&&view.inputTotal>0?(view.totals.cacheRead/view.inputTotal*100).toFixed(1)+'%':'—'}</strong></span><span>有记录 <strong>{view.daily.length} / {range} 天</strong></span></div>
 {report&&report.sources.some(s=>(source==='all'||s.source===source)&&['error','missing'].includes(s.status))&&<p className="toolbox-feedback" role="status">部分来源未读到数据，合计仅包含已读取记录。请检查下方数据来源。</p>}
 {view.daily.length>0&&<details className="usage-daily"><summary>每日用量明细 · {view.daily.length} 天</summary><div className="usage-table-scroll"><table className="usage-table"><caption>按当前来源合并；未缓存输入、缓存读取及缓存写入之和用于计算输入占比。缺失日志不代表没有使用。</caption><thead><tr>{['日期','未缓存输入','输出','缓存读取','缓存写入','合计'].map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{view.daily.map(d=><tr key={d.date}><td>{d.date}</td>{(['input','output','cacheRead','cacheWrite','total']as const).map(k=><td key={k}>{number(d[k])}</td>)}</tr>)}</tbody></table></div></details>}
 {report&&!view.filtered.length?<div className="toolbox-empty"><BarChart3 size={28}/><h2>这个范围还没有可统计记录</h2><p>先检查下方数据来源，再尝试选择日志目录或扩大日期范围。</p></div>:<div className="usage-chart" aria-label="每日 Token 用量"><div className="chart-bars">{view.chart.map(d=><div className="chart-column" key={d.date} title={`${d.date}：${number(d.total)} Token`}><div style={{height:`${d.total/max*100}%`}}/><span className="sr-only">{d.date}：{number(d.total)}</span></div>)}</div><div className="chart-caption"><span>{view.from}</span><span>每日用量 · 峰值 {number(max===1&&view.totals.total===0?0:max)}</span><span>{view.until}</span></div></div>}
 <div className="usage-detail-grid"><section><h2>模型分布</h2>{view.models.length?<table className="usage-table"><thead><tr><th>模型 / 来源</th><th>Token</th></tr></thead><tbody>{view.models.slice(0,30).map(([name,t])=><tr key={name}><td>{name}</td><td>{number(t.total)}</td></tr>)}</tbody></table>:<p className="muted">有记录后显示模型分布。</p>}{view.models.length>30&&<p className="form-hint">显示前 30 项，完整数据可导出。</p>}</section><section className="usage-sources"><h2>数据来源</h2>{(['codex','claude']as const).map(s=>{const status=report?.sources.find(v=>v.source===s);return <div className="usage-source" key={s}><div><strong>{sourceName[s]}</strong><span className={`source-state ${status?.status==='ready'?'ready':''}`}>{!status?'等待读取':{ready:'已读取',empty:'暂无记录',missing:'未找到日志',error:'读取失败'}[status.status]}</span></div><p>{status?.detail||'正在检查数据目录…'}</p><details><summary>目录与配置</summary><p className="path-text">{status?.path||config?.paths[s]}</p><div className="source-actions"><button className="secondary" disabled={busy||!!config?.error} onClick={()=>void location(s)}><FolderOpen size={14}/>选择目录</button><button className="text-button" disabled={busy||!!config?.error} onClick={()=>void location(s,true)}>恢复默认</button></div></details></div>;})}<div className="usage-source"><strong>DeepSeek Harness / Claude Chat</strong><p>本版没有接入其用量格式。请在对应客户端查看，不计入上方合计。</p></div></section></div>
 <p className="toolbox-provenance"><button className="text-button" onClick={()=>void api().resourceOpen('ccusage').catch(e=>setFeedback(messageOf(e)))}>统计引擎：ccusage 20.0.24 · MIT <ExternalLink size={12}/></button><span>{report?`更新于 ${new Date(report.generatedAt).toLocaleTimeString('zh-CN',{hour12:false})}`:'正在建立第一份摘要'}</span></p></div>;
}
function ResourcePanel(){
 const [state,setState]=useState<ToolboxState|null>(null),[query,setQuery]=useState(''),[category,setCategory]=useState('all'),[client,setClient]=useState('all'),[favorites,setFavorites]=useState(false),[selected,setSelected]=useState('ccusage'),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState('');
 useEffect(()=>{let live=true;void api().toolboxState().then(v=>{if(live)setState(v);}).catch(e=>{if(live)setFeedback(messageOf(e));});return()=>{live=false;};},[]);
 const filtered=RESOURCES.filter(r=>(category==='all'||r.category===category)&&(client==='all'||r.clients.includes(client))&&(!favorites||state?.marks[r.id]?.favorite)&&`${r.name} ${r.summary} ${r.useCase} ${state?.marks[r.id]?.note||''}`.toLowerCase().includes(query.toLowerCase()));
 const current=filtered.find(r=>r.id===selected)||filtered[0];
 async function mark(id:string,value:ResourceMark){if(busy)return;setBusy(true);try{setState(await api().resourceMark(id,value));setFeedback('已保存在本机');}catch(e){setFeedback(messageOf(e));}finally{setBusy(false);}}
 return <div className="resource-panel"><div className="toolbox-controls"><label className="toolbox-search"><Search size={16}/><input aria-label="搜索开源资源" placeholder="搜索用途、名称或个人备注" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="资源类别" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">所有类别</option>{Object.entries(categories).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select aria-label="适用 Agent" value={client} onChange={e=>setClient(e.target.value)}><option value="all">所有客户端</option>{['Codex','Claude Code','Claude','DeepSeek Harness'].map(c=><option key={c}>{c}</option>)}</select><button className="secondary" aria-pressed={favorites} onClick={()=>setFavorites(!favorites)}><Star size={15}/>只看收藏</button></div>
 <p className="usage-scope">按实际用途整理的作者仓库入口，核对日期 2026-09-22。收藏不会安装；适配和许可以原项目当前说明为准。</p>{(feedback||state?.error)&&<p role="status" className="toolbox-feedback">{state?.error||feedback}</p>}
 <div className="resource-layout"><div className="resource-list" aria-label="开源资源列表"><span className="result-count">{filtered.length} 个项目</span>{filtered.map(r=><button className="resource-row" key={r.id} aria-pressed={current?.id===r.id} onClick={()=>setSelected(r.id)}><div><strong>{r.name}</strong>{state?.marks[r.id]?.favorite&&<Star size={14} aria-label="已收藏"/>}</div><p>{r.summary}</p><span>{categories[r.category]} · {r.clients.join(' / ')}</span></button>)}</div>{current?<ResourceDetail key={current.id} item={current} mark={state?.marks[current.id]||{favorite:false,note:''}} disabled={busy||!state||!!state.error} onMark={m=>void mark(current.id,m)} onMessage={setFeedback}/>:<div className="toolbox-empty"><Search size={28}/><h2>没有匹配的资源</h2><p>换一个用途关键词，或取消筛选。</p></div>}</div></div>;
}
function ResourceDetail({item,mark,disabled,onMark,onMessage}:{item:ResourceItem;mark:ResourceMark;disabled:boolean;onMark:(mark:ResourceMark)=>void;onMessage:(text:string)=>void}){
 const [note,setNote]=useState(mark.note);useEffect(()=>setNote(mark.note),[mark.note]);
 return <article className="resource-detail"><div className="resource-title"><h2>{item.name}</h2><button className="secondary" disabled={disabled} aria-pressed={mark.favorite} onClick={()=>onMark({...mark,note,favorite:!mark.favorite})}><Star size={16}/>{mark.favorite?'已收藏':'收藏'}</button></div><p className="muted">{item.owner} · {item.license}</p><h3>适合什么场景</h3><p>{item.useCase}</p><h3>如何使用</h3><p>{item.setup}</p><p className="resource-clients">适用：{item.clients.join(' / ')}</p><div className="source-actions"><button className="primary" onClick={()=>void api().resourceOpen(item.id).catch(e=>onMessage(messageOf(e)))}><ExternalLink size={16}/>打开作者仓库</button><button className="secondary" onClick={()=>void api().resourceCopy(item.id).then(()=>onMessage('项目链接和使用说明已复制')).catch(e=>onMessage(messageOf(e)))}><Copy size={15}/>复制说明</button></div><label className="field resource-note">我的备注<textarea aria-label="资源备注" maxLength={300} value={note} onChange={e=>setNote(e.target.value)} placeholder="记下适用项目、使用感受或稍后要试的功能"/><span className="notes-count">{note.length} / 300 · 只保存在本机</span></label><button className="secondary" disabled={disabled||note===mark.note} onClick={()=>onMark({...mark,note})}>保存备注</button></article>;
}
function SkillsPanel({safe}:{safe:boolean}){
 const [items,setItems]=useState<LocalSkill[]>([]),[query,setQuery]=useState(''),[warnings,setWarnings]=useState<string[]>([]),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
 async function refresh(){if(busy)return;setBusy(true);try{const result=await api().localSkills();setItems(result.items);setWarnings(result.warnings);setLoaded(true);}catch(e){setWarnings([messageOf(e)]);}finally{setBusy(false);}}
 useEffect(()=>{void refresh();},[]);
 const filtered=items.filter(s=>`${s.name} ${s.description} ${s.client}`.toLowerCase().includes(query.toLowerCase()));
 return <div className="skills-panel"><div className="toolbox-controls"><label className="toolbox-search"><Search size={16}/><input aria-label="搜索本机技能" placeholder="搜索技能名称、简介或客户端" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="secondary" disabled={busy} onClick={()=>void refresh()}><RefreshCw size={15}/>{busy?'正在扫描…':'刷新清单'}</button><span>{filtered.length} 个技能文件</span></div><p className="usage-scope">{safe?'安全体验读取隔离技能目录。':'扫描当前用户的 .codex/skills、.agents/skills 与 .claude/skills。'}这里只表示文件存在，不代表客户端已启用；同时包含“发现与安装”配置的目标目录；插件缓存及项目级目录不在扫描范围。</p>{warnings.map(w=><p key={w} role="status" className="toolbox-feedback">{w}</p>)}{loaded&&!filtered.length?<div className="toolbox-empty"><Library size={28}/><h2>{items.length?'没有匹配的技能':'还没有找到本机技能'}</h2><p>可以在“发现与安装”搜索并安装技能，然后刷新清单。</p></div>:<div className="local-skill-list">{filtered.slice(0,200).map(s=><article className="local-skill" key={s.id}><div><h2>{s.name}</h2><span>{s.client}</span></div><p>{s.description}</p><button className="text-button" onClick={()=>void api().skillReveal(s.id).catch(e=>setWarnings([messageOf(e)]))}><FolderOpen size={15}/>打开所在目录</button></article>)}</div>}{filtered.length>200&&<p className="form-hint">显示前 200 项，请用搜索缩小范围。</p>}</div>;
}
