import {useEffect,useRef,useState} from 'react';
import {ArrowDownToLine,ArrowUpRight,Heart,RefreshCw,X,Check,ShieldCheck} from 'lucide-react';
import type {CommunityTheme,WorkshopState,HealthReport} from '../workshop-types';
import type {IntegrationSnapshot} from '../integration-types';
import {IntegrationsPanel} from './Integrations';
import {ThemeStudio} from './ThemeStudio';
import {ThemeCover} from './ThemeCover';
import {Modal} from './UI';
const clients={codex:'Codex',claude:'Claude Desktop',deepseek:'DeepSeek Harness'};
const formats={'codex-native':'原生主题','claude-json':'Claude JSON','dsh-dreamskin':'DSH 主题包','dreamskin-zip':'Dream Skin ZIP','custom-css':'CSS','dsh-appearance':'DSH 配色'};
const empty:WorkshopState={favorites:[],tasks:[],themes:{}};
const message=(e:unknown)=>String(e).replace(/^Error: (Error invoking remote method '[^']+': Error: )?/,'');
export function WorkshopPanel({safe,paused,visible}:{safe:boolean;paused:boolean;visible:boolean}){
 const api=window.starSleep!;
 const [tab,setTab]=useState('community'),[catalog,setCatalog]=useState<CommunityTheme[]>([]),[state,setState]=useState(empty),[integration,setIntegration]=useState<IntegrationSnapshot|null>(null),[error,setError]=useState('');
 const [client,setClient]=useState('all'),[style,setStyle]=useState('all'),[format,setFormat]=useState('all'),[availability,setAvailability]=useState('all'),[favorite,setFavorite]=useState(false),[selected,setSelected]=useState<CommunityTheme|null>(null);
 useEffect(()=>{let live=true;void Promise.all([api.workshopCatalog(),api.workshopState(),api.integrations()]).then(([c,s,i])=>{if(live){setCatalog(c);setState(s);setIntegration(i);}}).catch(e=>setError(message(e)));const off=api.workshopChanged(setState),off2=api.integrationChanged(setIntegration);return()=>{live=false;off();off2();};},[]);
 useEffect(()=>{if(visible)void api.themeClients().then(setIntegration).catch(e=>setError(message(e)));},[visible]);
 async function run(fn:()=>Promise<unknown>){setError('');try{await fn();}catch(e){setError(message(e));}}
 const downloaded=(r:CommunityTheme)=>Object.entries(state.themes).some(([id,m])=>m.resourceId===r.id&&integration?.themes.some(t=>t.id===id));
 const applicable=(r:CommunityTheme)=>!!integration?.clients?.[r.client]?.ready&&['codex-native','claude-json','dsh-dreamskin'].includes(r.format);
 const status=(r:CommunityTheme)=>!r.download?'作者社区入口':downloaded(r)?'已下载':applicable(r)?'可配置':'缺少兼容客户端或加载器';
 const filtered=catalog.filter(r=>(client==='all'||r.client===client)&&(style==='all'||r.style===style)&&(format==='all'||r.format===format)&&(!favorite||state.favorites.includes(r.id))&&(availability==='all'||(availability==='ready'?applicable(r):availability==='downloaded'?downloaded(r):!applicable(r))));
 return <section className={`workshop-panel tab-${tab}`} aria-label="社区美化工坊" onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect='copy';}} onDrop={e=>{e.preventDefault();const files=Array.from(e.dataTransfer.files);if(files.length!==1){setError('一次拖入一个美化文件');return;}void run(async()=>{await api.themeDrop(files[0]);setTab('mine');setError(/\.(png|jpe?g|webp)$/i.test(files[0].name)?'图片已加入 DeepSeek 背景页':'文件已加入主题库，尚未配置客户端');});}}>
  <div className="workshop-heading"><div><h1>社区美化工坊</h1><p>来自创作者的配色与材质，在你熟悉的 Agent 里使用。</p></div><span className="workshop-counter">{catalog.length} 个社区资源</span></div>
  <nav className="workshop-tabs" aria-label="工坊分类">{[['community','社区精选'],['create','主题创作'],['mine','我的主题'],['clients','客户端配置']].map(([id,name])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{name}</button>)}</nav>
  {(error||state.error)&&<p role="status" className="toolbox-feedback">{error||state.error}</p>}
  <div hidden={tab!=='community'} className="community-content">
   <div className="workshop-filters"><label>客户端<select aria-label="精选客户端" value={client} onChange={e=>setClient(e.target.value)}><option value="all">全部客户端</option>{Object.entries(clients).map(([k,n])=><option key={k} value={k}>{n}</option>)}</select></label><label>明暗<select value={style} onChange={e=>setStyle(e.target.value)}><option value="all">全部风格</option><option value="light">浅色</option><option value="dark">深色</option></select></label><label>格式<select value={format} onChange={e=>setFormat(e.target.value)}><option value="all">全部格式</option>{Object.entries(formats).map(([k,n])=><option key={k} value={k}>{n}</option>)}</select></label><label>状态<select value={availability} onChange={e=>setAvailability(e.target.value)}><option value="all">全部状态</option><option value="ready">可配置</option><option value="downloaded">已下载</option><option value="missing">需准备加载器</option></select></label><button className="text-button" aria-pressed={favorite} onClick={()=>setFavorite(v=>!v)}><Heart size={15}/>收藏</button></div>
   <div className="community-grid">{filtered.map(r=>{const task=state.tasks.find(t=>t.resourceId===r.id);return <article className="community-card" key={r.id}>
    <ThemeCover theme={r} onClick={()=>setSelected(r)}/>
    <div className="community-card-body"><div className="community-card-title"><button className="text-button" onClick={()=>setSelected(r)}><h2>{r.name}</h2></button><button className="icon-button" aria-label={`收藏 ${r.name}`} aria-pressed={state.favorites.includes(r.id)} onClick={()=>void run(()=>api.workshopFavorite(r.id,!state.favorites.includes(r.id)))}><Heart size={17} fill={state.favorites.includes(r.id)?'currentColor':'none'}/></button></div><p>{r.author} · {clients[r.client]}</p><p>{formats[r.format]} · {r.version.slice(0,8)}</p><p className="loader-note">{r.loader}</p><div className="community-actions"><span>{status(r)}</span>{task?.status==='downloading'?<button className="text-button" onClick={()=>void run(()=>api.workshopCancel(task.id))}><X size={14}/>取消下载</button>:r.download?<button className="secondary" disabled={downloaded(r)||!!state.error} onClick={()=>void run(()=>api.workshopDownload(r.id))}>{downloaded(r)?<Check size={15}/>:<ArrowDownToLine size={15}/>} {downloaded(r)?'已下载':task?.status==='failed'||task?.status==='cancelled'?'重试下载':'下载到主题库'}</button>:<button className="secondary" onClick={()=>void run(()=>api.workshopOpen(r.id))}>作者入口 <ArrowUpRight size={15}/></button>}</div>{task?.status==='downloading'&&<><progress max={task.total||undefined} value={task.total?task.received:undefined}/><small role="status">已接收 {Math.round(task.received/1024)} KB</small></>}{task?.error&&<p role="status" className="download-error">{task.error}</p>}</div>
   </article>;})}</div>{!filtered.length&&<p className="empty">没有符合这些条件的主题，试试其他筛选。</p>}
   <p className="workshop-footnote">目录可离线浏览 · 下载不会修改客户端 · 也可拖入 JSON、.codex-theme-v1、CSS、Dream Skin ZIP 或图片</p>
  </div>
  <div hidden={tab!=='create'}><ThemeStudio onLibrary={()=>setTab('mine')}/></div>
  <div hidden={tab!=='mine'}><IntegrationsPanel safe={safe} paused={paused} onBack={()=>setTab('community')} section="theme" active={visible&&tab==='mine'}/></div>
  <div hidden={tab!=='clients'}><HealthPanel visible={visible&&tab==='clients'} onConfigure={()=>setTab('mine')}/></div>
  {selected&&<Modal title={selected.name} onClose={()=>setSelected(null)} wide><p>{selected.description}</p><dl className="resource-meta"><dt>作者</dt><dd>{selected.author}</dd><dt>适用客户端</dt><dd>{clients[selected.client]}</dd><dt>加载方式</dt><dd>{selected.loader}</dd><dt>固定版本</dt><dd>{selected.version}</dd><dt>核验日期</dt><dd>{selected.checked}</dd><dt>许可证</dt><dd>{selected.license}</dd></dl><p className="muted">{selected.source}</p>{selected.licenseText&&<details><summary>查看完整许可与署名</summary><pre className="theme-license">{selected.licenseText}</pre></details>}<p className="muted">卡片为配色艺术封面或星枢背景示意，并非客户端实测截图。原作者效果请通过原始项目查看。</p><button className="secondary" onClick={()=>void run(()=>api.workshopOpen(selected.id))}>查看作者原始项目 <ArrowUpRight size={15}/></button></Modal>}
 </section>;
}

export function HealthPanel({visible,onConfigure,onSettings,onLogs}:{visible:boolean;onConfigure:()=>void;onSettings?:()=>void;onLogs?:()=>void}){
 const api=window.starSleep!;const [report,setReport]=useState<HealthReport|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[attention,setAttention]=useState(false);
 const pending=useRef(false),mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 async function refresh(){if(pending.current)return;pending.current=true;setBusy(true);setError('');try{const next=await api.clientHealth();if(mounted.current)setReport(next);}catch(e){if(mounted.current)setError(message(e));}finally{pending.current=false;if(mounted.current)setBusy(false);}}
 useEffect(()=>{if(visible&&!report)void refresh();},[visible]);
 const issues=report?.items.filter(i=>i.status!=='ok')??[],items=attention?issues:report?.items??[];
 return <section className="health-panel" aria-busy={busy}><div className="workshop-heading"><div><h1>{onSettings?'系统维护':'客户端配置体检'}</h1><p>只检查配置与安装文件，不读取对话、令牌或密钥。</p></div><ShieldCheck size={30}/></div><div className="health-actions"><button className="secondary" disabled={busy} onClick={()=>void refresh()}><RefreshCw size={16}/>{busy?'正在检查…':'重新体检'}</button><button className="secondary" disabled={busy||!report} onClick={()=>{if(pending.current)return;pending.current=true;setBusy(true);setError('');void api.exportHealth().then(done=>{if(done&&mounted.current)setError('脱敏报告已导出，包含完整体检项。');}).catch(e=>{if(mounted.current)setError(message(e));}).finally(()=>{pending.current=false;if(mounted.current)setBusy(false);});}}>导出脱敏报告</button><button className="text-button" onClick={onConfigure}>前往主题配置</button>{onSettings&&<button className="text-button" onClick={onSettings}>设置与数据管理</button>}{onLogs&&<button className="text-button" onClick={onLogs}>查看执行记录</button>}</div>{error&&<p className="toolbox-feedback" role="status">{error}</p>}
 {report&&<><div className="health-summary"><span>{report.items.length-issues.length} 项就绪 · {issues.length} 项需核对</span><button className="secondary" aria-pressed={attention} onClick={()=>setAttention(v=>!v)}>只看待处理项</button></div><p className="muted">{report.safe?'隔离客户端验证 · 真实配置未改变':'本机客户端检测'} · {new Date(report.at).toLocaleString()}</p><div className="health-clients">{report.clients&&Object.values(report.clients).map(c=><div key={c.label}><h2>{c.label}</h2><p>{c.detail}</p><p className="path-text">目标：{c.configPath||'尚未选择'}</p></div>)}</div><div className="health-list">{items.map((item,index)=><div key={index} className="health-row"><span className={'health-badge '+item.status}>{item.status==='ok'?'就绪':'需核对'}</span><div><h3>{item.name}</h3><p>{item.detail}</p><small>{item.next}</small></div></div>)}</div>{attention&&!issues.length&&<p className="toolbox-empty" role="status">本次检查没有待处理项。客户端实际效果仍以客户端中查看为准。</p>}</>}
 </section>;
}
