const {_electron:electron}=require('playwright');
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{createHash}=require('node:crypto');
const root=path.resolve(__dirname,'..'),out=path.join(root,'artifacts/v17'),data=path.join(root,'.qa-data','market-'+Date.now());fs.mkdirSync(out,{recursive:true});
const commit='a'.repeat(40),md='---\nname: work-review\ndescription: Review a project with a clear, practical checklist.\n---\n# Review the work\nCheck readability, testing and documentation.\nSee https://github.com/sample/skills for details.';
const files={'skills/work-review/SKILL.md':md,'skills/work-review/references/checklist.md':'# Checklist\nReview the change and report clear findings.','LICENSE':'MIT License\nCopyright (c) QA fixture'};
const tree=Object.entries(files).map(([name,text])=>({path:name,type:'blob',mode:'100644',size:Buffer.byteLength(text),sha:createHash('sha1').update(`blob ${Buffer.byteLength(text)}\0${text}`).digest('hex')}));
const env={...process.env,STARSLEEP_QA_DATA:data};delete env.ELECTRON_RUN_AS_NODE;let app,p;const results=[],errors=[];
async function check(name,fn){await fn();results.push(name);console.log('PASS',name);}
async function shot(name){const b64=await app.evaluate(async({BrowserWindow})=>(await BrowserWindow.getAllWindows()[0].capturePage()).toPNG().toString('base64'));fs.writeFileSync(path.join(out,name+'.png'),Buffer.from(b64,'base64'));}
async function launch(){app=await electron.launch({...(process.env.STARSLEEP_QA_EXE?{executablePath:process.env.STARSLEEP_QA_EXE}:{}),args:[...(process.env.STARSLEEP_QA_EXE?[]:[root]),'--safe-mode'],env,timeout:60000});p=await app.firstWindow();p.setDefaultTimeout(20000);p.on('pageerror',e=>errors.push(e.message));await p.getByRole('button',{name:'Agent 工具箱',exact:true}).waitFor();await p.evaluate(async()=>{const s=await window.starSleep.snapshot();await window.starSleep.settings({...s.settings,sound:false,volume:0,reducedMotion:true});});await p.getByRole('button',{name:'Agent 工具箱',exact:true}).click();await p.getByRole('button',{name:'发现与安装',exact:true}).click();}
async function mock(){await app.evaluate(({net},v)=>{global.__requests=[];net.fetch=async url=>{global.__requests.push(url);const repo={full_name:'sample/skills',description:'Useful skills for practical development workflows.',default_branch:'main',license:{spdx_id:'MIT'},pushed_at:'2026-09-22T08:00:00Z',stargazers_count:1280};if(url.includes('rate-limit'))return new Response('{}',{status:403});let value;if(url.includes('raw.githubusercontent.com'))return new Response(v.files[decodeURIComponent(url.split(v.commit+'/')[1])]);if(url.includes('/search/'))value={items:[repo],total_count:1};else if(url.includes('/commits/'))value={sha:v.commit};else if(url.includes('/git/trees/'))value={tree:v.tree};else value=repo;return new Response(JSON.stringify(value));};},{files,tree,commit});}
(async()=>{try{await launch();await mock();
 await check('search, repository discovery and pinned audit show source files and license',async()=>{
  await p.getByLabel('GitHub 搜索',{exact:true}).fill('writing agent skills');await p.getByRole('button',{name:'搜索 GitHub',exact:true}).click();await shot('github-search');await p.getByRole('button',{name:'发现 Skills',exact:true}).click();await shot('repository-skills');await p.getByRole('button',{name:'查看并审查',exact:true}).click();await p.getByRole('heading',{name:'安装到哪里',exact:true}).waitFor();assert.equal(await p.getByRole('button',{name:'确认并安装',exact:true}).isDisabled(),true);await p.getByLabel('审查文件',{exact:true}).selectOption('LICENSE');await p.waitForFunction(()=>document.querySelector('.market-source pre')?.textContent.includes('MIT License'));await p.getByLabel('审查文件',{exact:true}).selectOption('SKILL.md');
 });
 await check('native install is isolated, duplicate cannot overwrite, ZIP exports exact reviewed payload',async()=>{
  await p.locator('.market-consent input').check();await p.getByRole('button',{name:'确认并安装',exact:true}).click();await p.getByRole('status').filter({hasText:'已安装 work-review'}).waitFor();const installed=await p.evaluate(()=>window.starSleep.marketState());assert.ok(installed.installs[0].destination.startsWith(data));assert.equal(fs.readFileSync(path.join(installed.installs[0].destination,'SKILL.md'),'utf8'),md);
  await p.locator('.market-consent input').check();await p.getByRole('button',{name:'确认并安装',exact:true}).click();await p.getByRole('status').filter({hasText:'同名技能已存在'}).waitFor();const zip=path.join(data,'claude-skill.zip');await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},zip);await p.getByRole('button',{name:'导出 Claude 聊天技能包',exact:true}).click();await p.getByRole('status').filter({hasText:'已导出'}).waitFor();const unpack=require('fflate').unzipSync(fs.readFileSync(zip));assert.equal(Buffer.from(unpack['work-review/SKILL.md']).toString(),md);assert.ok(unpack['work-review/LICENSE']);
 });
 await check('audit, install and navigation controls reachable at compact and high zoom',async()=>{
  for(const[name,w,h,z]of [['desktop',1280,820,1],['compact',900,650,1],['zoom125',900,650,1.25],['zoom150',900,650,1.5],['zoom200',900,650,2]]){await app.evaluate(({BrowserWindow},v)=>{const w=BrowserWindow.getAllWindows()[0];w.setSize(v.w,v.h);w.webContents.setZoomFactor(v.z);},{w,h,z});await p.locator('.toolbox-body').evaluate(e=>e.scrollTop=0);await p.waitForTimeout(100);await shot(name+'-audit');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),true);const install=p.getByRole('button',{name:'确认并安装',exact:true});await install.scrollIntoViewIfNeeded();await install.focus();assert.equal(await install.evaluate(e=>document.activeElement===e),true);await shot(name+'-install');}
 });
 await app.close();await launch();await mock();
 await check('history survives restart, remove retains files and restore returns original version',async()=>{
  await p.getByRole('button',{name:'安装记录',exact:true}).click();await p.getByRole('heading',{name:'work-review',exact:true}).waitFor();await p.getByRole('button',{name:'移除技能',exact:true}).click();await p.getByRole('button',{name:'确认移除',exact:true}).click();await p.getByRole('button',{name:'恢复技能',exact:true}).click();await p.getByRole('status').filter({hasText:'已恢复'}).waitFor();await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];w.setSize(1280,820);w.webContents.setZoomFactor(1);});await p.locator('.toolbox-body').evaluate(e=>e.scrollTop=0);await shot('install-history');const s=await p.evaluate(()=>window.starSleep.marketState());assert.equal(s.installs[0].status,'installed');assert.equal(fs.readFileSync(path.join(s.installs[0].destination,'SKILL.md'),'utf8'),md);
 });
 await check('rate limits produce actionable feedback; scheduler demo still interrupts marketplace',async()=>{
  await p.getByRole('button',{name:'返回发现',exact:true}).click();await p.getByLabel('GitHub 搜索',{exact:true}).fill('rate-limit skills');await p.getByRole('button',{name:'搜索 GitHub',exact:true}).click();await p.getByRole('status').filter({hasText:'GitHub 请求受限'}).waitFor();await p.evaluate(()=>window.starSleep.demo('shutdown'));await p.getByRole('dialog',{name:'到时提醒',exact:true}).waitFor();await p.getByRole('button',{name:'结束演示',exact:true}).click();await p.getByRole('dialog').waitFor({state:'hidden'});
 });assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'desktop-results.json'),JSON.stringify({results,errors,safe:true,data,network:'deterministic GitHub responses',executable:process.env.STARSLEEP_QA_EXE||'development'},null,2));
 }finally{if(app)await app.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
