const {_electron:electron}=require('playwright');
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),data=path.join(root,'.qa-data','toolbox-'+Date.now()),out=process.env.STARSLEEP_QA_OUT||path.join(root,'artifacts/v16');
fs.mkdirSync(data,{recursive:true});fs.mkdirSync(out,{recursive:true});
function seed(){const c=path.join(data,'usage-samples/codex/sessions'),a=path.join(data,'usage-samples/claude/projects/demo');fs.mkdirSync(c,{recursive:true});fs.mkdirSync(a,{recursive:true});for(let i=0;i<14;i++){const d=new Date();d.setDate(d.getDate()-i);d.setHours(8,0,0,0);const timestamp=d.toISOString(),input=10000+i*1100,output=1000+i*80,cache=4000+i*400;const event={timestamp,type:'event_msg',payload:{type:'token_count',info:{total_token_usage:{input_tokens:input,cached_input_tokens:cache,output_tokens:output,total_tokens:input+output},last_token_usage:{input_tokens:input,cached_input_tokens:cache,output_tokens:output,total_tokens:input+output}}}};fs.writeFileSync(path.join(c,`day-${i}.jsonl`),[{timestamp,type:'session_meta',payload:{id:`test-${i}`}},{timestamp,type:'turn_context',payload:{model:'gpt-5.4'}},event,event].map(JSON.stringify).join('\n')+'\n');fs.writeFileSync(path.join(a,`day-${i}.jsonl`),JSON.stringify({timestamp,type:'assistant',sessionId:'test-'+i,requestId:'r-'+i,message:{id:'m-'+i,role:'assistant',model:'claude-sonnet-4-6',usage:{input_tokens:1200+i*120,output_tokens:200,cache_read_input_tokens:800,cache_creation_input_tokens:100}}})+'\n');}const dir=path.join(data,'skill-samples/.codex/skills/qa-skill');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'SKILL.md'),'---\nname: qa-document-helper\ndescription: 整理本机文档与工作清单的测试技能\n---\nOnly a QA fixture.');}
seed();let app,p;const results=[],errors=[];const env={...process.env,STARSLEEP_QA_DATA:data};delete env.ELECTRON_RUN_AS_NODE;
async function shot(name){const png=await app.evaluate(async({BrowserWindow})=>(await BrowserWindow.getAllWindows()[0].capturePage()).toPNG().toString('base64'));fs.writeFileSync(path.join(out,name+'.png'),Buffer.from(png,'base64'));}
const check=async(name,fn)=>{await fn();results.push(name);console.log('PASS',name);};
async function launch(){app=await electron.launch({...(process.env.STARSLEEP_QA_EXE?{executablePath:process.env.STARSLEEP_QA_EXE}:{}),args:[...(process.env.STARSLEEP_QA_EXE?[]:[root]),'--safe-mode'],env,timeout:60000});p=await app.firstWindow();p.setDefaultTimeout(15000);p.on('pageerror',e=>errors.push(e.message));await p.getByRole('button',{name:'Agent 工具箱',exact:true}).waitFor();await p.evaluate(async()=>{const s=await window.starSleep.snapshot();await window.starSleep.settings({...s.settings,sound:false,volume:0,reducedMotion:true});});await p.getByRole('button',{name:'Agent 工具箱',exact:true}).click();}
(async()=>{try{
 await launch();
 await check('bundled engine reports actual fixture counts, range and source filtering and private export',async()=>{
  await p.getByRole('button',{name:'刷新',exact:true}).waitFor({state:'visible'});await p.getByRole('button',{name:'今天',exact:true}).click();assert.equal(await p.getByTestId('usage-total').innerText(),'13,300');await p.getByLabel('用量来源',{exact:true}).selectOption('codex');assert.equal(await p.getByTestId('usage-total').innerText(),'11,000');
  const file=path.join(data,'report.json');await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},file);await p.getByRole('button',{name:'导出摘要',exact:true}).click();await p.getByRole('status').filter({hasText:'用量摘要已导出'}).waitFor();const report=JSON.parse(fs.readFileSync(file,'utf8'));assert.equal(report.totals.total,11000);assert.equal(report.source,'codex');assert.equal(JSON.stringify(report).includes(data),false);assert.equal(JSON.stringify(report).includes('messages'),false);
  await p.getByLabel('用量来源',{exact:true}).selectOption('all');await p.getByRole('button',{name:'近 7 天',exact:true}).click();
 });
 await check('resources support search, category filtering, favorites, notes, copying and allowlisted links',async()=>{
  await p.getByRole('button',{name:'开源资源',exact:true}).click();await p.getByRole('button',{name:'收藏',exact:true}).click();await p.getByLabel('资源备注',{exact:true}).fill('每周复盘 Token，先看模型分布');await p.getByRole('button',{name:'保存备注',exact:true}).click();await p.getByRole('button',{name:'保存备注',exact:true}).waitFor({state:'visible'});await p.getByRole('button',{name:'复制说明',exact:true}).click();assert.match(await app.evaluate(({clipboard})=>clipboard.readText()),/github.com\/ccusage\/ccusage/);
  await app.evaluate(({shell})=>{global.__opened=[];shell.openExternal=async url=>{global.__opened.push(url);};});await p.getByRole('button',{name:'打开作者仓库',exact:true}).click();assert.deepEqual(await app.evaluate(()=>global.__opened),['https://github.com/ccusage/ccusage']);assert.equal(await p.evaluate(()=>window.starSleep.resourceOpen('https://invalid.example').then(()=>false,()=>true)),true);
  await p.getByRole('button',{name:'只看收藏',exact:true}).click();assert.equal(await p.locator('.resource-row').count(),1);await p.getByLabel('搜索开源资源').fill('每周复盘');assert.equal(await p.locator('.resource-row').count(),1);await p.getByLabel('搜索开源资源').fill('没有这种工具');assert.equal(await p.locator('.resource-row').count(),0);await p.getByLabel('搜索开源资源').fill('');await p.getByRole('button',{name:'只看收藏',exact:true}).click();await p.getByLabel('资源类别').selectOption('mcp');assert.equal(await p.locator('.resource-row').count(),2);await p.getByLabel('资源类别').selectOption('all');
 });
 await check('local skill inventory searches metadata and reveals only scanned paths',async()=>{
  await p.getByRole('button',{name:'本机 Skills',exact:true}).click();await p.getByRole('heading',{name:'qa-document-helper',exact:true}).waitFor();await p.getByLabel('搜索本机技能').fill('整理');assert.equal(await p.locator('.local-skill').count(),1);await app.evaluate(({shell})=>{global.__revealed=[];shell.showItemInFolder=p=>global.__revealed.push(p);});await p.getByRole('button',{name:'打开所在目录',exact:true}).click();assert.match((await app.evaluate(()=>global.__revealed))[0],/qa-skill/);assert.equal(await p.evaluate(()=>window.starSleep.skillReveal('C:\\Windows').then(()=>false,()=>true)),true);await shot('local-skills');
 });
 await app.close();await launch();
 await check('favorites and notes survive restart; invalid data directories leave selection unchanged',async()=>{
  await p.getByRole('button',{name:'刷新',exact:true}).waitFor();const before=await p.evaluate(()=>window.starSleep.toolboxState());assert.equal(before.marks.ccusage.favorite,true);assert.equal(before.marks.ccusage.note,'每周复盘 Token，先看模型分布');await app.evaluate(({dialog},data)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[data]});},data);assert.equal(await p.evaluate(()=>window.starSleep.usageSelect('codex').then(()=>false,()=>true)),true);assert.deepEqual((await p.evaluate(()=>window.starSleep.toolboxState())).paths,before.paths);
 });
 await check('toolbox controls remain reachable at desktop, compact and 125/150/200 percent zoom',async()=>{
  for(const [name,w,h,zoom]of [['desktop',1280,820,1],['compact',900,650,1],['zoom125',900,650,1.25],['zoom150',900,650,1.5],['zoom200',900,650,2]]){
   await app.evaluate(({BrowserWindow},v)=>{const win=BrowserWindow.getAllWindows()[0];win.setSize(v.w,v.h);win.webContents.setZoomFactor(v.zoom);},{w,h,zoom});await p.getByRole('button',{name:'用量看板',exact:true}).click();await p.locator('.toolbox-body').evaluate(e=>e.scrollTop=0);await p.waitForTimeout(100);await shot(name+'-usage');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),true);await p.getByRole('button',{name:'导出摘要',exact:true}).focus();assert.equal(await p.getByRole('button',{name:'导出摘要',exact:true}).evaluate(e=>document.activeElement===e),true);
   await p.getByRole('button',{name:'开源资源',exact:true}).click();await p.locator('.toolbox-body').evaluate(e=>e.scrollTop=0);await p.waitForTimeout(80);await shot(name+'-resources');const open=p.getByRole('button',{name:'打开作者仓库',exact:true});await open.scrollIntoViewIfNeeded();const rect=await open.boundingBox();assert.ok(rect&&rect.y>=0&&rect.y+rect.height<=await p.evaluate(()=>innerHeight));await open.focus();assert.equal(await open.evaluate(e=>document.activeElement===e),true);await shot(name+'-resource-actions');
  }
 });
 await check('reminders still interrupt toolbox and return to schedules remains available',async()=>{await p.evaluate(()=>window.starSleep.demo('shutdown'));await p.getByRole('dialog',{name:'到时提醒',exact:true}).waitFor();await p.getByRole('button',{name:'结束演示',exact:true}).click();await p.getByRole('dialog').waitFor({state:'hidden'});await p.getByRole('button',{name:'返回计划',exact:true}).click();await p.getByRole('button',{name:'新建计划',exact:true}).waitFor();});
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({results,errors,data,safe:true,executable:process.env.STARSLEEP_QA_EXE||'development Electron'},null,2));
 }finally{if(app)await app.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
