const {_electron:electron}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),out=path.join(root,'artifacts/v191'),data=path.join(root,'.qa-data','v191-'+Date.now());fs.mkdirSync(out,{recursive:true});const env={...process.env,STARSLEEP_QA_DATA:data};delete env.ELECTRON_RUN_AS_NODE;
let app,p;const results=[],errors=[];const check=async(name,fn)=>{await fn();results.push(name);console.log('PASS',name);};
async function capture(name){const bytes=await app.evaluate(async({BrowserWindow})=>(await BrowserWindow.getAllWindows()[0].capturePage()).toPNG().toString('base64'));fs.writeFileSync(path.join(out,name+'.png'),Buffer.from(bytes,'base64'));}
(async()=>{try{
 app=await electron.launch({...(process.env.STARSLEEP_QA_EXE?{executablePath:process.env.STARSLEEP_QA_EXE}:{}),args:[...(process.env.STARSLEEP_QA_EXE?[]:[root]),'--safe-mode'],env,recordVideo:{dir:path.join(out,'video'),size:{width:1240,height:820}},timeout:60000});p=await app.firstWindow();p.setDefaultTimeout(18000);p.on('pageerror',e=>errors.push(e.message));
 await check('cinematic plays three phases, then disposes without adding a window',async()=>{await p.getByRole('region',{name:'启动动画'}).waitFor();await p.waitForFunction(()=>+document.querySelector('.star-scene').dataset.launchTime>650);await capture('charge');await p.waitForFunction(()=>+document.querySelector('.star-scene').dataset.launchTime>2600);await capture('flight');await p.waitForFunction(()=>+document.querySelector('.star-scene').dataset.launchTime>4750);await capture('arrival');await p.getByRole('button',{name:'新建计划',exact:true}).waitFor();assert.equal(await p.locator('.star-scene canvas').count(),1);assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().length),1);assert.ok(await p.locator('.star-scene').evaluate(e=>!e.dataset.launchPhase));});
 await check('observation replay, immediate skip and focus recovery work',async()=>{await p.evaluate(async()=>{const s=await window.starSleep.snapshot();await window.starSleep.settings({...s.settings,sound:false,volume:0});});await p.getByRole('button',{name:'星际观景',exact:true}).click();await p.getByRole('button',{name:'重播开场',exact:true}).click();await p.getByRole('region',{name:'启动动画'}).waitFor();await p.getByRole('button',{name:'进入工作台',exact:true}).click();await p.waitForTimeout(100);assert.equal(await p.getByRole('region',{name:'启动动画'}).count(),0);assert.ok(await p.locator('.space-navigation button[aria-current=page]').evaluate(e=>document.activeElement===e));});
 await check('demo shutdown reminder preempts launch and freezes the scene',async()=>{await p.getByRole('button',{name:'星际观景',exact:true}).click();await p.getByRole('button',{name:'重播开场',exact:true}).click();await p.evaluate(()=>window.starSleep.demo('shutdown'));await p.getByRole('dialog',{name:'到时提醒',exact:true}).waitFor();assert.equal(await p.getByRole('region',{name:'启动动画'}).count(),0);await p.waitForTimeout(120);const n=await p.evaluate(()=>window.__starScene.draws);await p.waitForTimeout(400);assert.equal(await p.evaluate(()=>window.__starScene.draws),n);await p.getByRole('button',{name:'结束演示',exact:true}).click();});
 await check('hidden during launch has zero decorative draws and recovers usable controls',async()=>{await p.getByRole('button',{name:'星际观景',exact:true}).click();await p.getByRole('button',{name:'重播开场',exact:true}).click();await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].hide());await p.waitForTimeout(150);const n=await p.evaluate(()=>window.__starScene.draws);await p.waitForTimeout(350);assert.equal(await p.evaluate(()=>window.__starScene.draws),n);await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].show());await p.keyboard.press('Escape');await p.getByRole('button',{name:'新建计划',exact:true}).waitFor();});
 await check('200 percent zoom keeps skip and pause accessible; reduced motion retains static work area',async()=>{await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];w.setSize(900,650);w.webContents.setZoomFactor(2);});await p.getByRole('button',{name:'星际观景',exact:true}).click();await p.getByRole('button',{name:'重播开场',exact:true}).click();await p.waitForTimeout(900);await capture('zoom200');const button=p.getByRole('button',{name:'进入工作台',exact:true});const box=await button.boundingBox(),viewport=await p.evaluate(()=>({w:innerWidth,h:innerHeight}));assert.ok(box.x>=0&&box.y>=0&&box.x+box.width<=viewport.w+1&&box.y+box.height<=viewport.h+1);await p.getByRole('button',{name:'暂停全部',exact:true}).click();await p.keyboard.press('Escape');await p.evaluate(async()=>{const s=await window.starSleep.snapshot();await window.starSleep.settings({...s.settings,reducedMotion:true});});await p.waitForTimeout(150);const n=await p.evaluate(()=>window.__starScene.draws);await p.waitForTimeout(350);assert.equal(await p.evaluate(()=>window.__starScene.draws),n);assert.equal(await p.locator('.cinematic-launch').count(),0);});
 await check('automatic intro opt-out permits explicit replay, while static quality bypasses it',async()=>{await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];w.setSize(1240,820);w.webContents.setZoomFactor(1);});await p.evaluate(async()=>{const s=await window.starSleep.snapshot();await window.starSleep.settings({...s.settings,reducedMotion:false});const e=await window.starSleep.experience();await window.starSleep.experiencePrefs({...e.prefs,startupAnimation:false,motionQuality:'adaptive'});});await p.reload();await p.getByRole('button',{name:'新建计划',exact:true}).waitFor();assert.equal(await p.locator('.cinematic-launch').count(),0);await p.getByRole('button',{name:'星际观景',exact:true}).click();await p.getByRole('button',{name:'重播开场',exact:true}).click();await p.getByRole('region',{name:'启动动画'}).waitFor();await p.evaluate(async()=>{const e=await window.starSleep.experience();await window.starSleep.experiencePrefs({...e.prefs,startupAnimation:true,motionQuality:'static'});});await p.getByRole('region',{name:'启动动画'}).waitFor({state:'hidden'});await p.reload();await p.getByRole('button',{name:'新建计划',exact:true}).waitFor();assert.equal(await p.locator('.cinematic-launch').count(),0);});
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({results,errors,safe:true},null,2));const video=p.video();await app.close();app=null;if(video)await video.saveAs(path.join(out,'StarNexus-v1.9.1-cinematic.webm'));
}finally{if(app)await app.close();}})().catch(e=>{console.error(e);fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({error:String(e),results,errors},null,2));process.exitCode=1;});
