const {_electron:electron}=require('playwright');
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),out=process.env.STARSLEEP_QA_OUT||path.join(root,'artifacts/v18/desktop'),data=path.join(root,'.qa-data','v18-'+Date.now());fs.mkdirSync(out,{recursive:true});
const env={...process.env,STARSLEEP_QA_DATA:data};delete env.ELECTRON_RUN_AS_NODE;
let app,p;const results=[],errors=[];const check=async(name,fn)=>{await fn();results.push(name);console.log('PASS',name);};
const shot=async name=>{if(process.env.STARSLEEP_QA_NO_SHOTS==='1')return;const bytes=await app.evaluate(async({BrowserWindow})=>(await BrowserWindow.getAllWindows()[0].capturePage()).toPNG().toString('base64'));fs.writeFileSync(path.join(out,name+'.png'),Buffer.from(bytes,'base64'));};
const resize=async(w,h,z=1)=>{await app.evaluate(({BrowserWindow},v)=>{const win=BrowserWindow.getAllWindows()[0];win.setSize(v.w,v.h);win.webContents.setZoomFactor(v.z);},{w,h,z});await p.waitForTimeout(200);};
(async()=>{try{
 app=await electron.launch({...(process.env.STARSLEEP_QA_EXE?{executablePath:process.env.STARSLEEP_QA_EXE}:{}),args:[...(process.env.STARSLEEP_QA_EXE?[]:[root]),'--safe-mode'],env,timeout:60000});p=await app.firstWindow();p.setDefaultTimeout(20000);p.on('pageerror',e=>errors.push(e.message));await p.getByRole('button',{name:'新建计划',exact:true}).waitFor();await p.evaluate(async()=>{const s=await window.starSleep.snapshot();await window.starSleep.settings({...s.settings,sound:false,volume:0});});await resize(1320,880);
 await check('single WebGL scene renders; four nodes retain plan search and use keyboard controls',async()=>{
  await p.waitForFunction(()=>window.__starScene?.draws>10);assert.equal(await p.locator('.star-scene canvas').count(),1);await p.getByLabel('搜索计划',{exact:true}).fill('保留搜索');for(const name of ['Agent 工作台','美化工坊','系统维护','主控台']){await p.getByRole('navigation',{name:'空间导航'}).getByRole('button',{name,exact:true}).click();await p.waitForTimeout(650);}assert.equal(await p.getByLabel('搜索计划',{exact:true}).inputValue(),'保留搜索');await p.getByLabel('搜索计划',{exact:true}).fill('');await p.getByRole('button',{name:'镜头拉近',exact:true}).click();await p.waitForTimeout(400);assert.ok((await p.evaluate(()=>window.starSleep.experience())).prefs.cameraZoom>1);await p.getByRole('button',{name:'镜头复位',exact:true}).click();await p.waitForTimeout(400);await shot('control-full');
 });
 await check('actual community files download, identify all three clients, and preserve source',async()=>{
  await p.getByRole('navigation',{name:'空间导航'}).getByRole('button',{name:'美化工坊',exact:true}).click();
  for(const id of ['warm-light','arizona','dsh-aurora']){await p.evaluate(id=>window.starSleep.workshopDownload(id),id);const s=await p.evaluate(()=>window.starSleep.workshopState());assert.equal(s.tasks.find(t=>t.resourceId===id).status,'done',JSON.stringify(s.tasks));}
  const s=await p.evaluate(()=>window.starSleep.integrations());assert.equal(s.themes.length,3);assert.deepEqual(s.themes.map(t=>t.format).sort(),['claude-json','codex-native','dsh-dreamskin']);await shot('workshop-community');
 });
 await check('isolated apply requires explicit native confirmation and records written versus confirmed separately',async()=>{
  await app.evaluate(({dialog})=>{dialog.showMessageBox=async()=>({response:0});});const themes=(await p.evaluate(()=>window.starSleep.integrations())).themes;const codex=themes.find(t=>t.format==='codex-native');assert.equal(await p.evaluate(id=>window.starSleep.themeCodexApply(id),codex.id),'已取消');assert.equal((await p.evaluate(()=>window.starSleep.workshopState())).themes[codex.id].writtenAt,undefined);
  await app.evaluate(({dialog})=>{dialog.showMessageBox=async()=>({response:1});});for(const t of themes){await p.evaluate(t=>window.starSleep[t.format==='codex-native'?'themeCodexApply':t.format==='claude-json'?'themeClaudeApply':'themeDshApply'](t.id),t);const m=(await p.evaluate(()=>window.starSleep.workshopState())).themes[t.id];assert.ok(m.writtenAt);assert.equal(m.confirmedAt,undefined);await p.evaluate(id=>window.starSleep.workshopConfirm(id),t.id);}
  await p.getByRole('button',{name:'我的主题',exact:true}).click();await shot('workshop-library');const report=await p.evaluate(()=>window.starSleep.clientHealth());assert.equal(report.safe,true);assert.ok(Object.values(report.clients).every(c=>c.configPath.startsWith(data)));
  const file=path.join(data,'health-export.json');await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},file);await p.evaluate(()=>window.starSleep.exportHealth());assert.ok(!fs.readFileSync(file,'utf8').includes(data.replaceAll('\\','\\\\')));for(const fn of ['themeCodexRestore','themeClaudeRestore','themeDshRestore'])await p.evaluate(fn=>window.starSleep[fn](),fn);
 });
 await check('panel presets, edge keyboard resize, high zoom and narrow windows keep navigation reachable',async()=>{
  for(const[name,w,h,z]of [['compact',900,650,1],['zoom125',1100,800,1.25],['zoom150',1100,800,1.5],['zoom200',900,650,2]]){await resize(w,h,z);await p.getByRole('navigation',{name:'空间导航'}).getByRole('button',{name:'美化工坊',exact:true}).click();await p.getByRole('button',{name:'社区精选',exact:true}).click();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),true);await shot(name);await p.getByRole('button',{name:'展开',exact:true}).click();await p.getByRole('button',{name:'设置',exact:true}).focus();assert.equal(await p.getByRole('button',{name:'设置',exact:true}).evaluate(e=>document.activeElement===e),true);}
  await resize(1320,880);await p.getByRole('button',{name:'紧凑',exact:true}).click();const before=(await p.evaluate(()=>window.starSleep.experience())).prefs.panels.workshop;await p.getByRole('button',{name:'拖动调整面板尺寸；方向键调整',exact:true}).press('ArrowRight');const after=(await p.evaluate(()=>window.starSleep.experience())).prefs.panels.workshop;assert.ok(after.width>=before.width);await p.getByRole('button',{name:'展开',exact:true}).click();
 });
 await check('shutdown warning freezes scene immediately; hidden, minimized and mini draw zero frames',async()=>{
  await p.evaluate(()=>window.starSleep.demo('shutdown'));await p.getByRole('dialog',{name:'到时提醒',exact:true}).waitFor();await p.waitForTimeout(100);const first=await p.evaluate(()=>window.__starScene.draws);await p.waitForTimeout(800);assert.equal(await p.evaluate(()=>window.__starScene.draws),first);await shot('reminder-priority');await p.getByRole('button',{name:'结束演示',exact:true}).click();
  for(const mode of ['hide','minimize','mini']){if(mode==='mini')await p.evaluate(()=>window.starSleep.setMode('mini'));else await app.evaluate(({BrowserWindow},m)=>BrowserWindow.getAllWindows()[0][m](),mode);await p.waitForTimeout(200);const n=await p.evaluate(()=>window.__starScene.draws);await p.waitForTimeout(700);assert.equal(await p.evaluate(()=>window.__starScene.draws),n,mode);if(mode==='mini'){await shot('mini');await p.evaluate(()=>window.starSleep.setMode('full'));}await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];w.restore();w.show();});}
  assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().length),1);
 });
 await check('reduced motion and context loss retain complete DOM controls; retry restores rendering',async()=>{
  await p.evaluate(async()=>{const s=await window.starSleep.snapshot();await window.starSleep.settings({...s.settings,reducedMotion:true});});await p.waitForTimeout(150);let n=await p.evaluate(()=>window.__starScene.draws);await p.waitForTimeout(500);assert.equal(await p.evaluate(()=>window.__starScene.draws),n);await p.getByRole('navigation',{name:'空间导航'}).getByRole('button',{name:'主控台',exact:true}).click();await p.getByRole('button',{name:'新建计划',exact:true}).click();await p.getByRole('dialog').waitFor();await p.keyboard.press('Escape');await p.evaluate(async()=>{const s=await window.starSleep.snapshot();await window.starSleep.settings({...s.settings,reducedMotion:false});});await p.locator('.star-scene canvas').evaluate(c=>c.dispatchEvent(new Event('webglcontextlost',{cancelable:true})));await p.waitForTimeout(100);n=await p.evaluate(()=>window.__starScene.draws);await p.waitForTimeout(400);assert.equal(await p.evaluate(()=>window.__starScene.draws),n);await shot('webgl-fallback');await p.getByRole('button',{name:'重新启用动效',exact:true}).click();await p.waitForFunction(()=>window.__starScene.draws>5);
 });
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({results,errors,safe:true,data,network:'actual pinned community files',executable:process.env.STARSLEEP_QA_EXE||'development'},null,2));
}finally{if(app)await app.close();}})().catch(e=>{console.error(e);fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({error:String(e),results,errors},null,2));process.exitCode=1;});
