const {_electron:electron}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),out=process.env.STARSLEEP_QA_OUT||path.join(root,'artifacts/v110/desktop'),data=path.join(root,'.qa-data','v110-'+Date.now());fs.mkdirSync(out,{recursive:true});const env={...process.env,STARSLEEP_QA_DATA:data};delete env.ELECTRON_RUN_AS_NODE;
const codex=path.join(data,'usage-samples/codex/sessions');fs.mkdirSync(codex,{recursive:true});
function fixture(id,input=10000){const timestamp=new Date().toISOString(),output=1000,cache=4000;fs.writeFileSync(path.join(codex,id+'.jsonl'),[{timestamp,type:'session_meta',payload:{id}},{timestamp,type:'turn_context',payload:{model:'test-model'}},{timestamp,type:'event_msg',payload:{type:'token_count',info:{total_token_usage:{input_tokens:input,cached_input_tokens:cache,output_tokens:output,total_tokens:input+output},last_token_usage:{input_tokens:input,cached_input_tokens:cache,output_tokens:output,total_tokens:input+output}}}}].map(JSON.stringify).join('\n')+'\n');}fixture('initial');
let app,p;const results=[],errors=[];const check=async(name,fn)=>{await fn();results.push(name);console.log('PASS',name);};
const nav=async name=>p.getByRole('navigation',{name:'空间导航'}).getByRole('button',{name,exact:true}).click();
const shot=async name=>{await p.waitForTimeout(150);const bytes=await app.evaluate(async({BrowserWindow})=>(await BrowserWindow.getAllWindows()[0].capturePage()).toPNG().toString('base64'));fs.writeFileSync(path.join(out,name+'.png'),Buffer.from(bytes,'base64'));};
const command=async query=>{await p.keyboard.press('Control+k');await p.getByRole('dialog',{name:'快捷入口'}).waitFor();await p.getByRole('combobox',{name:'搜索功能'}).fill(query);await p.keyboard.press('Enter');};
(async()=>{try{
 app=await electron.launch({...(process.env.STARSLEEP_QA_EXE?{executablePath:process.env.STARSLEEP_QA_EXE}:{}),args:[...(process.env.STARSLEEP_QA_EXE?[]:[root]),'--safe-mode'],env,timeout:60000});p=await app.firstWindow();p.setDefaultTimeout(15000);p.on('pageerror',e=>errors.push(e.message));await p.getByRole('button',{name:'进入工作台',exact:true}).click();await p.evaluate(async()=>{const s=await window.starSleep.snapshot();await window.starSleep.settings({...s.settings,sound:false,volume:0});});
 await check('command search, keyboard selection, empty result and focus return',async()=>{await p.getByRole('button',{name:'快捷入口',exact:true}).click();await p.getByRole('combobox',{name:'搜索功能'}).fill('no-result');await p.getByText('没有匹配功能，试试“设置”或“Agent”。').waitFor();await p.getByRole('combobox',{name:'搜索功能'}).fill('');await p.keyboard.press('ArrowDown');assert.match(await p.locator('.command-list').getByRole('option',{selected:true}).innerText(),/Agent/);await shot('commands');await p.keyboard.press('Escape');assert.ok(await p.getByRole('button',{name:'快捷入口',exact:true}).evaluate(e=>document.activeElement===e));await command('Token');await p.getByRole('heading',{name:'Agent 工具箱'}).waitFor();});
 await check('usage detail is real fixture data, force refresh sees new data, unsupported sources remain explicit',async()=>{await p.getByRole('button',{name:'今天',exact:true}).click();await p.waitForFunction(()=>document.querySelector('[data-testid=usage-total]')?.textContent==='11,000');await p.locator('.usage-daily summary').click();assert.match(await p.locator('.usage-daily tbody').innerText(),/11,000/);assert.match(await p.locator('.usage-insights').innerText(),/40.0%/);await p.getByText('部分来源未读到数据，合计仅包含已读取记录。请检查下方数据来源。').waitFor();fixture('new');await p.getByRole('button',{name:'刷新',exact:true}).click();await p.waitForFunction(()=>document.querySelector('[data-testid=usage-total]')?.textContent==='22,000');assert.equal(await p.evaluate(()=>window.starSleep.usageRead('invalid').then(()=>false,()=>true)),true);await shot('usage');await p.locator('.usage-daily').scrollIntoViewIfNeeded();await shot('usage-detail');});
 await check('tool tabs retain range, source, search and unsaved notes; background usage sends no new polls',async()=>{await p.getByLabel('用量来源',{exact:true}).selectOption('codex');await p.getByRole('button',{name:'开源资源',exact:true}).click();await p.getByLabel('资源备注',{exact:true}).fill('尚未保存的备注');await p.getByLabel('搜索开源资源').fill('ccusage');await p.getByRole('button',{name:'用量看板',exact:true}).click();assert.equal(await p.getByLabel('用量来源',{exact:true}).inputValue(),'codex');assert.equal(await p.getByRole('button',{name:'今天',exact:true}).getAttribute('aria-pressed'),'true');await p.getByRole('button',{name:'开源资源',exact:true}).click();assert.equal(await p.getByLabel('资源备注',{exact:true}).inputValue(),'尚未保存的备注');assert.equal(await p.getByLabel('搜索开源资源').inputValue(),'ccusage');await app.evaluate(({ipcMain})=>{const original=ipcMain._invokeHandlers.get('usage-read');global.__usageCalls=0;ipcMain.removeHandler('usage-read');ipcMain.handle('usage-read',(...a)=>{global.__usageCalls++;return original(...a);});});await p.clock.install();await p.clock.fastForward(600001);assert.equal(await app.evaluate(()=>global.__usageCalls),0);await p.clock.resume();});
 await check('system summary and issue filter, recoverable health failure and cleared feedback',async()=>{await nav('系统维护');await p.getByRole('region',{name:'运行摘要'}).waitFor();await p.locator('.health-summary').waitFor();await p.getByRole('button',{name:'只看待处理项'}).click();assert.equal(await p.locator('.health-list .health-badge.ok').count(),0);await app.evaluate(({ipcMain})=>{global.__health=ipcMain._invokeHandlers.get('client-health');ipcMain.removeHandler('client-health');ipcMain.handle('client-health',()=>{throw Error('QA 体检失败');});});await p.getByRole('button',{name:'重新体检'}).click();await p.getByRole('status').filter({hasText:'QA 体检失败'}).waitFor();await app.evaluate(({ipcMain})=>{ipcMain.removeHandler('client-health');ipcMain.handle('client-health',global.__health);});await p.getByRole('button',{name:'重新体检'}).click();await p.waitForFunction(()=>!document.body.innerText.includes('QA 体检失败'));await p.getByRole('button',{name:'重新体检'}).waitFor();await p.locator('.flight-content').evaluate(e=>e.scrollTop=0);await shot('system');});
 await check('command does not create a plan, cannot replace editing, reminder preempts palette',async()=>{const before=await p.evaluate(()=>window.starSleep.snapshot());await command('新建');await p.getByRole('dialog').waitFor();await p.keyboard.press('Control+k');assert.equal(await p.getByRole('dialog',{name:'快捷入口'}).count(),0);await p.keyboard.press('Escape');assert.equal((await p.evaluate(()=>window.starSleep.snapshot())).plans.length,before.plans.length);await p.keyboard.press('Control+k');await p.getByRole('dialog',{name:'快捷入口'}).waitFor();await p.evaluate(()=>window.starSleep.demo('shutdown'));await p.getByRole('dialog',{name:'到时提醒'}).waitFor();await p.getByRole('dialog',{name:'快捷入口'}).waitFor({state:'hidden'});await p.keyboard.press('Control+k');assert.equal(await p.getByRole('dialog',{name:'快捷入口'}).count(),0);await p.getByRole('button',{name:'结束演示'}).click();});
 await check('compact and 125/150/200 percent layouts retain commands, navigation and scrolling',async()=>{for(const [label,w,h,z]of [['compact',900,650,1],['125',1100,800,1.25],['150',1100,800,1.5],['200',900,650,2]]){await app.evaluate(({BrowserWindow},v)=>{const w=BrowserWindow.getAllWindows()[0];w.setSize(v.w,v.h);w.webContents.setZoomFactor(v.z);},{w,h,z});await p.keyboard.press('Control+k');await p.getByRole('combobox',{name:'搜索功能'}).fill('设置');const option=p.locator('#command-settings');await option.scrollIntoViewIfNeeded();const box=await option.boundingBox();assert.ok(box.y>=0&&box.y+box.height<=await p.evaluate(()=>innerHeight));await shot('commands-'+label);await p.keyboard.press('Escape');assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));await nav('Agent 工作台');await p.getByRole('button',{name:'用量看板',exact:true}).click();await p.locator('.toolbox-body').evaluate(e=>e.scrollTop=0);await shot('usage-'+label);await p.getByRole('button',{name:'导出摘要'}).scrollIntoViewIfNeeded();assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));}});
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({safe:true,results,errors},null,2));
}finally{if(app)await app.close();}})().catch(e=>{console.error(e);fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({error:String(e),results,errors},null,2));process.exitCode=1;});
