const {_electron:electron}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),out=path.join(root,'artifacts/v13'),data=path.join(root,'.qa-data','v13-'+Date.now());
fs.mkdirSync(out,{recursive:true});fs.mkdirSync(data,{recursive:true});
const env={...process.env,STARSLEEP_QA_DATA:data};delete env.ELECTRON_RUN_AS_NODE;
let app,page;const results=[],errors=[];
const check=async(name,fn)=>{await fn();results.push({name,passed:true});console.log('PASS',name);};
const state=()=>page.evaluate(()=>window.starSleep.snapshot());
const experience=()=>page.evaluate(()=>window.starSleep.experience());
const shot=async name=>page.screenshot({path:path.join(out,name+'.png')});
async function launch(scale=1){app=await electron.launch({args:[root,'--safe-mode',`--force-device-scale-factor=${scale}`],env,timeout:60000});page=await app.firstWindow();page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));await page.getByRole('button',{name:'新建计划',exact:true}).waitFor();await page.evaluate(async()=>{let s=await window.starSleep.snapshot();await window.starSleep.settings({...s.settings,sound:false,volume:0});});}
async function library(){await page.locator('.templates summary').click();await page.getByRole('button',{name:'查看与管理个人模板'}).click();}
async function mini(){await page.getByRole('button',{name:'迷你模式',exact:true}).click();await page.getByRole('region',{name:'迷你控制台'}).waitFor();await page.waitForTimeout(400);}
async function full(){await page.getByRole('button',{name:'返回完整界面'}).click();await page.getByRole('button',{name:'新建计划',exact:true}).waitFor();}
(async()=>{
 await launch();await shot('01-empty');
 await check('template save preserves unsaved editor and creates no plan',async()=>{
  await page.getByRole('button',{name:'新建计划',exact:true}).click();await page.getByLabel('计划名称',{exact:true}).fill('夜航工作结束');await page.getByLabel('重复方式',{exact:true}).selectOption('daily');await page.getByLabel('执行时间',{exact:true}).fill('23:30');
  assert.equal(await page.evaluate(async()=>{try{await window.starSleep.setMode('mini');return false;}catch{return true;}}),true);
  await page.getByRole('button',{name:'存为常用模板',exact:true}).click();await page.getByLabel('模板名称').fill('我的夜航');await shot('02-template-editor');await page.getByRole('button',{name:'保存模板',exact:true}).click();await page.getByLabel('计划名称',{exact:true}).waitFor();assert.equal(await page.getByLabel('计划名称',{exact:true}).inputValue(),'夜航工作结束');assert.equal((await state()).plans.length,0);assert.equal((await experience()).presets.length,1);
  await page.keyboard.press('Escape');await page.getByRole('button',{name:'放弃修改',exact:true}).click();
 });
 await check('template apply requires confirmation; edit and delete never change existing plan',async()=>{
  await library();await shot('03-templates');await page.getByRole('button',{name:/^我的夜航.*每天/}).click();assert.equal((await state()).plans.length,0);await page.getByRole('button',{name:'保存计划',exact:true}).click();const before=(await state()).plans[0];
  await page.getByRole('button',{name:'查看与管理个人模板'}).click();await page.getByRole('button',{name:'编辑模板我的夜航'}).click();await page.getByLabel('模板名称').fill('夜航·改名');await page.getByRole('button',{name:'保存模板',exact:true}).click();assert.equal((await state()).plans[0].name,before.name);await page.getByRole('button',{name:'删除模板夜航·改名'}).click();await page.getByRole('button',{name:'删除模板',exact:true}).click();assert.equal((await experience()).presets.length,0);assert.equal((await state()).plans[0].id,before.id);await page.keyboard.press('Escape');await page.locator('.templates summary').click();
 });
 await check('quick template retains name and duration, starts only at confirmation',async()=>{
  await page.getByRole('button',{name:'快捷计时',exact:true}).click();await page.getByLabel('自定义分钟').fill('30');await page.getByLabel('到点动作',{exact:true}).selectOption('alarm');await page.getByRole('button',{name:'存为常用模板',exact:true}).click();await page.getByLabel('模板名称').fill('半小时后伸个懒腰');await page.getByRole('button',{name:'保存模板',exact:true}).click();await page.getByLabel('模板名称').waitFor({state:'hidden'});await page.getByRole('dialog',{name:'快捷计时',exact:true}).getByRole('button',{name:'取消',exact:true}).click();await library();await page.getByRole('button',{name:/^半小时后伸个懒腰.*30/}).click();assert.equal((await state()).plans.length,1);await page.waitForTimeout(1100);const now=Date.now();await page.getByRole('button',{name:'开始计时',exact:true}).click();const p=(await state()).plans.find(p=>p.name==='半小时后伸个懒腰');assert.ok(Math.abs(p.exactAt-now-1800000)<2500);await page.locator('.templates summary').click();
 });
 await check('seven day counts, item editor, skip update and paused labels',async()=>{
  await page.getByRole('button',{name:'未来七天',exact:true}).click();await page.locator('.agenda-days button').first().waitFor();assert.equal(await page.locator('.agenda-days button').count(),7);let a=await page.evaluate(()=>window.starSleep.agenda());assert.equal(await page.locator('.agenda-event').count(),a.days[0].occurrences.length);await shot('04-agenda');
  const p=(await state()).plans.find(p=>p.kind==='alarm');await page.evaluate(p=>window.starSleep.skip(p.id,p.nextAt),p);await page.waitForFunction(()=>!Array.from(document.querySelectorAll('.agenda-event')).some(e=>e.textContent.includes('半小时后伸个懒腰')));
  await page.evaluate(()=>window.starSleep.pause(true));await page.getByText('全部暂停 · 原定安排',{exact:true}).waitFor();await page.evaluate(()=>window.starSleep.pause(false));await page.keyboard.press('Control+f');await page.getByLabel('搜索计划').waitFor();await page.getByLabel('搜索计划').fill('夜航');
 });
 await check('mini reuses one window and renderer, retains filter, clears selection, supports pin and pause',async()=>{
  await page.getByLabel('全选当前筛选结果').check();const before=await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];return {id:w.id,pid:w.webContents.getOSProcessId(),bounds:w.getBounds()};});await mini();const after=await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];return {count:BrowserWindow.getAllWindows().length,id:w.id,pid:w.webContents.getOSProcessId(),bounds:w.getBounds(),top:w.isAlwaysOnTop()};});assert.equal(after.count,1);assert.equal(after.id,before.id);assert.equal(after.pid,before.pid);assert.ok(Math.abs(after.bounds.width-320)<=1);assert.equal(after.bounds.height,168);assert.equal(after.top,true);await shot('05-mini');assert.equal(await page.evaluate(()=>document.body.classList.contains('motion-off')),true);
  await page.getByRole('button',{name:'取消置顶'}).click();await page.waitForTimeout(200);assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isAlwaysOnTop()),false);await page.getByRole('button',{name:'置顶小窗'}).click();await page.getByRole('button',{name:'暂停全部',exact:true}).click();await page.getByText('全部计划已暂停',{exact:true}).waitFor();await shot('06-mini-paused');await page.getByRole('button',{name:'恢复计划',exact:true}).click();await full();assert.equal(await page.getByLabel('搜索计划').inputValue(),'夜航');assert.equal(await page.getByLabel('全选当前筛选结果').isChecked(),false);assert.deepEqual(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].getBounds()),before.bounds);await page.getByLabel('搜索计划').fill('');
 });
 await check('reminders restore full mode and do not create duplicate audio controllers',async()=>{
  await page.evaluate(()=>{const original=AudioContext.prototype.createOscillator;window.audioActive=0;AudioContext.prototype.createOscillator=function(){let o=original.call(this);window.audioActive++;o.addEventListener('ended',()=>window.audioActive--);return o;};});await mini();await page.evaluate(()=>window.starSleep.demo('alarm'));await page.getByRole('dialog',{name:'到时提醒'}).waitFor();assert.equal((await experience()).mode,'full');const active=await page.evaluate(()=>window.audioActive);assert.ok(active>0&&active<=78);const ends=(await state()).alarms[0].endsAt;await page.evaluate(()=>window.starSleep.setMode('full'));assert.equal((await state()).alarms[0].endsAt,ends);await shot('07-reminder');await page.getByRole('button',{name:'停止提醒',exact:true}).click();await page.waitForFunction(()=>window.audioActive===0,null,{polling:100,timeout:3000});assert.equal((await experience()).mode,'full');
  await mini();await page.evaluate(()=>window.starSleep.quick({kind:'shutdown',minutes:1}));await page.getByRole('dialog',{name:'到时提醒'}).waitFor();assert.equal((await experience()).mode,'full');await page.getByRole('button',{name:'取消本次关机',exact:true}).click();
 });
 await check('signal keyboard feedback has cooldown and no plan mutation; reduced motion and preference persist',async()=>{
  const before=JSON.stringify((await state()).plans);const button=page.getByRole('button',{name:'发送星舰信号'});await button.press('Enter');assert.equal(await button.isDisabled(),true);assert.equal(JSON.stringify((await state()).plans),before);await page.waitForTimeout(1600);assert.equal(await button.isEnabled(),true);
  await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByRole('button',{name:'外观',exact:true}).click();await page.getByRole('switch',{name:'减少动态效果'}).click();await page.getByRole('switch',{name:'星舰互动'}).click();await shot('08-settings');await page.keyboard.press('Escape');assert.equal(await page.getByRole('button',{name:'发送星舰信号'}).isDisabled(),true);assert.equal((await experience()).prefs.interaction,false);
 });
 await check('tray mode request respects editor protection and hide keeps app alive',async()=>{
  await app.evaluate(({Menu})=>{const build=Menu.buildFromTemplate;Menu.buildFromTemplate=function(items){globalThis.trayItems=items;return build.call(this,items);};});await page.evaluate(()=>window.starSleep.pause(true));await page.getByRole('button',{name:'新建计划',exact:true}).click();await page.getByLabel('计划名称',{exact:true}).fill('保留草稿');await app.evaluate(()=>globalThis.trayItems.find(i=>i.label==='迷你模式').click());assert.equal((await experience()).mode,'full');assert.equal(await page.getByLabel('计划名称',{exact:true}).inputValue(),'保留草稿');await page.keyboard.press('Escape');await page.getByRole('button',{name:'放弃修改'}).click();await page.evaluate(()=>window.starSleep.pause(false));await mini();await page.getByRole('button',{name:'隐藏到托盘'}).click();assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isVisible()),false);await app.evaluate(()=>globalThis.trayItems.find(i=>i.label==='迷你模式').click());await page.getByRole('button',{name:'返回完整界面'}).waitFor();await full();
 });
 await check('minimum full layout and mini have no overflow',async()=>{await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(900,650));await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await shot('09-minimum');await mini();assert.equal(await page.evaluate(()=>document.documentElement.scrollHeight>innerHeight),false);await full();await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1240,800));await page.waitForTimeout(300);await shot('10-console');});
 await check('experience fault cannot stop valid schedules',async()=>{await page.waitForTimeout(600);fs.mkdirSync(path.join(data,'experience.json.tmp'));assert.equal(await page.evaluate(async()=>{try{await window.starSleep.savePreset({type:'quick',name:'失败',kind:'alarm',minutes:30});return false;}catch{return true;}}),true);assert.ok((await experience()).error);assert.ok(!(await state()).storageError);assert.equal((await state()).paused,false);const n=(await state()).plans.length;await page.evaluate(()=>window.starSleep.quick({kind:'alarm',minutes:30}));assert.equal((await state()).plans.length,n+1);fs.rmdirSync(path.join(data,'experience.json.tmp'));});
 await app.close();app=null;
 await check('restart defaults full and keeps templates and preferences',async()=>{await launch();assert.equal((await experience()).mode,'full');assert.equal((await experience()).presets.length,1);assert.equal((await experience()).prefs.interaction,false);assert.equal((await experience()).error,undefined);await app.close();app=null;});
 for(const scale of [1.25,1.5,2])await check(`full and mini at ${scale*100}%`,async()=>{await launch(scale);await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];w.setSize(900,650);w.focus();});await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await shot(`full-scale-${scale}`);await mini();assert.equal(await page.evaluate(()=>document.documentElement.scrollHeight>innerHeight),false);await shot(`mini-scale-${scale}`);await full();await page.keyboard.press('Control+n');await page.getByLabel('计划名称',{exact:true}).waitFor();await page.keyboard.press('Escape');await app.close();app=null;});
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'qa-results.json'),JSON.stringify({results,errors,actualShutdownTested:false},null,2));console.log('Completed',results.length,'v1.3 desktop checks');
})().catch(async e=>{console.error(e);if(app){await shot('failure').catch(()=>{});await app.close().catch(()=>{});}fs.writeFileSync(path.join(out,'qa-results.json'),JSON.stringify({results,errors,failure:String(e)},null,2));process.exitCode=1;});
