const {_electron:electron}=require('playwright');const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),out=path.join(root,'artifacts/v19/desktop'),data=path.join(root,'.qa-data/v19-'+Date.now());fs.mkdirSync(out,{recursive:true});
const env={...process.env,STARSLEEP_QA_DATA:data};delete env.ELECTRON_RUN_AS_NODE;let app,p;const results=[],errors=[];
const check=async(name,fn)=>{await fn();results.push(name);console.log('PASS',name);};
const shot=async name=>{if(['startup','observatory'].includes(name))await p.waitForTimeout(750);if(name==='studio-image')await p.locator('.flight-content').evaluate(e=>e.scrollTop=0);const bytes=await app.evaluate(async({BrowserWindow})=>(await BrowserWindow.getAllWindows()[0].capturePage()).toPNG().toString('base64'));fs.writeFileSync(path.join(out,name+'.png'),Buffer.from(bytes,'base64'));};
const nav=async name=>p.getByRole('navigation',{name:'空间导航'}).getByRole('button',{name,exact:true}).click();
async function launch(){app=await electron.launch({...(process.env.STARSLEEP_QA_EXE?{executablePath:process.env.STARSLEEP_QA_EXE}:{}),args:[...(process.env.STARSLEEP_QA_EXE?[]:[root]),'--safe-mode'],env,timeout:60000});p=await app.firstWindow();p.setDefaultTimeout(20000);p.on('pageerror',e=>errors.push(e.message));}
(async()=>{try{await launch();
 await check('startup offers immediate skip and single Canvas; new brand visible',async()=>{await p.getByRole('region',{name:'启动动画'}).waitFor();assert.equal(await p.locator('.star-scene canvas').count(),1);assert.ok(await p.locator('.brand').innerText().then(s=>s.includes('星枢')));await shot('startup');await p.getByRole('button',{name:'进入工作台',exact:true}).click();await p.getByRole('button',{name:'新建计划',exact:true}).waitFor();await p.evaluate(async()=>{const s=await window.starSleep.snapshot();await window.starSleep.settings({...s.settings,sound:false,volume:0});});});
 await check('scene reveal preserves search and reminder preempts it',async()=>{await p.getByLabel('搜索计划',{exact:true}).fill('保留搜索');await shot('control');await p.getByRole('button',{name:'星际观景',exact:true}).click();await p.getByRole('region',{name:'星际观景'}).waitFor();await shot('observatory');await p.keyboard.press('Escape');assert.equal(await p.getByLabel('搜索计划',{exact:true}).inputValue(),'保留搜索');await p.getByRole('button',{name:'星际观景',exact:true}).click();await p.evaluate(()=>window.starSleep.demo('shutdown'));await p.getByRole('dialog',{name:'到时提醒',exact:true}).waitFor();assert.equal(await p.getByRole('region',{name:'星际观景'}).count(),0);await p.waitForTimeout(150);const n=await p.evaluate(()=>window.__starScene.draws);await p.waitForTimeout(400);assert.equal(await p.evaluate(()=>window.__starScene.draws),n);await p.getByRole('button',{name:'结束演示',exact:true}).click();await p.getByLabel('搜索计划',{exact:true}).fill('');});
 await check('studio saves and exports all three native themes without changing clients',async()=>{await nav('美化工坊');await shot('workshop');await p.getByRole('button',{name:'主题创作',exact:true}).click();for(const [target,name]of [['codex','Codex 雾海'],['claude','Claude 雾海'],['deepseek','DeepSeek 雾海']]){await p.getByLabel('创作目标',{exact:true}).selectOption(target);await p.getByLabel('主题名称',{exact:true}).fill(name);await p.getByRole('button',{name:'保存到我的主题',exact:true}).click();await p.getByRole('button',{name:'已保存',exact:true}).waitFor();}const s=await p.evaluate(()=>window.starSleep.integrations());assert.equal(s.themes.length,3);assert.ok(!s.codexRestore&&!s.dshRestore);await shot('studio-native');});
 await check('Codex image ZIP uses selected local image, exports and reimports with duplicate detection',async()=>{await p.getByLabel('创作目标',{exact:true}).selectOption('codex-image');await p.getByLabel('主题名称',{exact:true}).fill('星枢 · 雾海');await p.getByRole('button',{name:/选择背景/}).first().click();await p.locator('.studio-preview').evaluate(e=>new Promise(r=>{const check=()=>e.style.backgroundImage?r():setTimeout(check,50);check();}));await shot('studio-image');await p.getByRole('button',{name:'保存到我的主题',exact:true}).click();await p.getByRole('button',{name:'已保存',exact:true}).waitFor();const file=path.join(out,'StarNexus-Codex-Mist.zip');await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},file);await p.getByRole('button',{name:'导出美化包',exact:true}).click();await p.waitForFunction(()=>document.body.innerText.includes('主题已导出'));const {unzipSync}=require('fflate'),parts=unzipSync(fs.readFileSync(file));assert.deepEqual(Object.keys(parts).sort(),['background.jpg','theme.css','theme.json']);const folder=path.join(out,'codex-image');fs.mkdirSync(folder,{recursive:true});for(const [name,bytes]of Object.entries(parts))fs.writeFileSync(path.join(folder,name),bytes);await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},file);const error=await p.evaluate(()=>window.starSleep.themeImport().then(()=>'',e=>String(e)));assert.match(error,/已在主题库/);const invalid=await p.evaluate(()=>window.starSleep.themeCreate({name:'bad',target:'exec'}).then(()=>'',e=>String(e)));assert.match(invalid,/无效/);});
 await check('layout at 100/125/150/200 percent retains navigation, editor and keyboard exit',async()=>{for(const [label,w,h,z]of [['100',1240,820,1],['compact',900,650,1],['125',1100,800,1.25],['150',1100,800,1.5],['200',900,650,2]]){await app.evaluate(({BrowserWindow},v)=>{const w=BrowserWindow.getAllWindows()[0];w.setSize(v.w,v.h);w.webContents.setZoomFactor(v.z);},{w,h,z});await p.waitForTimeout(160);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));await p.getByRole('button',{name:'设置',exact:true}).focus();assert.ok(await p.getByRole('button',{name:'设置',exact:true}).evaluate(e=>document.activeElement===e));await shot('studio-'+label);await nav('主控台');await p.keyboard.press('Control+n');await p.getByRole('dialog').waitFor();await p.keyboard.press('Escape');await nav('美化工坊');}await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];w.setSize(1240,820);w.webContents.setZoomFactor(1);});});
 await check('hidden and mini stop rendering; opt out survives restart; old branding absent in About',async()=>{await nav('主控台');await p.getByRole('button',{name:'设置',exact:true}).click();await p.getByRole('button',{name:'关于',exact:true}).click();assert.ok(!(await p.locator('.author-bio').innerText()).includes('AI'));await shot('about');await p.getByRole('button',{name:'外观',exact:true}).click();await p.getByRole('switch',{name:'启动动画',exact:true}).click();await p.keyboard.press('Escape');for(const mode of ['hide','mini']){if(mode==='mini')await p.evaluate(()=>window.starSleep.setMode('mini'));else await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].hide());await p.waitForTimeout(150);const n=await p.evaluate(()=>window.__starScene.draws);await p.waitForTimeout(350);assert.equal(await p.evaluate(()=>window.__starScene.draws),n);if(mode==='mini')await p.evaluate(()=>window.starSleep.setMode('full'));await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].show());}assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().length),1);await app.close();app=null;await launch();await p.getByRole('button',{name:'新建计划',exact:true}).waitFor();assert.equal(await p.getByRole('region',{name:'启动动画'}).count(),0);assert.equal((await p.evaluate(()=>window.starSleep.integrations())).themes.length,4);});
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({results,errors,data,safe:true},null,2));
}finally{if(app)await app.close();}})().catch(e=>{console.error(e);fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({error:String(e),results,errors},null,2));process.exitCode=1;});
