const {_electron:electron}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{randomUUID}=require('node:crypto'),{spawn}=require('node:child_process'),readline=require('node:readline');
const root=path.resolve(__dirname,'..'),out=path.join(root,'artifacts/v14'),data=path.join(root,'.qa-data','v14-'+Date.now());fs.mkdirSync(out,{recursive:true});fs.mkdirSync(data,{recursive:true});
const env={...process.env,STARSLEEP_QA_DATA:data};delete env.ELECTRON_RUN_AS_NODE;
let app,page,fake;const results=[],errors=[];
const record=async(name,fn)=>{await fn();results.push({name,passed:true});console.log('PASS',name);};
const state=()=>page.evaluate(()=>window.starSleep.integrations());
const shot=name=>page.screenshot({path:path.join(out,name+'.png')});
const wait=async(predicate,timeout=10000)=>{const until=Date.now()+timeout;while(Date.now()<until){if(await predicate())return;await new Promise(r=>setTimeout(r,150));}throw new Error('Condition timed out');};
async function launch(scale=1){app=await electron.launch({...(process.env.STARSLEEP_QA_EXE?{executablePath:process.env.STARSLEEP_QA_EXE}:{}),args:[...(process.env.STARSLEEP_QA_EXE?[]:[root]),'--safe-mode',`--force-device-scale-factor=${scale}`],env,timeout:60000});page=await app.firstWindow();page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message));await page.getByRole('button',{name:'Agent 与美化',exact:true}).waitFor();await page.evaluate(async()=>{const s=await window.starSleep.snapshot();await window.starSleep.settings({...s.settings,sound:false,volume:0,warningMinutes:1});});await app.evaluate(({dialog})=>{dialog.showMessageBox=async()=>({response:1,checkboxChecked:false});});}
let connection;
async function event(kind,extra={}){const body={provider:'codex',event:kind,sessionId:'desktop-qa',name:'夜间构建 · 安全验证',pid:app.process().pid,at:Date.now(),eventId:randomUUID(),...extra};const response=await fetch(`http://127.0.0.1:${connection.port}/event`,{method:'POST',headers:{Authorization:'Bearer '+connection.token},body:JSON.stringify(body)});assert.equal(response.status,200);return response.json();}
async function openPanel(){const button=page.locator('.agent-entry');if(!(await page.getByRole('heading',{name:'Agent 与美化',exact:true}).isVisible()))await button.click();}
const native='codex-theme-v1:'+JSON.stringify({variant:'dark',theme:{accent:'#ade3fa',surface:'#070e1b',ink:'#e0edf7'}});
(async()=>{
 await launch();connection=JSON.parse(fs.readFileSync(path.join(data,'agent-bridge','connection.json'),'utf8'));
 await record('theme import and clipboard configuration through real UI',async()=>{await openPanel();await page.getByRole('button',{name:'原界面美化',exact:true}).click();await page.getByRole('button',{name:'粘贴主题',exact:true}).click();await page.getByLabel('主题名称',{exact:true}).fill('星眠 · 冷蓝星舰');await page.getByLabel('主题代码',{exact:true}).fill(native);await page.getByRole('button',{name:'导入主题库',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await page.getByRole('button',{name:'复制主题代码',exact:true}).click();assert.equal(JSON.parse((await app.evaluate(({clipboard})=>clipboard.readText())).slice(15)).theme.accent,'#ade3fa');await shot('themes');});
 await record('DSH and Claude formats, duplicate rejection, backup and restore in isolated client directory',async()=>{await page.evaluate(async()=>{await window.starSleep.themeImportText('{"version":1,"colors":{"accent":"#5faaff","background":"#070e1b"}}','DeepSeek 午夜');await window.starSleep.themeImportText('{"name":"Claude 夜航","bgMain":"#070e1b","textPrimary":"#e0edf7"}','Claude 夜航');});const s=await state();assert.equal(s.themes.length,3);const claude=s.themes.find(t=>t.format==='claude-json');await page.evaluate(id=>window.starSleep.themeClaudeApply(id),claude.id);const file=path.join(data,'test-clients/claude/theme.json');assert.equal(JSON.parse(fs.readFileSync(file,'utf8')).bgMain,'#070e1b');await page.evaluate(()=>window.starSleep.themeClaudeRestore());assert.equal(fs.existsSync(file),false);assert.equal(await page.evaluate(async raw=>{try{await window.starSleep.themeImportText(raw,'again');return false;}catch{return true;}},native),true);});
 await record('connection config preserves foreign hooks, idempotent install and targeted uninstall',async()=>{const file=path.join(data,'test-clients/codex/hooks.json');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify({custom:'keep',hooks:{Stop:[{hooks:[{type:'command',command:'echo keep'}]}]}}));await page.evaluate(()=>window.starSleep.agentConnect('codex',true));const first=fs.readFileSync(file,'utf8');assert.equal(JSON.parse(first).custom,'keep');assert.equal(JSON.parse(first).hooks.Stop.length,2);await page.evaluate(()=>window.starSleep.agentConnect('codex',true));assert.equal(fs.readFileSync(file,'utf8'),first);await page.evaluate(()=>window.starSleep.agentConnect('codex',false));assert.equal(JSON.parse(fs.readFileSync(file,'utf8')).hooks.Stop.length,1);await page.evaluate(()=>window.starSleep.agentConnect('codex',true));await page.evaluate(()=>window.starSleep.agentConnect('claude',true));});
 await record('PowerShell hook bridge emits completion context and reports from a live process',async()=>{
   const fakeExe=path.join(data,'codex.exe');fs.copyFileSync(process.execPath,fakeExe);const runner=path.join(data,'fake-agent.cjs');fs.writeFileSync(runner,`const {spawnSync}=require('node:child_process');require('node:readline').createInterface({input:process.stdin}).on('line',line=>{const v=JSON.parse(line);const r=spawnSync('powershell.exe',['-NoProfile','-NonInteractive','-ExecutionPolicy','RemoteSigned','-File',${JSON.stringify(path.join(data,'agent-bridge/agent-hook.ps1'))},'-Provider',v.provider],{input:JSON.stringify(v.payload),encoding:'utf8',windowsHide:true});process.stdout.write(JSON.stringify({status:r.status,out:r.stdout,err:r.stderr})+'\\n');});`);
   fake=spawn(fakeExe,[runner],{stdio:['pipe','pipe','pipe'],windowsHide:true});const lines=readline.createInterface({input:fake.stdout});const send=(provider,payload)=>new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(new Error('Hook timeout')),10000);lines.once('line',line=>{clearTimeout(timeout);resolve(JSON.parse(line));});fake.stdin.write(JSON.stringify({provider,payload})+'\n');});
   const start=await send('codex',{hook_event_name:'UserPromptSubmit',session_id:'hook-test',turn_id:'one',cwd:root});assert.equal(start.status,0);const context=JSON.parse(start.out).hookSpecificOutput.additionalContext;assert.match(context,/STARSLEEP_DONE/);await page.evaluate(()=>window.starSleep.agentArm(['codex:hook-test']));
   const marker=context.match(/\[STARSLEEP_DONE:[a-f0-9]+\]/)[0];await send('codex',{hook_event_name:'Stop',session_id:'hook-test',turn_id:'one',cwd:root,last_assistant_message:'Done\n'+marker});await wait(async()=>(await state()).night.sessions.some(s=>s.id==='codex:hook-test'&&s.status==='completed'));fake.kill();fake=null;await wait(async()=>!(await state()).night.armed);
 });
 await record('multiple task selection and explicit confirmation, then waiting input cancels countdown eligibility',async()=>{await event('start');await event('start',{sessionId:'other',name:'文档与测试'});await page.getByRole('button',{name:'夜间联动',exact:true}).click();await page.getByLabel('监控 夜间构建 · 安全验证').check();await page.getByLabel('监控 文档与测试').check();await page.getByRole('button',{name:'等待 2 个任务后关机'}).click();await page.getByRole('button',{name:'确认开启夜间联动'}).click();assert.equal((await state()).night.selected.length,2);await event('waiting');assert.equal((await state()).night.deadline,null);await shot('agent');await page.evaluate(()=>window.starSleep.agentDisarm());});
 await record('hidden window continues monitoring; completed task restores full warning then safe executor runs',async()=>{
   const r=await event('start');const marker=r.context.match(/\[STARSLEEP_DONE:[a-f0-9]+\]/)[0];await page.evaluate(()=>window.starSleep.agentArm(['codex:desktop-qa']));await event('stop',{message:'完成\n'+marker});await page.evaluate(()=>window.starSleep.window('hide'));console.log('WAIT observation window 60 seconds');await wait(async()=>!!(await state()).night.deadline,70000);assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isVisible()),true);await page.getByRole('dialog',{name:'到时提醒'}).waitFor();await shot('agent-warning');await page.evaluate(()=>window.starSleep.window('hide'));console.log('WAIT safe shutdown deadline 60 seconds');await wait(async()=>{const s=await page.evaluate(()=>window.starSleep.snapshot());return s.logs.some(l=>l.text.includes('安全测试模式 · 已拦截实际关机'));},70000);assert.equal((await state()).night.armed,false);await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].show());
 });
 await record('pause removes armed watch and restart never re-arms it',async()=>{await event('start');await page.evaluate(()=>window.starSleep.agentArm(['codex:desktop-qa']));await page.evaluate(()=>window.starSleep.pause(true));assert.equal((await state()).night.armed,false);await page.evaluate(()=>window.starSleep.pause(false));await app.close();await launch();assert.equal((await state()).night.armed,false);assert.equal((await state()).night.sessions.length,0);assert.equal((await state()).themes.length,3);});
 await record('native-sized screenshots at common scales, with controls accessible',async()=>{for(const scale of [1,1.25,1.5,2]){if(scale!==1){await app.close();await launch(scale);}await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(900,650));await openPanel();await shot('agent-scale-'+scale);await page.getByRole('button',{name:'原界面美化',exact:true}).click();await shot('themes-scale-'+scale);assert.equal(await page.getByRole('button',{name:'导入美化包',exact:true}).isVisible(),true);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}});
 assert.deepEqual(errors,[]);await app.close();app=null;assert.equal(fs.existsSync(path.join(data,'agent-bridge/connection.json')),false);fs.writeFileSync(path.join(out,'qa-results.json'),JSON.stringify({version:'1.4.0',data,results,errors},null,2));console.log('DONE',results.length,'checks');
})().catch(e=>{console.error(e);fs.writeFileSync(path.join(out,'qa-results.json'),JSON.stringify({results,errors,error:String(e)},null,2));process.exitCode=1;}).finally(async()=>{fake?.kill();if(app)await app.close().catch(()=>{});});
