import type {ResourceItem} from './toolbox-types';
// Curated from the authors' README pages on 2026-09-22. Instructions are never executed here.
export const RESOURCES:ResourceItem[]=[
 {id:'ccusage',name:'ccusage',owner:'ccusage / ryoppippi',category:'tools',clients:['Codex','Claude Code'],summary:'把本地 Agent 会话转成按日、按月和按会话的用量报告。',useCase:'想知道 Token 花在哪里，比较模型和工作习惯。星枢的用量看板直接复用其 Windows 引擎。',setup:'星枢已内置 ccusage 20.0.24，无需额外安装。独立使用时按作者 README 选择 CLI 安装方式。',license:'MIT',url:'https://github.com/ccusage/ccusage',checked:'2026-09-22'},
 {id:'openai-skills',name:'OpenAI Skills',owner:'OpenAI',category:'skills',clients:['Codex'],summary:'官方维护的 Codex 技能目录，覆盖文档、开发和常用工作流。',useCase:'优先寻找与当前任务匹配的官方技能，而不是一次装入整个目录。',setup:'在 Codex 中使用 skill-installer 选择仓库中的具体技能；安装后按客户端提示刷新或重启。每个技能的依赖与许可需单独查看。',license:'按各技能 LICENSE 查看',url:'https://github.com/openai/skills',checked:'2026-09-22'},
 {id:'anthropic-skills',name:'Anthropic Skills',owner:'Anthropic',category:'skills',clients:['Claude Code','Claude'],summary:'官方技能示例，涵盖文档处理、设计和工作流程。',useCase:'处理 PDF、演示文稿、表格，或学习如何编写自己的技能。',setup:'Claude Code 可按 README 添加 anthropics/skills 市场并选择技能。Claude 桌面 Skills 的导入方式与 Code 插件不同，请按对应客户端说明操作。',license:'示例及文档技能许可不同，逐项查看',url:'https://github.com/anthropics/skills',checked:'2026-09-22'},
 {id:'claude-plugins',name:'Claude 官方插件目录',owner:'Anthropic',category:'plugins',clients:['Claude Code'],summary:'按用途收集 Claude Code 插件，包含技能、命令和外部工具接入。',useCase:'希望给 Code 会话补上特定工作能力，并在客户端管理启停。',setup:'在 Claude Code 插件界面搜索所需项目。仓库内各插件独立维护，普通 Claude Chat 不等于 Claude Code。',license:'按各插件 LICENSE 查看',url:'https://github.com/anthropics/claude-plugins-official',checked:'2026-09-22'},
 {id:'superpowers',name:'Superpowers',owner:'obra',category:'skills',clients:['Codex','Claude Code'],summary:'将需求讨论、计划、实现、测试与复核组织成可复用开发流程。',useCase:'任务一复杂就容易遗漏步骤，希望 Agent 有更明确的工程流程。',setup:'Codex 在 Plugins 中搜索 Superpowers；Claude Code 可按 README 从官方插件市场安装。不同客户端需分别配置。',license:'MIT',url:'https://github.com/obra/superpowers',checked:'2026-09-22'},
 {id:'antfu-skills',name:'antfu/skills',owner:'Anthony Fu',category:'skills',clients:['Codex','Claude Code'],summary:'面向前端与 JavaScript 生态的个人技能集合。',useCase:'使用 Vue、Vite、TypeScript 等工具，希望获得更贴近项目习惯的指导。',setup:'先查看技能目录，挑选匹配技术栈的条目；按仓库说明用 skills 工具或手动添加。客户端兼容性按单项确认。',license:'MIT',url:'https://github.com/antfu/skills',checked:'2026-09-22'},
 {id:'skills-cli',name:'skills',owner:'Vercel Labs',category:'tools',clients:['Codex','Claude Code'],summary:'从开源仓库发现和管理 Agent Skills 的命令行工具。',useCase:'需要跨项目管理技能，避免手工复制目录后忘记来源。',setup:'按作者 README 使用 npx skills。先列出可用技能，再选择目标客户端与安装范围；星枢只提供入口，不自动运行安装命令。',license:'MIT',url:'https://github.com/vercel-labs/skills',checked:'2026-09-22'},
 {id:'mcp-servers',name:'MCP 参考服务器',owner:'Model Context Protocol',category:'mcp',clients:['Codex','Claude','DeepSeek Harness'],summary:'MCP 官方参考实现与生态入口，展示文件、记忆和工具连接方式。',useCase:'让 Agent 连接明确需要的数据或工具，学习 MCP 配置结构。',setup:'选择一个服务器，查看其 README、所需运行时与访问范围，再在目标客户端的 MCP 设置中配置；各客户端格式不同。',license:'MIT；第三方链接按其许可',url:'https://github.com/modelcontextprotocol/servers',checked:'2026-09-22'},
 {id:'playwright-mcp',name:'Playwright MCP',owner:'Microsoft',category:'mcp',clients:['Codex','Claude','DeepSeek Harness'],summary:'通过 MCP 为 Agent 提供浏览器操作能力。',useCase:'测试网页、复现界面问题、验证完整用户流程。',setup:'按仓库中目标客户端配置示例添加 MCP 服务，需要相应 Node 与浏览器环境。首次操作时核对浏览器和访问范围。',license:'Apache-2.0',url:'https://github.com/microsoft/playwright-mcp',checked:'2026-09-22'},
 {id:'deepseek-harness',name:'DeepSeek Harness',owner:'DeepSeek AI',category:'plugins',clients:['DeepSeek Harness'],summary:'以插件为核心的 Agent Harness，提供官方插件与开发文档入口。',useCase:'为 DeepSeek 添加工具或工作流程，核对桌面版实际使用的 Profile。',setup:'从官方仓库文档查找插件及 Profile 配置。开发预览接口变化较快；先核对本机版本，不把 Web 与桌面 Profile 混用。',license:'MIT',url:'https://github.com/deepseek-ai/deepseek-harness',checked:'2026-09-22'}
];
